<div class="dux-tools">
    <div class="bread-head">用户节操B充值管理<span class="small">用户节操B充值</span>

<!--        <div class="float-right">-->
<!--            <a class="button button-small bg-main icon-list" href="/verse/index">金句列表</a>-->
<!--        </div>-->

    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/recharge/add">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <!-- tab head start-->
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>节操币充值</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">节操币充值</a></li>
                        </ul>
                    </div>
                </div>
                <!-- tab head end -->

                <!-- table body start-->
                <div class="tab-body">

                    <!-- tab 1 start -->
                    <div class="tab-panel active" id="tab-1">

                        <!--                        手机号-->
                        <div class="form-group">
                            <div class="label">
                                <label>手机号 * </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="mobile" name="mobile" size="60" datatype="*" placeholder="手机号">
                                <div class="input-note">请填写手机号</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="label">
                                <label>金额 * </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="money" name="money" size="60" datatype="*" placeholder="金额">
                                <div class="input-note">请填写金额</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="label">
                                <label>设备类型 * </label>
                            </div>
                            <div class="field">
                                <div class="button-group radio">
                                    <label class="button">
                                        <input name="device" value="IOS" type="radio" datatype="*" />
                                        <span class="icon icon-check text-green"></span> IOS
                                    </label>

                                    <label class="button">
                                        <input name="device" value="ANDROID" type="radio" datatype="*" />
                                        <span class="icon icon-check text-green"></span> ANDROID
                                    </label>

                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- tab 1 end -->

                </div>
                <!-- table body end-->

                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>