<div class="dux-tools">
    <div class="bread-head">
        客服列表
        <span class="small">
            管理后台客服
        </span>
    </div>
    <div class="tools-function clearfix">
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a> 
            <ul class="drop-menu pull-right">
                <li><a href="/kf/user/addtpl">添加用户</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">用户id</th>
                        <th width="150">账号</th>
                        <th width="100">客服昵称</th>
                        <th width="100">身份</th>
                        <th width="100">状态</th>
                        <th width="150">更新时间</th>
                        <th width="100">操作</th>
                    </tr>
                    <?php if($list) {?>
                    <?php foreach($list as $v):?>
                    <tr>
                        <td><?=$v['user_id']?></td>
                        <td><?=$v['username']?>
                        </td>
                        <td><?=$v['nickname']?>
                        </td>
                        <td style="word-wrap: break-word;word-break: break-word; "><?=$v['role']?>
                        </td>

                        <?php if($v['status'] == 1) {?>
                        <td><span class="bg-green"><?=$v['status_cn']?></span></td>
                        <?php }else{ ?>
                        <td><span class="bg-red"><?=$v['status_cn']?></span></td>
                        <?php }?>

                        <td><?=$v['create_time']?>
                        </td>
                        <td>
                            <a class="button bg-blue button-small icon-pencil" href="/kf/user/edittpl/user_id/<?php echo $v['user_id'] ?>" title="修改"></a>
                            <a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/kf/user/disable" data='{"user_id":<?php echo $v['user_id'] ?>}' title="删除"></a>
                        </td>
                    </tr>
                    <?php endforeach;?>
                    <?php }?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>