<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<div class="dux-tools">
    <div class="bread-head">生成商品兑换码</div>
</div>
<div class="admin-main">
    <form method="post" action="/cdkey/exec">

        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <!-- tab head end -->
                <!-- table body start-->
                <div class="tab-body">
                    <!-- tab 1 start -->
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>得到商品商城SKU自编码</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="sku_outer_id" name="sku_outer_id" size="60" datatype="*">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>	合同编号</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="contract_id" name="contract_id" size="60" datatype="*">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>合同数量</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="total" name="total" size="60" datatype="*">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>兑换码有效期</label>
                            </div>
                            <div class="field">
                                <input type="text" id="d4321" class="input datebtn" style="width:220px;" id="datetime" name="validity_time" value="<?=date('Y-m-d')?>" onfocus="WdatePicker({startDate:'<?=date('Y-m-d')?>',minDate:'<?=date('Y-m-d')?>'})" style="cursor:pointer;" size="60" datatype="*"  autocomplete="off">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>价格</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="price" name="price" size="2" datatype="*">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>兑换码商城上架自编码</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="batch_number" name="batch_number" size="60" datatype="*">
                            </div>
                        </div>

                    </div>
                    <!-- tab 1 end -->
                </div>
                <!-- table body end-->
                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <input class="button bg-main" type="submit" value="提交">
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>
<script type="text/javascript" charset="utf-8">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
    });
</script>