
<div class="dux-tools">
    <div class="bread-head">商品兑换码<span class="small">批次列表</span></div><br>
</div>
<!--生成兑换码和搜索信息-->
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/cdkey/index" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="sku_outer_id" name="sku_outer_id"  value="<?=$_GET['sku_outer_id']?>" placeholder="得到商品商城SKU自编码">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="batch_number" name="batch_number"  value="<?=$_GET['batch_number']?>" placeholder="兑换码商城上架自编码">
                    </div>&nbsp;
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
    <div class="float-right">
        <a href="/cdkey/add" class="button button-small bg-blue icon-plus dropdown-toggle">生成兑换码</a>&nbsp;
        <a href="/cdkey/nullifyTpl" class="button button-small bg-red icon-trash dropdown-toggle">作废兑换码</a>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                <tr>
                    <th width="*">批次ID</th>
                    <th width="*">得到商品商城SKU自编码</th>
                    <th width="*">兑换码商城上架自编码</th>
                    <th width="*">合同编号</th>
                    <th width="*">合同数量</th>
                    <th width="*">已兑换数量</th>
                    <th width="*">价格</th>
                    <th width="*">有效期</th>
                    <th width="*">创建时间</th>
                    <th width="*">操作</th>
                </tr>
                <?php if ($list) : ?>
                    <?php foreach ($list as $val) : ?>
                        <tr>
                            <td><?php echo $val['id']; ?></td>
                            <td><?php echo $val['sku_outer_id']; ?></td>
                            <td><?php echo $val['batch_number'];?></td>
                            <td><?php echo $val['contract_id'];?></td>
                            <td><?php echo $val['total'] ? :'--'; ?></td>
                            <td><?php echo $val['exchange_count'] ? :0; ?></td>
                            <td><?php echo $val['price'] ? : '--'; ?></td>
                            <td><?php echo $val['validity_time'] ? : '--'; ?></td>
                            <td><?php echo $val['create_time'] ? : '--'; ?></td>
                            <?php if($val['status'] == 3) {?>
                                <td><a class="button button-small bg-green" href="javascript:void(0)" >待生成</a></td>
                            <?php } elseif($val['status'] == 2) { ?>
                                <td><a class="button button-small bg-green" href="javascript:void(0)" >生成中..</a></td>
                            <?php } elseif($val['status'] == 1)  {?>
                                <td><a class="button button-small bg-green" href="/cdkey/export?cid=<?php echo $val['id']; ?>" >导出</a></td>
                            <?php } else {?>
                                <td><a class="button button-small" href="javascript:void(0)" >作废</a></td>
                            <?php } ?>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
        Do.ready('base', function () {
            $('#table').duxTable();
        });
    </script>
</div>