<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<div class="dux-tools">
    <div class="bread-head">查询兑换码信息</div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/cdkey/infoTpl" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="cdkey" name="cdkey"  value="" placeholder="兑换码">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                <tr>
                    <th width="*">兑换用户ID</th>
                    <th width="*">兑换时间</th>
                    <th width="*">兑换状态</th>
                    <th width="*">兑换码有效期</th>
                    <th width="*">得到商品商城SKU自编码</th>
                    <th width="*">序列号</th>
                </tr>
                <?php if ($list) : ?>
                    <tr>
                        <td><?php echo $list['uuid'] ? :'--';?></td>
                        <td><?php echo $list['exchange_time'] ? :'--';?></td>
                        <td><?php echo $list['status'] ? :'--';?></td>
                        <td><?php echo $list['validity_time'] ? :'--'; ?></td>
                        <td><?php echo $list['sku_outer_id'] ? :'--'; ?></td>
                        <td><?php echo $list['serial_num'] ? :'--'; ?></td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <script>
        Do.ready('base', function () {
            $('#table').duxTable();
        });
    </script>
</div>