<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<div class="dux-tools">
    <div class="bread-head">订单管理<span class="small">订单列表</span></div><br>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/bpfinance/index" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="label">
                        <label>请选择订单状态：</label>
                    </div>
                    <select class="input" name="status">
                        <option value="ALL"<?=($_GET['status'] == ALL) ? 'selected="selected"':'';?>>全部</option>
                        <option value="WAIT_SELLER_SEND_GOODS"<?=($_GET['status'] == WAIT_SELLER_SEND_GOODS) ? 'selected="selected"':'';?>>待发货</option>
                        <option value="TRADE_BUYER_SIGNED"<?=($_GET['status'] == TRADE_BUYER_SIGNED) ? 'selected="selected"':'';?>>已签收</option>
                        <option value="TRADE_CLOSED"<?=($_GET['status'] == TRADE_CLOSED) ? 'selected="selected"':'';?>>退款完成</option>
                        <option value="WAIT_BUYER_CONFIRM_GOODS"<?=($_GET['status'] == WAIT_BUYER_CONFIRM_GOODS) ? 'selected="selected"':'';?>>待确认收货</option>
                    </select>&nbsp;
                    <div class="field">
                        <input type="text" id="d4321" class="input datebtn" style="width:150px;" id="datetime" name="start_time" value="<?=$start_time;?>" onfocus="WdatePicker({maxDate:'#F{$dp.$D(\'d4322\',{d:-30})||\'%y-%M-%d\'}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="开始时间">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" id="d4322" class="input datebtn" style="width:150px;" id="datetime" name="end_time"  value="<?=$end_time;?>" onfocus="WdatePicker({maxDate:'#F{$dp.$D(\'d4321\',{d:30});}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="结束时间">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="number" size="20" value="<?=$mobile?>" placeholder="手机号">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="order_no" size="20" value="<?=$order_no?>" placeholder="订单号">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="showcase" size="20" style="width:80px" value="<?=$showcase?>" placeholder="店铺ID">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
                <div class="form-button">
                    <button class="button" type="submit" name="excel" id="excel" value="1">导出</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="*">订单号</th>
                        <th width="*">商品总价</th>
                        <th width="*">店铺ID</th>
                        <th width="*">买家UID</th>
                        <th width="*">收货人姓名</th>
                        <th width="*">收货人手机号</th>
                        <th width="120">订单状态</th>
                        <th width="*">支付方式</th>
                        <th width="*">详细地址</th>
                        <th width="*">邮政编码</th>
                        <th width="*">维权状态</th>
                        <th width="*">付款时间</th>
                        <!--<th width="100">操作</th>-->
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $val) : ?>
                            <tr>
                                <td><a href="/bporder/info?id=<?=$val['order_id']?>&showcase_id=<?=$val['showcase_id']?>"><?php echo $val['order_id']; ?></a></td>
                                <td><?php echo $val['total_fee']; ?></td>
                                <td><?php echo $val['showcase_id']; ?></td>
                                <td><?php echo $val['buyer_id'] ? : '--'; ?></td>
                                <td><?php echo $val['receiver_name'] ? :'--'; ?></td>
                                <td><?php echo $val['receiver_mobile'] ? : '--'; ?></td>
                                <?php
                                switch ($val['state']){
                                    case 'WAIT_BUYER_PAY':
                                        $bg = 'green';
                                        break;
                                    case 'WAIT_SELLER_SEND_GOODS':
                                        $bg = 'blue';
                                        break;
                                    case 'WAIT_BUYER_CONFIRM_GOODS':
                                        $bg = 'gray';
                                        break;
                                    case 'TRADE_BUYER_SIGNED':
                                        $bg = 'red';
                                        break;
                                    case 'TRADE_CLOSED':
                                        $bg = 'dot';
                                        break;
                                    case 'TRADE_CLOSED_BY_USER':
                                        $bg = 'dot';
                                        break;
                                }
                                
                                ?>
                                <td><span class="tag bg-<?=$bg?>"><?php echo $val['state_name']; ?></span></td>
                                <td><?php echo $val['pay_type'] ? : '--'; ?></td>
                                <td title="<?=$val['receiver_address']?>"><?php echo mb_substr($val['receiver_address'], 0,6 ,'gbk') ? :'--'; ?></td>
                                <td><?php echo $val['receiver_zip'] ? : '--'; ?></td>
                                <td><?php echo $val['feedback'] ? : '--'; ?></td>
                                <td><?php echo $val['pay_time']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php if($pagger):?>
    <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
        <?=$pagger?>
    </div>
<?php endif;?>
<script type="text/javascript" charset="utf-8">
        Do.ready('base',function() {
            $('.js-time').duxTime();
        });
</script>
</div>