<div class="dux-tools">
    <div class="bread-head">信息推送管理<span class="small">信息列表</span>
    </div>
    <br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main" href="/bpmessage?t=9">全部</a>
            <a class="button button-small bg-green" href="/bpmessage?t=0">待发送</a>
            <a class="button button-small bg-blue" href="/bpmessage?t=1">发送成功</a>
            <a class="button button-small bg-red" href="/bpmessage?t=2">丢弃不发</a>
        </div>
    </div> 
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="200">编号</th>
                        <th width="*">手机号码</th>
                        <th width="*">发送状态</th>
                        <th width="*">短信内容</th>
                        <th width="*">发送次数</th>
                        <th width="*">备注</th>
                        <th width="*">创建时间</th>
                        <th width="*">修改时间</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']?></td>
                                <td><?php echo $val['mobile']; ?></td>
                                <?php 
                                switch ($val['state']){
                                    case 0:
                                        $state = 'grren';
                                        break;
                                    case 1:
                                        $state = 'blue';
                                        break;
                                    case 2:
                                        $state = 'red';
                                        break;
                                        
                                }
                                ?>
                                <td><span class="tag bg-<?=$state?>"><?php if($val['state'] == 0) {echo "待发送";}elseif($val['state'] == 1){echo "发送成功";}else{echo "丢弃不发";} ?></span></td>
                                <td><?php echo $val['content'] ? : '--'; ?></td>
                                <td><?php echo $val['num'] ? :'--'; ?></td>
                                <td><?php echo $val['memo'] ? : '--'; ?></td>
                                <td><?php echo $val['ctime']; ?></td>
                                <td><?php echo $val['update_time']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>