<div class="dux-tools">
    <div class="bread-head">店铺管理<span class="small">操作记录</span></div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="" >
            <div class="form-inline">
                <select class="input js-assign" target="#tpl" name="showcase_id" datatype="*" id="parent">
                    <option value="">请选择店铺</option>
                    <?php foreach ($showcase_list as $showcase) : ?>
                        <option value="<?=$showcase['showcase_id']?>" <?=($showcase_id == $showcase['showcase_id']) ? 'selected': ''?>><?php echo $showcase['name']; ?></option>
                    <?php endforeach; ?>
                </select>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="*">ID</th>
                        <th width="*">操作标记</th>
                        <th width="*">操作来源</th>
                        <th width="*">接口名称</th>
                        <th width="*">操作结果</th>
                        <th width="*">操作人</th>
                        <th width="*">操作时间</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $key => $val) : ?>
                            <tr>
                                <td><?=$key+1?></td>
                                <td><?=$val['title']?></td>
                                <td><?=$val['source_id']?></td>
                                <td><?=$val['uri']?></td>
                                <td><?=$val['output']?></td>
                                <td><?=$val['nickname']?></td>
                                <td><?=$val['optime']?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
        Do.ready('base', function () {
        $('#table').duxTable();
        });
    </script>
</div>