<div class="dux-tools">
    <div class="bread-head">订单管理<span class="small">订单详情</span>
<!--        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/user/add">添加用户</a></li>
            </ul>
        </div>-->
    </div>

    <!-- <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main icon-list" href="javascript:;">
            内容列表</a>
        </div>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/admin.php?r=duxcms/AdminFormData/add&fieldset_id=1">添加内容</a></li>
            </ul>
        </div>
    </div> -->
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="panel-head"><strong>订单详情</strong>
        </div>
        <div class="table-responsive">
            <table class="table">
                <tbody>
                    <tr>
                        <td width="250" align="right">订单ID：</td>
                        <td><?=$oinfo[order_id]?></td>
                    </tr>
                    <tr>
                        <td align="right">店铺名称</td>
                        <td><?=$oinfo[showcase_name]?></td>
                    </tr>
                    <tr>
                        <td align="right">商品总价：</td>
                        <td><?=$oinfo[total_fee]?></td>
                    </tr>
                    <tr>
                        <td align="right">优惠金额：</td>
                        <td><?=$oinfo[discount_fee]?></td>
                    </tr>
                    <tr>
                        <td align="right">实付金额：</td>
                        <td><?=$oinfo[payment_fee]?></td>
                    </tr>
                    <tr>
                        <td align="right">邮费：</td>
                        <td><?=$oinfo[post_fee]?></td>
                    </tr>
                    <tr>
                        <td align="right">卖家UID：</td>
                        <td><?=$oinfo[seller_id]?></td>
                        </tr>
                    <tr>
                        <td align="right">买家UID：</td>
                        <td><?=$oinfo[buyer_id]?></td>
                    </tr>
                    <tr>
                        <td align="right">收货地址</td>
                        <td><?=$oinfo[receiver_province]?>省<?=$oinfo[receiver_city]?>市<?=$oinfo[receiver_address]?></td>
                    </tr>
                    <tr>
                        <td align="right">邮政编码：</td>
                        <td><?=$oinfo[receiver_zip]?></td>
                    </tr>
                    <tr>
                        <td align="right">收货人姓名：</td>
                        <td><?=$oinfo[receiver_name]?></td>
                    </tr>
                    <tr>
                        <td align="right">收货人手机号：</td>
                        <td><?=$oinfo[receiver_mobile]?></td>
                    </tr>
                    <tr>
                        <td align="right">外部交易编号：</td>
                        <td><?=$oinfo[outer_tid]?></td>
                    </tr>
                    <tr>
                        <td align="right">订单状态：</td>
                        <td><?=$oinfo[state_name]?></td>
                    </tr>
                    <tr>
                        <td align="right">支付类型：</td>
                        <td><?=$oinfo[pay_type]?></td>
                    </tr>
                    <tr>
                        <td align="right">付款时间：</td>
                        <td><?=$oinfo[pay_time]?></td>
                    </tr>
                    <tr>
                        <td align="right">订单创建时间：</td>
                        <td><?=$oinfo[create_time]?></td>
                    </tr>
                    <tr>
                        <td align="right">订单更新时间：</td>
                        <td><?=$oinfo[update_time]?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <br>
    <div class="panel dux-box">
        <div class="panel-head"><strong>商品列表</strong></div>
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100" style="text-align: center;">商品ID</th>
                        <th width="*">商品货号</th>
                        <th width="*">商品的SKU_ID</th>
                        <th width="*">商家编码</th>
                        <th width="*">SKU详情</th>
                        <th width="*">商品标题</th>
                        <th width="*">商品主图片地址</th>
                        <th width="*">购买数量</th>
                        <th width="*">商品售价</th>
                    </tr>
                    <?php if ($oinfo[order_detail]) : ?>
                        <?php foreach ($oinfo[order_detail] as $val) : ?>
                            <tr>
                                <td align="center"><?php echo $val['pid']; ?></td>
                                <td><?php echo $val['outer_pid']; ?></td>
                                <td><?php echo $val['sku_id']; ?></td>
                                <td><?php echo $val['outer_sku_id'] ? : '--'; ?></td>
                                <td><?php echo $val['sku_value'] ? :'--'; ?></td>
                                <td><?php echo $val['title'] ? : '--'; ?></td>
                                <td><?php echo $val['pic_path']; ?></td>
                                <td><?php echo $val['num']; ?></td>
                                <td><?php echo $val['price']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>