<div class="dux-tools">
    <div class="bread-head">商品管理<span class="small">商品详情</span>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="panel-head"><strong>商品详情</strong>
        </div>
        <div class="table-responsive">
            <table class="table" id="table">
                <tbody>
                    <tr>
                        <td width="250" align="right">商品ID：</td>
                        <td><?=$pinfo[product_id]?></td>
                    </tr>
                    <tr>
                        <td align="right">店铺ID：</td>
                        <td><?=$pinfo[showcase_id]?></td>
                    </tr>
                    <tr>
                        <td align="right">标题：</td>
                        <td><?=$pinfo[title]?></td>
                    </tr>
                    <tr>
                        <td align="right">售出数量：</td>
                        <td><?=$pinfo[sold_num]?></td>
                    </tr>
                    <tr>
                        <td align="right">价格</td>
                        <td><?=$pinfo[price]?></td>
                    </tr>
                    <tr>
                        <td align="right">运费：</td>
                        <td><?=$pinfo[post_fee]?></td>
                    </tr>
                    <tr>
                        <td align="right">商品主图：</td>
                        <td><img src="<?=$pinfo[pic_path]?>" width="200" /></td>
                    </tr>
                    <tr>
                        <td align="right">每人限购数量：</td>
                        <td><?=$pinfo[buy_quota_name]?></td>
                    </tr>
                    <tr>
                        <td align="right">上架状态：</td>
                        <td><?=$pinfo[onsell_name]?></td>
                    </tr>
                    <tr>
                        <td align="right">商品类型：</td>
                        <td><?=$pinfo[type_name]?></td>
                    </tr>
                    <tr>
                        <td align="right">创建时间：</td>
                        <td><?=$pinfo[create_time]?></td>
                    </tr>
                    <tr>
                        <td align="right">更新时间：</td>
                        <td><?=$pinfo[update_time]?></td>
                    </tr>
                    <tr>
                        <td>操作</td>
                        <td>
                            <!--<a class="button bg-blue button-small icon-pencil" href="/bpproduct/edit/id/<?=$pinfo[product_id]?>" title="编辑"></a>-->
                            <!--<a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/bpproduct/delete" data='{"id":<?=$pinfo[product_id]?>,"sid":<?=$pinfo['showcase_id']?>}' title="删除"></a>-->
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <br>
    <?php if ($pinfo[skus]) : ?>
    <div class="panel dux-box">
        <div class="panel-head"><strong>SKU列表</strong></div>
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100" style="text-align: center;">ID</th>
                        <th width="*">商品Id</th>
                        <th width="*">价格</th>
                        <th width="*">售出数量</th>
                        <th width="*">库存数量</th>
                        <th width="*">商品外部货号</th>
                        <?php if ($pinfo[skus][0][sku_pro]) : ?>
                        <?php foreach ($pinfo[skus][0][sku_pro] as $val) : ?>
                        <th width="*"><?=$val[k]?></th>
                        <?php endforeach; ?>
                        <?php endif; ?>
                    </tr>
                        <?php foreach ($pinfo[skus] as $val) : ?>
                            <tr>
                                <td align="center"><?php echo $val['id']; ?></td>
                                <td><?php echo $val['pid']; ?></td>
                                <td><?php echo $val['price']; ?></td>
                                <td><?php echo $val['sold_num'] ? : '--'; ?></td>
                                <td><?php echo $val['quantity'] ? :'--'; ?></td>
                                <td><?php echo $val['outer_id'] ? : '--'; ?></td>
                                <?php foreach ($val['sku_pro'] as $sku_pro) : ?>
                                <td><?=$sku_pro['v']; ?></td>
                                <?php endforeach; ?>
                            </tr>
                        <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php endif; ?>
        <!-- <div class="panel-foot table-foot clearfix">
            <ul class="pagination pagination-small">
                <li><a href="/admin.php?r=duxcms/AdminFormData/index&fieldset_id=1&page=1">首页</a></li>
                <li><a href="/admin.php?r=duxcms/AdminFormData/index&fieldset_id=1&page=1">上一页</a></li>
                <li class="active"><a href="/admin.php?r=duxcms/AdminFormData/index&fieldset_id=1&page=1">1</a></li>
                <li><a href="/admin.php?r=duxcms/AdminFormData/index&fieldset_id=1&page=1">下一页</a></li>
                <li><a href="/admin.php?r=duxcms/AdminFormData/index&fieldset_id=1&page=1">末页</a></li>
            </ul>
        </div> -->
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>