<div class="dux-tools">
    <div class="bread-head">商品管理<span class="small">商品列表</span></div><br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main" href="/bpproduct/index?type=">全部</a>
            <a class="button button-small bg-green" href="/bpproduct/index?type=0">实物商品</a>
            <a class="button button-small bg-green" href="/bpproduct/index?type=1">卡卷</a>
            <a class="button button-small bg-green" href="/bpproduct/index?type=2">会员</a>
            <a class="button button-small bg-green" href="/bpproduct/index?type=3">第三方商品</a>
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/bpproduct/index" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="pname" size="20" value="<?=$pname?>" placeholder="商品名">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="showcase_id" size="20" value="<?=$showcase_id?>" placeholder="店铺ID">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="*">ID</th>
                        <th width="*">店铺ID</th>
                        <th width="*">标题</th>
                        <th width="*">价格</th>
                        <th width="*">类型</th>
                        <th width="100">状态</th>
                        <th width="100">访问</th>
                        <th width="*">修改时间</th>
                        <th width="*">发布时间</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['product_id']; ?></td>
                                <td><?php echo $val['showcase_id']; ?></td>
                                <td><a href="/bpproduct/info?id=<?php echo $val['product_id']; ?>"><?php echo $val['title']; ?><a><?=$val['presell'] ? '<span class="tag bg-red">预售<span>':''; ?></td>
                                <td><?php echo $val['price']; ?></td>
                                <td><?php echo $val['type_name'] ? :'--'; ?></td>
                                <td><span class="tag bg-<?=$val['onsell'] == 1 ? 'green':'red'; ?>"><?=$val['onsell_name'] ? :'--'; ?></span></td>
                                <td><?=$val['uv'].' / '.$val['pv']; ?></td>
                                <td><?php echo $val['update_time']; ?></td>
                                <td><?php echo $val['create_time']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>