<div class="dux-tools">
    <div class="bread-head">商品管理<span class="small">编辑商品</span>

        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/bpproduct">
            商品列表</a>  
        </div>

    </div>

    <!-- <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main icon-list" href="javascript:;">
            内容列表</a>
        </div>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/admin.php?r=duxcms/AdminFormData/add&fieldset_id=1">添加内容</a></li>
            </ul>
        </div>
    </div> -->
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/bpproduct/edit">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <!-- tab head start-->
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>商品管理</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">编辑商品</a></li>
                        </ul>
                    </div>
                </div>
                <!-- tab head end -->

                <!-- table body start-->
                 <div class="tab-body">

                    <!-- tab 1 start -->
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>商品ID</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="product_id" name="product_id" size="60" datatype="*" value="<?php echo $product['product_id']; ?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>店铺ID</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="showcase_id" name="showcase_id" size="60" datatype="*" value="<?php echo $product['showcase_id']; ?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>标题</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="title" name="title" size="60" datatype="*" placeholder="标题" value="<?php echo $product['title']; ?>">
                                <div class="input-note">请填写标题</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>商品摘要</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="intro" name="intro" size="60" datatype="*" value="<?php echo $product['intro']; ?>">
                                <div class="input-note">请填写商品摘要</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>商品介绍</label>
                            </div>
                            <div class="field">
                                <textarea class="input" style="width:220px;height: 150px;" id="description" name="description" size="60" datatype="*"><?php echo $product['description']; ?></textarea>
                                <div class="input-note">请填写商品介绍</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>库存数量</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="quantity" name="quantity" size="60" datatype="*" value="<?php echo $product['quantity']; ?>" <?php if($product[skus]) echo"disabled" ?>>
                                <div class="input-note">请填写库存数量</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>价格</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="price" name="price" size="60" datatype="*" value="<?php echo $product['price']; ?>">
                                <div class="input-note">请填写价格</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>运费</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="post_fee" name="post_fee" size="60" datatype="*" value="<?php echo $product['post_fee']; ?>">
                                <div class="input-note">请填写运费</div>
                            </div>
                        </div>
<!--                        <div class="form-group">
                            <div class="label">
                                <label>商品主图</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="price" name="price" size="60" datatype="*" value="<?php echo $product['price']; ?>">
                                <div class="input-note">请填写价格</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>展示图片</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="price" name="price" size="60" datatype="*" value="<?php echo $product['price']; ?>">
                                <div class="input-note">请填写价格</div>
                            </div>
                        </div>-->
                        <div class="form-group">
                            <div class="label">
                                <label>每人限购数量</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="buy_quota" name="buy_quota" size="60" datatype="*" value="<?php echo $product['buy_quota']; ?>">
                                <div class="input-note">请填写每人限购数量</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>商品类型<?=$product[product_type]?></label>
                            </div>
                            <div class="field">
                                <div class="button-group radio">
                                    <label class="button <?php if (0 == $product['type']) : ?> active <?php endif;?>">
                                        <input name="type" value="0" type="radio" <?php if ($product['product_type'] == 0) : ?> checked <?php endif;?>>
                                        <span class="icon icon-check text-green"></span> 实物
                                    </label>

                                    <label class="button <?php if (1 == $product['type']) : ?> active <?php endif;?>">
                                        <input name="type" value="1" type="radio" <?php if ($product['product_type'] == 1) : ?> checked <?php endif;?>>
                                        <span class="icon icon-check text-green"></span> 手艺
                                    </label>
                                    <label class="button <?php if (2 == $product['type']) : ?> active <?php endif;?>">
                                        <input name="type" value="2" type="radio" <?php if ($product['product_type'] == 2) : ?> checked <?php endif;?>>
                                        <span class="icon icon-check text-green"></span> 组局
                                    </label>

                                    <label class="button <?php if (3 == $product['type']) : ?> active <?php endif;?>">
                                        <input name="type" value="3" type="radio" <?php if ($product['product_type'] == 3) : ?> checked <?php endif;?>>
                                        <span class="icon icon-check text-green"></span> 众筹
                                    </label>

                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- tab 1 end  -->
                </div>
                <!-- table body end -->

                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script  type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
    });
</script>