<div class="dux-tools">
    <div class="bread-head">店铺管理<span class="small">店铺信息</span>
    </div>
</div>
<div class="panel dux-box">
        <div class="panel-head"><strong>店铺信息</strong>
        </div>
        <div class="table-responsive">
            <table class="table" id="table">
                <tbody>
                    <tr>
                        <td width="250" align="right">用户ID：</td>
                        <td><?=$showcase['user_id']?></td>
                    </tr>
                    <tr>
                        <td align="right">店铺ID：</td>
                        <td><?=$showcase['showcase_id']?></td>
                    </tr>
                    <tr>
                        <td align="right">店铺名称：</td>
                        <td><?=$showcase['name']?></td>
                    </tr>
                    <tr>
                        <td align="right">掌柜名称：</td>
                        <td><?=$showcase['nickname']?></td>
                    </tr>
                    <tr>
                        <td align="right">掌柜签名：</td>
                        <td><?=$showcase['signature']?></td>
                    </tr>
                    <tr>
                        <td align="right">店铺LOGO：</td>
                        <td><img src="<?=$showcase['logo']?>" width="200" /></td>
                    </tr>
                    <tr>
                        <td align="right">店铺APPID</td>
                        <td><?=$showcase['appid']?></td>
                    </tr>
                    <tr>
                        <td align="right">店铺appsecret</td>
                        <td><?=$showcase['appsecret']?></td>
                    </tr>
                    <tr>
                        <td align="right">店铺介绍</td>
                        <td><?=$showcase['intro']?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<script  type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#table').duxTable();
    });
</script>