<div class="dux-tools">
    <div class="bread-head">店铺管理<span class="small">店铺审核</span>

        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/bpshowcase">
            店铺列表</a>  
        </div>

    </div>

    <!-- <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main icon-list" href="javascript:;">
            内容列表</a>
        </div>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/admin.php?r=duxcms/AdminFormData/add&fieldset_id=1">添加内容</a></li>
            </ul>
        </div>
    </div> -->
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/bpshowcase/edit">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <!-- tab head start-->
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>店铺管理</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="javascript:;">店铺审核</a></li>
                        </ul>
                    </div>
                </div>
                <!-- tab head end -->

                <!-- table body start-->
                 <div class="tab-body">

                    <!-- tab 1 start -->
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>用户ID</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="showcase_id" name="showcase_id" size="60"  value="<?php echo $info['user_id']; ?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>真实姓名</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="title" name="title" size="60" placeholder="标题" value="<?php echo $info['realname']; ?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>自我介绍</label>
                            </div>
                            <div class="field">
                                <textarea class="input" style="width:220px;height: 150px;" id="description" name="description" size="60" readonly><?php echo $info['intro']; ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>手机号码</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="intro" name="intro" size="60"  value="<?php echo $info['mobile']; ?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>微信号码</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="intro" name="intro" size="60"  value="<?php echo $info['wechat']; ?>"readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>证件照片</label>
                            </div>
                            <div class="field">
                                <img src="<?php echo $info['id_photo']; ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>身份证号码</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="intro" name="intro" size="60" value="<?php echo $info['id_num']; ?>"readonly>
                            </div>
                        </div>
                    </div>
                    <!-- tab 1 end  -->
                </div>
                <!-- table body end -->

                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <button class="button bg" type="reset">加入黑名单</button>
                        <?php if ($info['status_person'] == "1" ) : ?>
                        <a href="javascript:;" url="/bpshowcase/unpass" data='{"id":"<?=$showcase_id?>","type":"<?=$type?>"}' title="驳回" class="button bg js-open" success="location.reload()">驳回</a>
                        <a href="javascript:;" url="/bpshowcase/pass" data='{"id":"<?=$showcase_id?>","type":"<?=$type?>"}' title="通过认证" class="button bg-main js-action" success="location.reload()">通过认证</a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script  type="text/javascript">
    var showcaseTitle = '驳回认证申请';
    var showcaseContent = <?=$refuse?>;
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxTable();
        
    });
</script>