<div class="dux-tools clearfix">
    <div class="bread-head">电子发票<span class="small">sku列表</span></div>
    <div class="button-group float-right">
<!--        <a class="button button-small bg-dot icon-plus dropdown-toggle"> 录入 <span class="downward"></span></a>-->
<!--        <ul class="drop-menu pull-right">-->
<!--            <li><a href="/invoice/addsku">录入SKU信息</a></li>-->
<!--        </ul>-->
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <div class="form-inline">
            <label><b>上传需要开票SKU编码:</b></label>
            <div class="form-button">
                <input type="text" class="input show_uo_imgs" id="files" name="file" placeholder="开票SKU编码上传" readonly=""/>
                <a class="button bg-blue button-small " data="files" id="image_upload3" preview="image_preview3" href="javascript:;"><span class="icon-upload">上传</span></a>
            </div>
        </div>
    </div>
    <div class="float-left">
        <form action="/invoice/ckd" method="GET" >
            <div class="form-inline">
                <div class="form-group" style="margin-left:10px;">
                    <label><b>请输入搜索条件:</b></label>
                    <div class="field" style="margin-left: 5px;">
                        <input type="text" class="input" name="sku_id" size="20" value="<?=$info['sku_id']?>" placeholder="填写sku编码">
                    </div>
                </div>
                <div class="form-button" style="margin-left:20px;">
                    <button class="button bg-main" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <thead>
                    <tr>
                        <th width="*">编号</th>
                        <th width="*">父级编码</th>
                        <th width="*">子级编码</th>
                        <th width="*">商品名称</th>
                        <th width="*">税率</th>
                        <th width="*">金额</th>
                        <th width="*">选项</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($data) : ?>
                        <?php foreach ($data['data'] as $val) : ?>
                            <tr>
                                <td><span class="idval"><?=$val['id']?></span></td>
                                <td><?=$val['parent_sku_id']?></td>
                                <td><?=$val['kind_sku_id']?></td>
                                <td><?=$val['title']?></td>
                                <td><?=$val['tax_rate']?></td>
                                <td><input type="text" name="jine" class="input jine" style="width:80px;" value="<?=$val['payment']?>"></td>
                                <td><button class="button bg-main submit" type="button" >设置</button></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
        Do.ready('base', function () {
            $('#form').duxForm();
            $('#image_upload3').duxFileUpload({
                uploadUrl: '/invoice/ckdUpload',
                type: 'xls',
                complete: function (data) {
                    alert('上传成功,个别失败');
                    $('.skvdiv').css('display','block');
                    $('.skuval').append(data);
                }
            });
        });

        $('.submit').on('click',function(){
            var oTr = $(this).parents('td').parents('tr');
            var oVal = oTr.find('.jine').val();
            var idVal = oTr.find('.idval').text();
            if(oVal == ''){
                alert('金额不能为空');
                return;
            }
            $.ajax({
                type: 'POST',
                dataType: 'JSON',
                url: '/invoice/ckd',
                data: {id:idVal,money:oVal}
            }).done(function(data){
                if(data.code == 1){
                    alert('设置成功');
                    return;
                }
                alert('设置失败');
                return;
            })

        })
        
        //全选
       $('#selectAll').bind('click', function(){
           $('.checkAll').prop('checked', true);
           
       });
       
       //全选
       $('#unselectAll').bind('click', function(){
            $('.checkAll').prop('checked', false);
       });
       
       $('.set').on('click', function(){
           var orders = '';
           var fpsl = $('#parent option:selected').val();
           if (!$('.checkAll').prop('checked')){
               alert('请先选择');
               return false;
           }
            $(".checkAll").each(function(){
                if ($(this).prop("checked")) {
                    orders += $(this).val() + ","; 
                }
            });
            
            $.ajax({
                type: 'POST',
                dataType: 'JSON',
                url: '/invoice/updatesl',
                data: {orderlist:orders,sl:fpsl}
            }).done(function (data){
                alert(data.msg);
                window.location.reload();
            })
       })
    </script>
</div>