<div class="dux-tools">
    <div class="bread-head">电子发票<span class="small">需要开发票订单列表</span></div><br>
</div>
<div class="tools-function clearfix">
    <div class="float-left">
        <div class="form-inline">
            <label><b>上传需要开票订单号:</b></label>
            <div class="form-button">
                <input type="text" class="input show_uo_imgs" id="files" name="file" placeholder="开票订单上传" readonly=""/>
                <a class="button bg-blue button-small " data="files" id="image_upload3" preview="image_preview3" href="javascript:;"><span class="icon-upload">上传</span></a>
            </div>
        </div>
    </div>
    <div class="float-left" style="margin-left: 10px;">
        <div class="form-inline">
            <div class="form-button">
                <button class="button bg-dot" type="button" id="selectAll">选中全部</button>
                <button class="button bg-sub" type="button" id="unselectAll">取消全选</button>
                <button class="button bg-main" type="button" id="batch" value=1>批量开票</button>
            </div>
        </div>
    </div>
</div><br>
<div class="tools-function clearfix">
    <div class="float-left">
        <form method="GET" action="/invoice/showlist" >
            <div class="form-inline">
                <label><b>搜索相关订单:</b></label>
                <div class="form-group">
                    <div class="field" style="margin-left: 5px;">
                        <input type="text" class="input" name="mobile" size="20" value="<?=$mobile?>" placeholder="请填写手机号">
                        <input type="text" class="input" name="order_id" size="20" value="<?=$order_id?>" placeholder="请填写订单号">
                    </div>
                    <label style="margin-left: 5px;"><b>选择状态:</b></label>
                    <div class="field">&nbsp;
                        <select class="input js-assign" style="text-align: center" name="status">
                            <option value=""><?php echo isset($status) ? $status : '全部状态'; ?></option>
                            <option value="1">未开发票</option>
                            <option value="2">开票成功</option>
                            <option value="3">开票失败</option>
                        </select>
                    </div>
                </div>
                <div class="form-button">
                    <button class="button bg-mix" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div><br>
<div class="tools-function clearfix">
    <div class="float-left">
        <div class="float-left">
            <div class="form-inline">
                <label><b>设置开票信息:</b></label>
                <div class="form-group">
                    <div class="field" style="margin-left: 5px;">
                        <input type="text" class="input" name="address" style="width: 300px;" value="<?=$invoice_info['seller_address']?>" placeholder="请设置销售方地址电话">
                        <input type="text" class="input" name="kpr" value="<?=$invoice_info['drawer']?>" placeholder="请设置开票人">
                        <input type="text" class="input" name="xsf_mc" style="width: 200px;" value="<?=$invoice_info['seller_name']?>" placeholder="请设置销售方名称">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button bg-red" type="submit" id="set">设置</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  $(function (){
      $('#set').on('click', function(){
          var xsf_mc = $(':input[name="xsf_mc"]').val();
          var kpr = $(':input[name="kpr"]').val();
          var address = $(':input[name="address"]').val();
          
          $.ajax({
              type: 'POST',
              dataType: 'JSON',
              url: '/invoice/setinvoice',
              data : {xsf_mc:xsf_mc,kpr:kpr,address:address}
          }).done(function(data){
              alert(data.msg);
              window.location.reload();
          })
      })
  })
</script>
<!-- 隐藏输入框 -->
<div style="position: absolute; left: 400px; top: 300px; background: #2c7; display: none; width: 200px; height: 200px;" id="id_box">
    <h4 style="text-align: center;"><b>开具红字发票此项为必填项</b></h4>
    <br>
    <input type="text" class="input" size="20"  placeholder="请填写原发票号码" name="v1">
    <br>
    <input type="text" class="input" size="20"  placeholder="请填写原发票代码" name="v2">
    <br>
    <div class="form-button">
        <input class="button bg-main" type="submit" value="提交" id="submit" style="float: left"/>
        <button class="icon-close button bg-gray" style="float:right">关闭</button>
    </div>
</div>
<!-- list -->
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <thead>
                    <tr>
                        <th width="*">选项</th>
                        <th width="*">编号</th>
                        <th width="*">订单号</th>
                        <th width="*">发票台头</th>
                        <th width="*">价税合计</th>
                        <th width="*">合计金额</th>
                        <th width="*">合计税额</th>
                        <th width="*">消费者手机号</th>
                        <th width="*">税率</th>
                        <th width="*">发票类型</th>
                        <th width="*">项目名称</th>
                        <th width="*">操作</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($data) : ?>
                        <?php foreach($data['data'] as $val) : ?>
                            <tr id="list">
                                <td><input type="checkbox" class="checkAll" value="<?=$val['order_id']?>"></td>
                                <td><a href="<?=$invoice_info['host']?>/soap/getinvoice?id=<?=$val['id']?>" target="_blank"><span class="autoid"><?php echo $val['id']; ?></span></td>
                                <td><?php echo $val['order_id']; ?></td>
                                <td><span class="title"><?php echo $val['invoice_title'];?></span></td>
                                <td><?php echo $val['payment_fee']; ?></td>
                                <td><?php echo $val['total_fee']; ?></td>
                                <td><?php echo $val['total_tax']?></td>
                                <td>
                                    <input type="hidden" value="<?=$val['state']?>" class="hidd">
                                    <span class="phone"><?php echo $val['buyer_phone']; ?></span>
                                </td>
                                <td><span class="tax_rate"><?php echo $val['tax_rate']?></span></td>
                                <td><span class="type"><?php echo $val['invoice_type'] == 1 ? '<span class="tag bg-red">红字发票</span>' : '<span class="tag bg-blue">蓝字发票</span>';?></span></td>
                                <td><?php echo $val['project_name']?></td>
                                <td>
                                    <?php if($val['state'] == 2 || $val['state'] == 4):?>
                                        <a class="button bg-green button-small icon-eye-open" href="<?php echo $val['invoice_url'];?>" target="_blank" >查看发票</a>
                                        <a class="button bg-red button-small icon-pencil" href="javascript:;" style="margin-left: 5px;">补开红票</a>
                                        <a class="button bg-yellow button-small icon-envelope sendmessage" href="javascript:;" style="margin-left: 5px;">重发短信</a>
                                    <?php else:?>
                                        <button class="button bg-blue button-small kaifapiao" value=2 style="">开具发票</button>
                                    <?php endif;?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
    Do.ready('base', function () {
        $('#form').duxForm();
        $('#image_upload3').duxFileUpload({
            uploadUrl: '/invoice/upload',
            type: 'xls',
            complete: function (data) {
               $('.show_uo_imgs').val(data.code);
            }
        });
        
    });
    
    //批量开票
       $('#batch').on('click', function(){
            var orders = [];
            $(".checkAll").each(function(i){
                if ($(this).prop("checked")) {
                    var oTmp = {};
                    oTmp.order = $('.checkAll').val();
                    oTmp.sl = $('.tax_rate').eq(i).text();
                    oTmp.title = $('.title').eq(i).text();
                    oTmp.id = $('.autoid').eq(i).text();
                    oTmp.phone = $('.phone').eq(i).text();
                    orders.push(oTmp);
                }
            });
            
            address = $(':input[name="address"]').val();
            xsf_mc = $(':input[name="xsf_mc"]').val();
            kpr = $(':input[name="kpr"]').val();
            
            $.ajax({
                type: 'POST',
                dataType: 'JSON',
                url: '/soap/index',
                data: {order_id:orders,type:0,kpr:kpr,xsf_mc:xsf_mc,address:address}
            }).done(function (data){
                alert(data.msg);
                window.location.reload();
            });
       })
       
    // 税率
//    $(function(){
//        $('#select').on('change', function(){
//            var iVal = $(this).val();
//            var aSelect = $(".fpsl");
//            $.each(aSelect, function (i, ele) {
//                var aP = $(ele).find('option');
//                aP.map( function () {
//                    if ($(this).val() == iVal) {
//                        $(this).attr('selected', true);
//                    }
//                });
//            })
//        });
//    });
    
    //重新发送短信
    $(function(){
        $('.sendmessage').on('click', function(){
            var oTr = $(this).parent('td').parent('tr');
            var order_id = oTr.find('td').eq(2).text();
            var id = oTr.find('td').eq(1).text();
            $.ajax({
                type : 'GET',
                dataType :'JSON',
                url : '/invoice/repeatmessage',
                data : {order_id:order_id,id:id}
            }).done(function(data){
                alert(data.msg);
            })
        });
    })
    
    //开电子发票
    $( function () {
        
       var oData = {};
       
       $('.kaifapiao').on('click', function(){
            var oTr = $(this).parent('td').parent('tr');
            oData.order_id = oTr.find('td').eq(2).text();
            oData.type = 0;
            oData.address = $(':input[name="address"]').val();
            oData.xsf_mc = $(':input[name="xsf_mc"]').val();
            oData.kpr = $(':input[name="kpr"]').val();
            oData.fpsl = oTr.find('td').eq(8).text();
            oData.title = oTr.find('td').eq(3).text();
            oData.id = oTr.find('td').eq(1).text();
            oData.phone = oTr.find('td').eq(7).text();
            
            postData(oData);
       });
       
       // 重新开票弹出层
       $(".icon-pencil").on('click', function () {
            var oBox = $('#id_box');
            var oTr = $(this).parent('td').parent('tr');
            oData.order_id = oTr.find('td').eq(2).text();
            oData.type = 1;
            oData.fpsl = oTr.find('.tax_rate').text();
            oData.address = $('input[name="address"]').val();
            oData.id = oTr.find('td').eq(1).text();
            oData.title = oTr.find('td').eq(3).text();
            oData.phone = oTr.find('td').eq(7).text();
            oData.kpr = $(':input[name="kpr"]').val();
            oData.xsf_mc = $(':input[name="xsf_mc"]').val();
                $(oBox).show('fast');
                // 禁止 href
                return false;
       });
       
       // 关闭
       $(".icon-close").on('click', function () {
           $('#id_box').hide();
       });
       
       //弹出层提交
       $("#submit").on('click', function () {
            oData.yfp_hm = $.trim($("input[name='v1']").val());
            oData.yfp_dm = $.trim($("input[name='v2']").val());
           
           if (oData.yfp_hm && oData.yfp_dm) {
               postData(oData);
           } else {
               alert('原发票号码、代码不能为空');
           }
       }); 
       
       //全选
       $('#selectAll').bind('click', function(){
            $(".type > span").each(function(i){
                //只能选中未开票的
                var iHidd = $('#table > tbody').find('tr').eq(i).find('.hidd').val();
                if ($(this).hasClass('bg-blue') &&  (iHidd == 1 || iHidd == 3)) {
                    $('.checkAll').eq(i).prop('checked', true);
                }
            });
       });
       
       //全选
       $('#unselectAll').bind('click', function(){
            $('.checkAll').prop('checked', false);
       });
       
       //ajax
       function postData(data)
       {
           $.ajax({
               type: "POST",
               dataType: "JSON",
               url: '/soap/index',
               data: data
           }).done( function (data) {
               alert(data.msg);
               window.location.reload();
           }).fail( function (a) {
               console.log(a + ' fail ');
               window.location.reload();
           });
       }
       
    });
</script>