<div class="dux-tools">
    <div class="bread-head">电子发票<span class="small">需要开发票订单列表</span></div>
    <br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <div class="float-left">
                <form method="GET" action="/invoice/showlist" enctype="multipart/form-data" id="form">
                    <div class="form-inline">
                        <div class="form-button">
                            <input type="file" class="button" name="import" />
                            <button class="button bg-main" type="submit" id="import" name="import" value="import">导入数据</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="float-left" style="margin-left: 10px;">
                <form method="GET" action="/invoice/showlist">
                    <div class="form-inline">
                        <div class="form-group">
                            <div class="form-button">
                                <label>请选择发票税率:</label>&nbsp;
                                <select class="input js-assign" name="fpsl" id="select" style="width: 50px;">
                                    <?php foreach ($tax_rate as $tax_val): ?>
                                        <option value='<?php echo $tax_val?>'><?php echo $tax_val;?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                            <div class="field" style="margin-left: 5px;">
                                <input type="text" class="input" name="mobile" size="20" value="<?=$mobile?>" placeholder="请填写手机号">
                                <input type="text" class="input" name="order_id" size="20" value="<?=$order_id?>" placeholder="请填写订单号">
                            </div>
                        </div>
                        <div class="form-button">
                            <button class="button" type="submit">搜索</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div style="position: absolute; left: 400px; top: 300px; background: #2c7; display: none; width: 200px; height: 200px;" id="id_box">
    <h4 style="text-align: center;"><b>开具红字发票此项为必填项</b></h4>
    <br>
    <input type="text" class="input" size="20"  placeholder="请填写原发票号码" name="v1">
    <br>
    <input type="text" class="input" size="20"  placeholder="请填写原发票代码" name="v2">
    <br>
    <div class="form-button">
        <input class="button bg-main" type="submit" value="提交" id="submit" style="float: left"/>
        <button class="icon-close button bg-gray" style="float:right">关闭</button>
    </div>
</div>

<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="*">订单号</th>
                        <th width="*">发票台头</th>
                        <th width="*">价税合计</th>
                        <th width="*">合计金额</th>
                        <th width="*">合计税额</th>
                        <th width="*">消费者手机号</th>
                        <th width="*">税率</th>
                        <th width="*">销售方地址电话</th>
                        <th width="*">发票类型</th>
                        <th width="*">操作</th>
                    </tr>
                    <?php if ($data) : ?>
                        <?php foreach($data['data'] as $val) : ?>
                            <tr>
                                <td><?php echo $val['order_id']; ?></td>
                                <td><?php echo $val['invoice_title']; ?></td>
                                <td><?php echo $val['payment_fee']; ?></td>
                                <td><?php echo $val['total_fee']; ?></td>
                                <td><?php echo $val['total_tax']?></td>
                                <td><?php echo $val['buyer_phone']; ?></td>
                                <td><select class="input js-assign fpsl" name="fpsl" style="width: 50px;">
                                       <?php foreach ($tax_rate as $tax_val): ?>
                                        <option value='<?php echo $tax_val?>'><?php echo $tax_val;?></option>
                                        <?php endforeach;?>
                                    </select>
                                </td>
                                <td><input name="xsf_dzdh" type="text" class="input" value="<?php echo $seller_address;?>"></input></td>
                                <td>
                                    <select class="input js-assign" name="type" style="width: 70px">
                                        <option value="0">蓝字发票</option>
                                        <option value="1">红字发票</option>
                                    </select>
                                </td>
                                <td>
                                    <?php if($val['state'] == 2):?>
                                    <a class="button bg-green button-small icon-eye-open" href="/soap/getinvoice/order_id/<?php echo $val['order_id'];?> " target="_blank" >查看发票</a>
                                    <?php else:?>
                                        <a class="button bg-blue button-small icon-pencil" href="javascript:;">开具发票</a>
                                    <?php endif;?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
    });
    
    // 税率
    $(function(){
        $('#select').on('change', function(){
            
            var _that = $(this);
            var iVal = $(this).val();
            
            var aSelect = $(".fpsl");
            
            $.each(aSelect, function (i, ele) {
                           
                var aP = $(ele).find('option');
                
                aP.map( function () {
                    
                    if ($(this).val() == iVal) {
                        $(this).attr('selected', true);
                    }
                    
                });
            })
        });
    });
    
    //开电子发票
    $( function () {
        
       var oData = {};
       
       // 弹出
       $(".icon-pencil").on('click', function () {
          
            var oBox = $('#id_box');
            var _that = $(this);
            
            var oTr = $(this).parent('td').parent('tr');
            
            oData = {
                    
                order_id: oTr.find('td').eq(0).text(),
                type: oTr.find(':input[name="type"]').val(),
                fpsl: oTr.find('.fpsl').val(),
                address: oTr.find('input[name="xsf_dzdh"]').val()
            };
            
            if (oData.type == 1) {
                
                $(oBox).show('fast');
                
                // 禁止 href
                return false;
            } else {
                
                postData(oData);
                
            }
            
       });
       
       // 关闭
       $(".icon-close").on('click', function () {
           
           $('#id_box').hide();
       });
       
       $("#submit").on('click', function () {
           var v1 = $.trim($("input[name='v1']").val());
           var v2 = $.trim($("input[name='v2']").val());
           oData = {
               yfp_hm : v1,
               yfp_dm : v2
           };
           if (v1 && v2) {
               postData(oData);
           } else {
               alert('原发票号码、代码不能为空');
           }
           
       });
       
       //ajax
       function postData(data)
       {
           $.ajax({
               type: "POST",
               dataType: "JSON",
               url: '/soap/index',
               data: data
           }).done( function (data) {
               alert(data.msg);
               window.location = '/invoice/showlist';
               
           }).fail( function (a) {
               console.log(a + ' fail ');
           });
       }
       
    });
</script>