<div class="dux-tools">
    <div class="bread-head">电子发票<span class="small">sku列表</span>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form action="/invoice/skulist" method="POST" enctype="multipart/form-data" >
        <div class="form-inline">
            <div class="form-group">
                <div class="field">
                    <label><b>请选择设置税率:</b></label>
                    <select class="input js-assign" name="showcase" datatype="*" id="parent">
                        <option value=0.00>0.00</option>
                        <option value=0.06>0.06</option>
                        <option value=0.17>0.17</option>
                    </select>
                </div>
                <div class="form-button" style="margin-left: 10px;">
                    <button class="button bg-dot" type="button" id="selectAll">选中全部</button>
                    <button class="button bg-sub" type="button" id="unselectAll">取消全选</button>
                </div>
            </div>
            <div class="form-button" style="margin-left:20px;">
                <button class="button bg-gray set" type="submit">设置</button>
            </div>
        </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="*">选项</th>
                        <th width="*">订单号</th>
                        <th width="*">商品类型</th>
                        <th width="*">发票台头</th>
                        <th width="*">税率</th>
                        <th width="*">购买人手机号</th>
                    </tr>
                    <?php if ($data) : ?>
                        <?php foreach ($data['data'] as $val) : ?>
                            <tr>
                                <td><input type="checkbox" class="checkAll" value="<?=$val['id']?>"></td>
                                <td><?=$val['order_id']?></td>
                                <td><?=$val['project_name']?></td>
                                <td><?=$val['invoice_title']?></td>
                                <td><?=$val['tax_rate']?></td>
                                <td><?=$val['buyer_phone']?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
        Do.ready('base', function () {
            $('#table').duxTable();
        });
        
        //全选
       $('#selectAll').bind('click', function(){
           $('.checkAll').prop('checked', true);
           
       });
       
       //全选
       $('#unselectAll').bind('click', function(){
            $('.checkAll').prop('checked', false);
       });
       
       $('.set').on('click', function(){
           var orders = '';
           var fpsl = $('#parent option:selected').val();
            $(".checkAll").each(function(){
                if ($(this).prop("checked")) {
                    orders += $(this).val() + ","; 
                }
            });
            
            $.ajax({
                type: 'POST',
                dataType: 'JSON',
                url: '/invoice/updatesl',
                data: {orderlist:orders,sl:fpsl}
            }).done(function (data){
                alert(data.msg);
                window.location.reload();
            })
       })
    </script>
</div>