<div class="dux-tools">
    <div class="bread-head">用户管理<span class="small">添加用户</span>
        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/user/list">用户列表</a>
        </div>
    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/user/add">

        <div class="tab dux-tab">
            <div class="panel dux-box  active">

                <!-- tab head start-->
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>用户管理配置</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">添加用户</a></li>
                        </ul>
                    </div>
                </div>
                <!-- tab head end -->

                <!-- table body start-->
                 <div class="tab-body">

                    <!-- tab 1 start -->
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>登录帐号</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="code" name="code" size="60" datatype="*" placeholder="登录帐号">
                                <div class="input-note">请填写登录帐号</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>名字</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="name" name="name" size="60" datatype="*" value="" placeholder="名字">
                                <div class="input-note">请填写名字</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>电话</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="tel" name="tel" size="60" datatype="*" placeholder="电话">
                                <div class="input-note">请填写电话</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>微信号</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="wechat_name" name="wechat_name" size="60" datatype="*" placeholder="微信号">
                                <div class="input-note">请填写微信号</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>微信昵称</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="wechat_nickname" name="wechat_nickname" size="60" datatype="*" value="" placeholder="微信昵称">
                                <div class="input-note">请填写微信昵称</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="label">
                                <label>登录密码</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="password" name="password" size="60" datatype="/[\d|\w]{6}/" value="" placeholder="登录密码" errormsg="密码长度6位以上">
                                <button class="button bg-green" type="button" id="pass" style="width: 130px; height: 40px;">生成随机密码</button>
                                <div class="input-note">请填写登录密码</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="label">
                                <label>确定登录密码</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="confirm_password" name="confirm_password" size="60" datatype="*" value="" placeholder="确定登录密码" errormsg="两次密码不一致" recheck="password">
                                <div class="input-note">请填写确定登录密码</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="label">
                                <label>用户组</label>
                            </div>
                            <div class="field">
                                <select class="input js-assign" target="#tpl" name="group">
                                    <option value="0">请选择</option>
                                    <?php if ($groups) : ?>
                                        <?php foreach ($groups as $val) : ?>
                                            <option value="<?php echo $val['id']; ?>"><?php echo $val['name']; ?></option>
                                        <?php endforeach;?>
                                    <?php endif;?>
                                </select>
                                <div class="input-note">请选择用户组</div>
                            </div>
                        </div>
                    </div>
                    <!-- tab 1 end -->

                </div>
                <!-- table body end-->

                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>
<script  type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
    });
    
    //    //生成随机密码
    $(document).ready(function(){
        $('#pass').click(function(){
            var len = 7;
            var str = 'QWER34TY9U678456IOPAsdfSDFGH5JKLZXCVqwertyuioBNMpaghjklzxcvbnm120_';
            var maxPos = str.length;
            var pwd = '_1';
            for (i = 0; i <= len; i++){
                pwd += str.charAt(Math.floor(Math.random() * maxPos));
            }
            $("#password").val(pwd);
            $("#confirm_password").val(pwd);
        })
    })
</script>