<div class="dux-tools">
    <div class="bread-head">后台角色管理<span class="small">角色列表</span>

        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/group">
            用户角色列表</a>
        </div>

    </div>

</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/Group/add">
       <div class="tab dux-tab">
       <div class="panel dux-box  active">
        <div class="panel-head">
                    <div class="tab-head">
                        <strong>角色管理</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">添加角色</a></li>
                        </ul>
                    </div>
        </div>
        
        
        <div class="form-group">
            <div class="label">
                <label>用户角色</label>
            </div>
            <div class="field">
                <input type="text" class="input" style="width:220px;" id="code" name="code" size="60" datatype="*" placeholder="用户角色">
                <div class="input-note">请填用户角色</div>
            </div>
        </div>
        

        <div class="panel-foot">
            <div class="form-button">
                <div id="tips"></div>
                <button class="button bg-main" type="submit">保存</button>
                <button class="button bg" type="reset">重置</button>
            </div>
        </div>
           
           </div></div>
    </form>
</div>
<script  type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
    });
</script>