<div class="dux-tools">
    <div class="bread-head">用户角色管理                <span class="small">管理后台用户角色</span>
    </div>
    <br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <!--a class="button button-small bg-main icon-list" href="/admin.php?r=duxcms/AdminFormData/index&fieldset_id=1">
                内容列表</a-->
        </div>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a> 
            <ul class="drop-menu pull-right">
                <li><a href="/group/add">添加角色</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">编号</th>
                        <th width="150">角色</th>
                        <th width="200">导航</th>
                        <th width="*">菜单</th>
                        <th width="150">时间</th>
                        <th width="100">操作</th>
                    </tr>
                    <?php foreach($list as $v):?>
                    <tr>
                        <td><?=$v['id']?></td>
                        <td><?=$v['name']?>
                        </td>
                        <td><?=$v['nav']?>
                        </td>
                        <td style="word-wrap: break-word;word-break: break-word; "><?=$v['menu']?>
                        </td>
                        <td><?=$v['datetime']?>
                        </td>
                        <td>
                            <a class="button bg-blue button-small icon-pencil" href="/group/edit/id/<?=$v['id']?>" title="修改"></a>
                            <a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/group/delete" data="<?=$v['id']?>" title="删除"></a>
                        </td>
                    </tr>
                   <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>

</div>