<div class="dux-tools">
    <div class="bread-head">用户管理<span class="small">用户列表</span>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/user/add">添加用户</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">ID</th>
                        <th width="*">登录账号</th>
                        <th width="*">名字</th>
                        <th width="*">电话</th>
                        <th width="*">微信号</th>
                        <th width="*">微信昵称</th>
                        <th width="*">用户组</th>
                        <th width="*">状态</th>
                        <th width="100">操作</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                <td><?php echo $val['code']; ?></td>
                                <td><?php echo $val['name']; ?></td>
                                <td><?php echo $val['tel'] ? : '--'; ?></td>
                                <td><?php echo $val['wechat'] ? :'--'; ?></td>
                                <td><?php echo $val['wechat_nickname'] ? : '--'; ?></td>
                                <td><?php echo $val['gname']; ?></td>
                                <td><?php echo $val['status']; ?></td>
                                <td>
                                    <a class="button bg-blue button-small icon-pencil" href="/user/edit/id/<?php echo $val['id']; ?>" title="编辑"></a>
                                    <a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/user/delete" data='{"id":<?php echo $val['id']; ?>}' title="删除"></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>