<div class="dux-tools">
    <div class="bread-head">后台菜单管理                <span class="small">管理后台菜单</span>
    </div>
    <br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <!--a class="button button-small bg-main icon-list" href="/admin.php?r=duxcms/AdminFormData/index&fieldset_id=1">
                内容列表</a-->
        </div>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/nav/add">添加菜单</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">编号</th>
                        <th width="*">菜单名字</th>
                        <th width="*">菜单小图标</th>
                        <th width="*">控制器</th>
                        <th width="*">动作</th>
                        <th width="100">操作</th>
                    </tr>
                    <?php foreach($list as $v):?>
                    <tr>
                        <td><?=$v['id']?></td>
                        <td>
                            <?=$v['depthstr'] . ' ' . $v['name']?> <?php if($v['depth'] < 3):?><a href="/nav/add/id/<?=$v['id']?>" title="添加子分类" class=" icon-plus text-green"></a><?php endif;?>

                            <?php if ($v['depth'] == 2) : ?>
                                <select class="input js-assign" target="#tpl" datatype="*" style="display:inline-block; width: auto;" navid="<?php echo $v['id']; ?>">
                                    <option value="0">请选择标签</option>
                                    <?php if ($tags) : ?>
                                        <?php foreach ($tags as $value) : ?>
                                            <?php if ($value['tag_top_id'] == $v['cid']) : ?>
                                                <option value="<?php echo $value['tag_id']; ?>" <?php if ($value['tag_id'] ==  $v['tid']) : ?> selected <?php endif; ?>>
                                                    <?php echo $value['tag_name']; ?>
                                                </option>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            <?php endif; ?>
                        </td>
                        <td><?=$v['icon']?>
                        </td>
                        <td><?=$v['controller']?>
                        </td>
                        <td><?=$v['action']?>
                        </td>
                        <td>
                            <a class="button bg-blue button-small icon-edit" href="/nav/edit/id/<?=$v['id']?>" title="修改"></a>
                            <a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/nav/delete" data="<?=$v['id']?>" title="删除"></a>
                        </td>
                    </tr>
                   <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>

</div>
<script type="text/javascript">
    $( function () {

        $("select[navid!='']").on('change', function () {

            var request = $.ajax({
                url: '/nav/ajaxchangetag',
                type: 'POST',
                dataType: 'json',
                data: {id: $(this).attr('navid'), tid: $(this).val()}
            });

            request.done(function (data) {
                console.log('ok');
            });

            request.fail(function (jqXHR, textStatus) {
                console.log('fail: ' + textStatus);
            });
        });
    });
</script>