<script type="text/javascript" src="<?=ASSET_URL?>/admincenter/lib/editor/ueditor.config.js"></script>
<script type="text/javascript" src="<?=ASSET_URL?>/admincenter/lib/editor/ueditor.all.js"></script>
<link rel="stylesheet" type="text/css" href="<?=ASSET_URL?>/admincenter/lib/editor/themes/default/css/ueditor.css" meta="screen">
<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/admincenter/js/calendar/WdatePicker.js"></script>
<style>
    .link{cursor: pointer;color: blue;}
    .hidden{display:none;}
    .hand{cursor:pointer;}
</style>
<?php echo Asset::getResource('promot.css', 'admincenter/common');?>
<div class="dux-tools">
    <div class="bread-head">用户消费记录列表<span class="small"></span>
        
    </div>

</div>

<div class="dux-tools">
    <div> 
    <span><a href="/charge/uinfo/uid/<?=$uid?>" class="button button-small bg-main" >返回</a></span>   
    <span><a href="/charge/uchargelist/uid/<?=$uid?>/type/ANDROID" class="button button-small <?php echo ($type == 'ANDROID')?('bg-gray'):(' hand bg-main'); ?>  " >android充值记录</a></span>
    <span><a href="/charge/uchargelist/uid/<?=$uid?>/type/IOS" class="button button-small <?php echo ($type == 'IOS')?('bg-gray'):(' hand bg-main'); ?>" >ios充值记录</a></span>
    <span><a href="/charge/buylist/uid/<?=$uid?>" class="button button-small bg-gray" >用户消费记录</a></span>
                    
                    
        <?php if($coin>0): ?><span style="float:right;">消费总金额为：<?=$coin?></span><?php endif;?>
    </div>
</div>

<div class="admin-main">
    <div class="panel dux-box">
        
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>用户id</th>
                        <th>排期id</th>
                        <th>产品类型</th>
                        <th>电子书id</th>
                        <th>产品价格</th>
                        <th>时间</th>
                        <th>修改时间</th>
                        <th>支付状态</th>
                    </tr>
                    <?php if ($alist) { ?>
                        <?php foreach($alist as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                <td><?=$val['uid']; ?></td>
                                <td><?php echo $val['tid']; ?></td>
                                <td><?php echo ($val['type']== 1)?('电子书'):(($val['type']==2)?('单条音频'):('语音包')); ?></td>
                                <td><?php echo $val['book_id']>0?$val['book_id']:''; ?></td>
                                <td><?php echo $val['price']; ?></td>
                                <td><?php echo $val['ctime']; ?></td>
                                <td><?php echo $val['utime']; ?></td>
                                <td><?php echo ($val['pay_status']==1)?'<span class="tag bg-green">已支付</span>':'<span class="tag">未支付</span>'; ?></td>
                                
                            </tr>
                        <?php endforeach; ?>
                    <?php }else{ ?>
                             
                            <tr> <td></td> <td></td><td></td><td></td><td></td><td></td><td>没有记录</td><td></td><td></td><td></td><td></td><td></td></tr>
                            
                    <?php } ?>
                </tbody>
            </table>
        </div>
        
        <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
        <?=$pagger?>
        </div>
        <?php endif;?>



    </div>



<script>
//search
$('.searchbtn').click(function(){
    var kwd = $('#kwd').val();
    var url = $(this).attr('url');
    var sd = $('.startdate').val(),ed=$('.enddate').val();
    if(kwd == '' || kwd == null){
        kwd=0;
    }
    
    
    url = url+kwd;
    if(sd !='' && ed !=''){
        url+='/sd/'+sd+'/ed/'+ed;
    }
    
    window.location.href = url;
});

$('.upstatus').click(function(){
    var _this = $(this),txt=_this.attr('txt'),st=_this.attr('st'),_class=$('.upstatus'),fid=_this.attr('fid');
    var url='/charge/up/fid/'+fid+'/st/'+st;
    $.ajax({
              type: 'POST',
              url: url,
              data: {},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                  if(data.status == 1){
                     $('.statusname'+fid).text(txt);
                     
                     _this.addClass('hidden');
                     _this.siblings().removeClass('hidden');
                  }else{
                      alert('更新失败');
                  }

              },
              error:function(xhr,type){
                  alert('请求错误！');
              }
           });
    
});

</script>
</div>