<script type="text/javascript" src="<?=ASSET_URL?>/static/lib/editor/ueditor.config.js"></script>
<script type="text/javascript" src="<?=ASSET_URL?>/static/lib/editor/ueditor.all.js"></script>
<link rel="stylesheet" type="text/css" href="<?=ASSET_URL?>/static/lib/editor/themes/default/css/ueditor.css" meta="screen">
<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<style>
    .link{cursor: pointer;color: blue;}
    .hidden{display:none;};
</style>
<?php echo Asset::getResource('promot.css', 'static/common');?>
<div class="dux-tools">
    <div class="bread-head">用户充值记录列表<span class="small"></span>
        
    </div>

</div>

<div class="dux-tools">
    <div> 
        <input name="kwd" type="text" id="kwd" placeholder="输入用户id" value="<?=$kwd?>" />  
        <input value="<?=$startDate;?>" type="text" class=" datebtn startdate" style="width:220px;" id="datetime" name="startdate"   onfocus="WdatePicker({minDate:'2014-01-01'})" style="cursor:pointer;" size="60" datatype="*" placeholder="开始日期" autocomplete="off">
        <input value="<?=$endDate;?>" type="text" class=" datebtn enddate" style="width:220px;" id="enddatetime" name="enddate"   onfocus="WdatePicker({minDate:'2014-01-01'})" style="cursor:pointer;" size="60" datatype="*" placeholder="结束日期" autocomplete="off">
        <select name="type" id="device"><option value="" <?php echo (empty($type))?('selected'):(''); ?>>选择设备号</option><option value="ANDROID" <?php echo ($type=='ANDROID')?('selected'):(''); ?> >ANDROID</option><option value="IOS" <?php echo ($type=='IOS')?('selected'):(''); ?>>IOS</option></select>
        <select name="status" id="status"><option value="" <?php echo (!is_numeric($status))?('selected'):(''); ?>>全部</option><option value="1" <?php echo ($status==1)?('selected'):(''); ?> >充值成功</option><option value="0" <?php echo ((is_numeric($status)) && ($status==0))?('selected'):(''); ?>>充值失败</option></select>
        
        
        <a class="searchbtn button button-small bg-blue" url = "/charge/list/kwd/">搜索</a>
        <span style="float:right;">充值成功总金额为：<?=$coin?></span>
    </div>
</div>

<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>用户id</th>
                        <th>列表id</th>
                        <th>充值活动ID</th>
                        <th>充值交易号</th>
                        <th>用户设备号</th>
                        <th>时间</th>
                        <th>充值的节操币</th>
                        <th>赠送节操币</th>
                        <th>修改时间</th>
                        <th>交易状态</th>
                        <th>支付类型</th>
                    </tr>
                    <?php if ($alist) : ?>
                        <?php foreach($alist as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                <td><a class="bg-main button-small " href="/charge/uinfo/uid/<?=$val['uid']; ?>" ><?=$val['uid']; ?></a></td>
                                <td><?php echo $val['pid']; ?></td>
                                <td><?php echo $val['eid']; ?></td>
                                <td><?php echo $val['order']; ?></td>
                                <td><?php echo $val['device']; ?></td>
                                <td><?php echo $val['datetime']; ?></td>
                                <td><?php echo $val['coin']; ?></td>
                                <td><?php echo $val['gift']; ?></td>
                                <td><?php echo $val['uptime']; ?></td>
                                <td><?php echo ($val['status']==1)?'<span class="tag bg-green">充值完成</span>':'<span class="tag">未付款</span>'; ?></td>
                                <td><?php echo ($val['paytype']=='APPLEPAY')?('苹果支付'):(($val['paytype']=='WECHAT')?('微信支付'):(($val['paytype']=='ALIPAY')?('支付宝'):('赠送'))); ?></td>
                                

                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </tbody>
            </table>
        </div>
        
        <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
        <?=$pagger?>
        </div>
        <?php endif;?>



    </div>



<script>
//search
$('.searchbtn').click(function(){
    var kwd = $('#kwd').val();
    var url = $(this).attr('url');
    var sd = $('.startdate').val(),ed=$('.enddate').val();
    var device = $('#device').val(),status = $('#status').val();
    if(kwd == '' || kwd == null){
        kwd=0;
    }
    
    
    url = url+kwd;
    if(sd !='' && ed !=''){
        url+='/sd/'+sd+'/ed/'+ed;
    }
    
    if(device !='' && device !=null){
        url+='/type/'+device;
    }
    
    if(status !=''){
        url+='/st/'+status;
    }
    
    
    
    window.location.href = url;
});

$('.upstatus').click(function(){
    var _this = $(this),txt=_this.attr('txt'),st=_this.attr('st'),_class=$('.upstatus'),fid=_this.attr('fid');
    var url='/charge/up/fid/'+fid+'/st/'+st;
    $.ajax({
              type: 'POST',
              url: url,
              data: {},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                  if(data.status == 1){
                     $('.statusname'+fid).text(txt);
                     
                     _this.addClass('hidden');
                     _this.siblings().removeClass('hidden');
                  }else{
                      alert('更新失败');
                  }

              },
              error:function(xhr,type){
                  alert('请求错误！');
              }
           });
    
});

</script>
</div>