<div class="dux-tools">
    <div class="bread-head">店铺管理<span class="small">店铺审核</span>
        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/store/showcase">店铺列表</a>
        </div>
    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/store/showcase/edit">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>店铺管理</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="Javascript:void();">店铺审核</a></li>
                        </ul>
                    </div>
                </div>
                 <div class="tab-body">
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>用户ID</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="user_id" name="user_id" size="60" value="<?php echo $info['user_id']; ?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>企业名称</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="com_name" name="com_name" size="60" value="<?php echo $info['com_name']; ?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>公司注册地址</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="com_register_address" name="com_register_address" size="60" value="<?php echo $info['com_register_address']; ?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>企业类型</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="com_type" name="com_type" size="60" value="<?php echo $info['com_type']; ?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>组织机构代码</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="com_number" name="com_number" size="60"  value="<?php echo $info['com_number']; ?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>工商执照注册号</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="com_reg_num" name="com_reg_num" size="60" value="<?php echo $info['com_reg_num']; ?>"readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>一般经营范围</label>
                            </div>
                            <div class="field">
                                <textarea class="input" style="width:220px;height: 150px;" id="com_scope" name="com_scope" size="60" readonly><?php echo $info['com_scope']; ?></textarea>
                                <div class="input-note">请填写商品介绍</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>前置许可经营范围</label>
                            </div>
                            <div class="field">
                                <textarea class="input" style="width:220px;height: 150px;" id="com_scope_pro" name="com_scope_pro" size="60" readonly><?php echo $info['com_scope_pro']; ?></textarea>
                                <div class="input-note">请填写商品介绍</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>有效期</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="com_expire" name="com_expire" size="60"  value="<?php echo $info['com_expire']; ?>"readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>营业执照照片</label>
                            </div>
                            <div class="field">
                                <p><img src="<?php echo $info['com_id_pic1']; ?>" width="600px"></p>
                                <p><img src="<?php echo $info['com_id_pic2']; ?>" width="600px"></p>
                                <p><img src="<?php echo $info['com_id_pic3']; ?>" width="600px"></p>
                                <p><img src="<?php echo $info['com_id_pic4']; ?>" width="600px"></p>
                                <p><img src="<?php echo $info['com_id_pic5']; ?>" width="600px"></p>
                                <p><img src="<?php echo $info['com_id_pic6']; ?>" width="600px"></p>
                                <?php if(is_array($info['com_id_pic7'])):?>
                                    <?php foreach($info['com_id_pic7'] as $val) :?>
                                    <p><img src="<?php echo $val['img']; ?>" width="600px"></p>
                                    <?php endforeach;?>
                                <?php else:?>
                                <p><img src="<?php echo $info['com_id_pic7']; ?>" width="600px"></p>
                                <?php endif;?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-foot">
                    <div class="form-button">
                        <?php if ($info['status_com'] == 1) : ?>
                        <a href="javascript:;" url="/store/showcase/unpass" data='{"id":"<?=$showcase_id?>"}' title="驳回" class="button bg js-open">驳回</a>
                        <a href="javascript:;" url="/store/showcase/pass" data='{"id":"<?=$showcase_id?>"}' title="通过认证" class="button bg-main js-action">通过认证</a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script  type="text/javascript">
    var showcaseTitle = '驳回认证申请';
    var showcaseContent = <?=$refuse?>;
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxTable();
    });
</script>