<div class="dux-tools">
    <div class="bread-head">测试号管理<span class="small">测试号列表</span>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/test/" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="openid" size="20" value="<?=$openid?>" placeholder="openid">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="kw" size="20" value="<?=$nickname?>" placeholder="用户昵称">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">ID</th>
                        <th width="*">手机号</th>
                        <th width="*">昵称</th>
                        <th width="*">OPENID</th>
                        <th width="*">注册来源</th>
                        <th width="*">注册时间</th>
                        <th width="*">操作</th>
                    </tr>
                    <?php if ($data) : ?>
                        <?php foreach($data as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                <td><?php echo $val['phone']; ?></td>
                                <td><?php echo $val['nickname']; ?></td>
                                <td><?php echo $val['openid']; ?></td>
                                <td><?php echo $val['source']; ?></td>
                                <td><?php echo $val['regtime']; ?></td>
                                <td><a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/Tag/delete" data='{"id":<?php echo $val['tag_id']; ?>}' title="删除"></a></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
Do.ready('base', function () {
$('#table').duxTable();
});
</script>