<div class="dux-tools">
    <div class="bread-head">测试号管理<span class="small">测试号列表</span>
    </div>
    <br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-blue icon-list" href="/test/index">openid</a>
            <a class="button button-small bg-gray icon-list" href="/test/mobile">手机号</a>
        </div>
    </div> 
</div>

<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">UID</th>
                        <th width="*">昵称</th>
                        <th width="*">手机号</th>
                        <th width="*">注册来源</th>
                        <th width="*">注册时间</th>
                        <th width="*">操作</th>
                    </tr>
                    <?php if ($data) : ?>
                        <?php foreach($data as $val) : ?>
                            <tr>
                                <td><?php echo $val['u_id']; ?></td>
                                <td><?php echo $val['u_nickname']; ?></td>
                                <td><?php echo $val['u_phone']; ?></td>
                                <td><?php echo $val['u_source']; ?></td>
                                <td><?php echo $val['u_regtime']; ?></td>
                                <td><a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/test/delete" data='{"uid":"<?php echo $val['u_id'];?>","mobile":"<?php echo $val['u_phone'];?>"}' title="删除"></a></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
Do.ready('base', function () {
$('#table').duxTable();
});
</script>