<div class="dux-tools clearfix">
    <div class="bread-head">生活作风<span class="small">sku列表</span></div>
    <div class="button-group float-right">
        <a class="button button-small bg-dot icon-plus dropdown-toggle"> 录入 <span class="downward"></span></a>
        <ul class="drop-menu pull-right">
            <li><a href="/shzf/inv/addsku">录入SKU信息</a></li>
        </ul>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <div class="form-inline">
            <label><b>上传需要开票SKU编码:</b></label>
            <div class="form-button">
                <input type="text" class="input show_uo_imgs" id="files" name="file" placeholder="开票SKU编码上传" readonly=""/>
                <a class="button bg-blue button-small " data="files" id="image_upload3" preview="image_preview3" href="javascript:;"><span class="icon-upload">上传</span></a>
            </div>
        </div>
    </div>
    <div class="float-left">
        <form action="/Shzf/inv/skulist" method="GET" >
            <div class="form-inline">
                <div class="form-group" style="margin-left:10px;">
                    <label><b>请输入搜索条件:</b></label>
                    <div class="field" style="margin-left: 5px;">
                        <input type="text" class="input" name="sku_id" size="20" value="<?=$info['sku_id']?>" placeholder="填写sku编码">
                    </div>
                    <div class="field" style="margin-left: 5px;">
                        <input type="text" class="input" name="sku_name" size="20" value="<?=$info['sku_name']?>" placeholder="商品名">
                    </div>
                </div>
                <div class="form-button" style="margin-left:20px;">
                    <button class="button bg-main" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
    <div class="float-left" style="margin-left: 10px;">
        <div class="form-inline">
            <div class="form-group">
                <div class="field">
                    <label><b>请选择设置税率:</b></label>
                    <select class="input js-assign" name="showcase" datatype="*" id="parent">
                        <option value=0.00>0.00</option>
                        <option value=0.06>0.06</option>
                        <option value=0.17>0.17</option>
                    </select>
                </div>
                <div class="form-button" style="margin-left: 10px;">
                    <button class="button bg-dot" type="button" id="selectAll">选中全部</button>
                    <button class="button bg-sub" type="button" id="unselectAll">取消全选</button>
                </div>
            </div>
            <div class="form-button" style="margin-left:20px;">
                <button class="button bg-gray set">设置</button>
            </div>
        </div>
    </div>
</div>
<div oncancel="" class="skvdiv" style="display: none">
    <table class="table">
        <caption>上传失败的sku编码</caption>
        <tbody class="skuval">
        </tbody>
    </table>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="*">选项</th>
                        <th width="*">sku编号</th>
                        <th width="*">商品类型</th>
                        <th width="*">税率</th>
                        <th width="*">操作</th>
                    </tr>
                    <?php if ($data) : ?>
                        <?php foreach ($data['list'] as $val) : ?>
                            <tr>
                                <td><input type="checkbox" class="checkAll" value="<?=$val['id']?>"></td>
                                <td><?=$val['sku_id']?></td>
                                <td><?=$val['product_name']?></td>
                                <td><?=$val['tax_tare']?></td>
                                <td>
                                    <button class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/Shzf/inv/delsku" data='{"id":<?php echo $val['id']; ?>}' title="删除"></button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
    Do.ready('base', function () {
        $('#form').duxForm();
        $('#image_upload3').duxFileUpload({
            uploadUrl: '/Shzf/Upload/uSku',
            type: 'xls',
            complete: function (data) {
                if (data) {
                    alert('上传成功,个别失败');
                    $('.skvdiv').css('display','block');
                    $('.skuval').append(data);
                } else {
                    alert('上传成功');
                }
            }
        });
    });

    //全选
   $('#selectAll').bind('click', function(){
       $('.checkAll').prop('checked', true);

   });

   //全选
   $('#unselectAll').bind('click', function(){
        $('.checkAll').prop('checked', false);
   });

   $('.set').on('click', function(){
       var orders = '';
       var fpsl = $('#parent option:selected').val();
        $(".checkAll").each(function(){
            if ($(this).prop("checked")) {
                orders += $(this).val() + ",";
            }
        });

        $.ajax({
            type: 'POST',
            dataType: 'JSON',
            url: '/Shzf/inv/tax',
            data: {orderlist:orders,sl:fpsl}
        }).done(function (data){
            alert(data.msg);
            window.location.reload();
        })
   })
</script>