<div class="dux-tools">
    <div class="bread-head">电子发票<span class="small">修改发票信息</span>
        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/invoice/inv/list">发票列表</a>
        </div>
    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/invoice/inv/edit">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="tab-body">
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>手机号</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" name="buyer_phone" placeholder="手机号" value="<?php echo $data['buyer_phone']; ?>">
                                <div class="input-note">请填写手机号</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>发票台头</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" name="title" value="<?php echo $data['title']; ?>" placeholder="发票台头">
                                <div class="input-note">发票台头</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>订单号</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;"  name="order_id" value="<?php echo $data['order_id']; ?>" placeholder="订单号">
                                <div class="input-note">请填写订单号</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>购买人税号税号:</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" name="buyer_tax_id" value="<?=$data['buyer_tax_id']?>" >
                                <div class="input-note">购买人税号税号</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-foot">
                    <div class="form-button">
                        <input type="hidden" name="i_id" value="<?=$data['id']?>">
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
    });
</script>