<div class="admin-main">
    <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
        <input type="text" class="input pull-left" style="width:220px;" id="search_title" name="search_title" size="60" placeholder="输入标题搜索">
        <button class="button bg-main search" type="button">搜索</button>
    </div>
    <div class="panel dux-box">

        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                <tr>
                    <th width="100">ID</th>
                    <th width="*">电子书运营标题</th>
                    <th width="*">作者</th>
                    <th width="*">类型</th>
                    <th width="*">字数</th>
                    <th width="*">销量</th>
                    <th width="*">定价</th>
                    <th width="*">状态</th>
                    <th width="*">操作</th>
                </tr>
                <?php if ($list) : ?>
                    <?php foreach($list as $val) : ?>
                        <tr>
                            <td><?php echo $val['id']; ?></td>
                            <td class="prve_img_<?php echo $val['id']; ?>"><a class="previmg"><?php echo $val['operating_title']; ?></a><img src="<?=$val['cover']?>" style="display: none" title="<?php echo $val['operating_title']; ?>"></td>
                            <td><?php echo $val['author']; ?></td>
                            <td><?php echo $val['type']== 2?'干货':'全文'; ?></td>
                            <td><?php echo $val['count']; ?></td>
                            <td><?php echo $val['sell_count']; ?></td>
                            <td><?php echo $val['price']; ?></td>
                            <td>
                                <?php if ($val['status'] == 1) : ?>
                                    <span class="tag bg-green">上架</span>
                                <?php elseif($val['status'] == 2) : ?>
                                    <span class="tag">库存</span>
                                <?php endif; ?>
                            </td>
                            <td>
                                <a class="button bg-green button-small icon-plus" value="<?php echo $val['id']; ?>" title="编辑"></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>

                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
            <a class="button bg-main button-small pull-right okBtn">好了</a>
        </div>
    <?php endif;?>
</div>