<div class="dux-tools">
    <div class="bread-head">电子书列表管理<span class="small">电子书列表</span>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/book/add">添加电子书</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="dux-tools">
    <div> <input name="kwd" type="text" id="kwd" placeholder="输入关键字" value="<?=$kwd?>" />  <a class="searchbtn button button-small bg-blue" url = "/book/list/kwd/">搜索</a></div>
</div>

<div class="admin-main">
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <div class="panel dux-box">

        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">ID</th>
                        <th width="*">电子书运营标题</th>
                        <th width="*">作者</th>
                        <th width="*">类型</th>
                        <th width="*">封面</th>
                        <th width="*">字数</th>
                        <th width="*">销量</th>
                        <th width="*">定价</th>
                        <th width="*">状态</th>
                        <th width="*">操作</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                <td><?php echo $val['operating_title']; ?></td>
                                <td><?php echo $val['author']; ?></td>
                                <td><?php echo $val['type']== 2?'干货':'全文'; ?></td>
                                <td><img src="<?php echo $val['cover']; ?>" height="100" /></td>
                                <td><?php echo $val['count']; ?></td>
                                <td><?php echo $val['sell_count']; ?></td>
                                <td><?php echo $val['price']; ?></td>
                                <td>
                                    <?php if ($val['status'] == 1) : ?>
                                        <span class="tag bg-green">上架</span>
                                    <?php elseif($val['status'] == 2) : ?>
                                        <span class="tag">库存</span>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <a class="button bg-blue button-small icon-pencil" href="/book/edit/id/<?php echo $val['id']; ?>" title="编辑"></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
Do.ready('base', function () {
$('#table').duxTable();
});


//search

$('.searchbtn').click(function(){
    var kwd = $('#kwd').val();
    var url = $(this).attr('url');
    url = url+kwd;
    window.location.href = url;
});
</script>