<div class="dux-tools">
    <div class="bread-head">用户反馈<span class="small">想看的电子书</span>

        <span class="small">
            <a href="/bookopinion/index/sort/desc" class="bread-head button  bg-main ">按反馈时间倒序</a>
        </span>
    </div>
</div>

<div class="admin-main">
    <?php if ($pagger): ?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
            <?= $pagger ?>
        </div>
    <?php endif; ?>
    <div class="panel dux-box">

        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                <tr>
                    <th width="*">来源金句</th>
                    <th width="*">用户id</th>
                    <th width="*">反馈时间</th>
                </tr>
                <?php if ($list) : ?>
                    <?php foreach ($list as $val) : ?>
                        <tr>
                            <td><a href="/verse/index/id/<?php echo $val['from_verse_id']; ?>"><?php echo $val['verse_source']; ?></a></td>
                            <td><?php echo $val['user_id']; ?></td>
                            <td><?php echo $val['create_date_time']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>

                </tbody>
            </table>
        </div>
    </div>
    <?php if ($pagger): ?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?= $pagger ?>
        </div>
    <?php endif; ?>
</div>