<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<!-- ECharts单文件引入 -->
<script src="<?=ASSET_URL?>/static/lib/js/chart/echarts-all.js"></script>
<div class="dux-tools">
    <div class="bread-head">数据统计<span class="small">订单数据统计</span></div><br>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/sdata/order" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        开始时间：<input type="text" id="d4321" class="input datebtn" style="width:220px;" id="datetime" name="start_time" value="<?=$start_time?>" onfocus="WdatePicker({startDate:'<?=date('Y-m-d',strtotime('-7 day'))?>',maxDate:'#F{$dp.$D(\'d4322\',{d:-1})}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="" autocomplete="off">
                    </div>
                    <div class="field">
                        结束时间：<input type="text" id="d4322" class="input datebtn" style="width:220px;" id="datetime" name="end_time"  value="<?=$end_time?>" onfocus="WdatePicker({startDate:'<?=date('Y-m-d',strtotime('today'))?>',maxDate:'<?=date('Y-m-d',strtotime('today'));?>',minDate:'#F{$dp.$D(\'d4321\',{d:+1})}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="" autocomplete="off">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="showcase_id" size="20" value="<?=$showcase_id?>" placeholder="请输入店铺ID">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
                <div class="form-button">
                    <button class="button" type="submit" name="excel" id="excel" value="1">导出</button>
                </div>
            </div>
        </form>
    </div>
</div>


<div class="admin-main">
    
        <div class="line-big">
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-red  icon-user"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=$order_people?></strong></h2>
                            下单人数
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-blue icon-key"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=$paied_people?></strong></h2>
                            付款人数
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-green icon-file-text-o"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=$paied_num?></strong></h2>
                            付款笔数
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-yellow icon-comments"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong>0</strong></h2>
                            商品销量
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-yellow icon-comments"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=$paied_sum?></strong></h2>
                            付款金额
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-yellow icon-comments"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=$paied_people_sum?></strong></h2>
                            客单价
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
    </div>
    
    <div class="panel dux-box">
        <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
        <div id="main" style="height:400px"></div>
    </div>
    <div class="line-big">
        <div class="xm6">
            <div class="panel dux-box">
                <div id="pie1" style="height:400px"></div>
            </div>
        </div>
        <div  class="xm6">
            <div class="panel dux-box">
                <div id="pie2" style="height:400px"></div>
            </div>
        </div>
    </div>
<script type="text/javascript" charset="utf-8">
    Do.ready('base',function() {
        $('.js-time').duxTime();
    });
</script>
<script type="text/javascript">
    // 基于准备好的dom，初始化echarts图表
    var myChart = echarts.init(document.getElementById('main'), 'macarons'); 
    var option = {
        tooltip : {
            trigger: 'axis'
        },
        legend: {
            data:['下单笔数','付款笔数','付款金额']
        },
        toolbox: {
            show : true,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        calculable : true,
        xAxis : [
            {
                type : 'category',
                boundaryGap : false,
                data : [<?=$dates?>]
            }
        ],
        yAxis : [
            {
                type : 'value',
                axisLabel : {
                    formatter: '{value} °C'
                }
            }
        ],
        series : [
            {
                name:'下单笔数',
                type:'line',
                data:[<?=$order_num_string?>],
            },
            {
                name:'付款笔数',
                type:'line',
                data:[<?=$paied_num_string?>],
            },
            {
                name:'付款金额',
                type:'line',
                data:[<?=$paied_sum_string?>],
            }
        ]
    };

    // 为echarts对象加载数据 
    myChart.setOption(option); 
</script>
<script type="text/javascript">
    // 图表实例化------------------
// srcipt标签式引入
var myChart = echarts.init(document.getElementById('pie1'));

// 过渡---------------------
myChart.showLoading({
    text: '正在努力的读取数据中...',    //loading话术
});

// ajax getting data...............

// ajax callback
myChart.hideLoading();

// 图表使用-------------------
option = {
    title : {
        text: '支付方式统计',
        subtext: '订单数量',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient : 'vertical',
        x : 'left',
        data:['WECHAT','JDPAY']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {
                show: true, 
                type: ['pie', 'funnel'],
                option: {
                    funnel: {
                        x: '25%',
                        width: '60%',
                        funnelAlign: 'left',
                        max: 1548
                    }
                }
            },
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    series : [
        {
            name:'支付方式',
            type:'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[
                {value:335, name:'WECHAT'},
                {value:310, name:'JDPAY'},
            ]
        }
    ]
};
                    
myChart.setOption(option);
</script>
<script type="text/javascript">
    // 图表实例化------------------
// srcipt标签式引入
var myChart = echarts.init(document.getElementById('pie2'));

// 过渡---------------------
myChart.showLoading({
    text: '正在努力的读取数据中...',    //loading话术
});

// ajax getting data...............

// ajax callback
myChart.hideLoading();

// 图表使用-------------------
option = {
    title : {
        text: '支付方式统计',
        subtext: '支付金额',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient : 'vertical',
        x : 'left',
        data:['WECHAT','JDPAY']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {
                show: true, 
                type: ['pie', 'funnel'],
                option: {
                    funnel: {
                        x: '25%',
                        width: '60%',
                        funnelAlign: 'left',
                        max: 1548
                    }
                }
            },
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    series : [
        {
            name:'支付方式',
            type:'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[
                {value:335, name:'WECHAT'},
                {value:310, name:'JDPAY'},
            ]
        }
    ]
};
                    
myChart.setOption(option);
</script>
</div>