<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<!-- ECharts单文件引入 -->
<script src="<?=ASSET_URL?>/static/lib/js/chart/echarts-all.js"></script>
<div class="dux-tools">
    <div class="bread-head">页面流量<span class="small">网站访问数据统计</span></div>
    <br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main icon-list" href="pagedata"> 页面转化数据</a>
            <a class="button button-small bg-back icon-list" href="pvperday"> 按每天流量分析</a>
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET">
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        开始时间：<input type="text" id="d4321" class="input datebtn" style="width:220px;" id="datetime" name="start_time" value="<?=$start_time?>" onfocus="WdatePicker({startDate:'<?=date('Y-m-d',strtotime('-7 day'))?>',maxDate:'#F{$dp.$D(\'d4322\',{d:+0})}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="" autocomplete="off">
                    </div>&nbsp;
                    <div class="field">
                        结束时间：<input type="text" id="d4322" class="input datebtn" style="width:220px;" id="datetime" name="end_time"  value="<?=$end_time?>" onfocus="WdatePicker({maxDate:'<?=date('Y-m-d',strtotime('-1 day'))?>',minDate:'#F{$dp.$D(\'d4321\',{d:+0})}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="" autocomplete="off">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="showcase_id" size="20" value="<?=$showcase_id?>" placeholder="请输入店铺ID">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">筛选</button>
                </div>
            </div>
        </form>
    </div>
</div>


<div class="admin-main">
    <div class="line-big">
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-red  icon-user"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=$overview['total_uv']?></strong></h2>
                            浏览UV
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-blue icon-key"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=$overview['total_pv']?></strong></h2>
                            浏览PV
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-green icon-share"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=$overview['share_pv']?></strong></h2>
                            外部分享
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-yellow icon-link"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong>0</strong></h2>
                            导出PV
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-yellow icon-time"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=number_format($overview['avg_stay'], 2)?></strong></h2>
                            平均停留时间
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm2">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-yellow icon-sitemap"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2 style="color: #c3c3c3;"><?=暂无?></h2>
                            平均访问深度
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
    </div>

<!--    <div class="line-big">-->
<!--        <div class="xm6">-->
<!--            <div class="panel dux-box">-->
<!--                <div class="panel-head">页面类型</div>-->
<!--                <div id="pagetype" style="height:400px"></div>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div  class="xm6">-->
<!--            <div class="panel dux-box">-->
<!--                <div class="panel-head">访问来源</div>-->
<!--                <div id="pagefrom" style="height:400px"></div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    <br>-->
    <div class="panel dux-box">
        <div class="panel-head">数据趋势</div>
        <br>
        <div class="line-big">
            <div class="xm5">
                <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
                <div id="main" style="height:400px"></div>
            </div>
            <div  class="xm7">
                <table id="table" class="table table-bordered">
                    <tbody>
                        <tr>
                            <th width="50">排名</th>
                            <th width="*">页面名称</th>
                        </tr>
                        <?php foreach ($top10 as $key => $item) : ?>
                            <tr>
                                <td align="center"><?=$key+1?></td>
                                <td><a><?=$item['page_id']?></a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br>
    <div class="panel dux-box">
        <div class="panel-head">详细数据</div>
        <table id="table" class="table table-bordered">
            <tbody>
                <tr>
                    <th width="500">页面名称</th>
                    <th width="*">浏览UV/PV</th>
                    <th width="*">外部分享UV/PV</th>
                    <th width="*">平均停留时间</th>
                    <th width="*">平均访问深度</th>
                </tr>
                <?php foreach ($top10 as $key => $item) : ?>
                    <tr>
                        <td><a><?=$item['page_id']?></a></td>
                        <td><?=$item['total_uv']?> / <?=$item['total_pv']?></td>
                        <td><?=$item['share_uv']?> / <?=$item['share_pv']?></td>
                        <td><?=$item['avg_stay']?></td>
                        <td>暂无</td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
    <script type="text/javascript" charset="utf-8">
        Do.ready('base',function() {
            $('.js-time').duxTime();
        });
    </script>
<!--    <script>-->
<!--        var pagetypeChart = echarts.init(document.getElementById('pagetype'));-->
<!--        option = {-->
<!--            tooltip : {-->
<!--                trigger: 'item',-->
<!--                formatter: "{b} <br/> {a} : {c} <br/> 占比 : {d}%"-->
<!--            },-->
<!--            legend: {-->
<!--                orient : 'vertical',-->
<!--                x : 'left',-->
<!--                data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']-->
<!--            },-->
<!--            calculable : true,-->
<!--            series : [-->
<!--                {-->
<!--                    name:'浏览PV',-->
<!--                    type:'pie',-->
<!--                    radius : ['30%', '60%'],-->
<!--                    itemStyle : {-->
<!--                        normal : {-->
<!--                            label : {-->
<!--                                show : false-->
<!--                            },-->
<!--                            labelLine : {-->
<!--                                show : false-->
<!--                            }-->
<!--                        }-->
<!--                    },-->
<!--                    data:[-->
<!--                        {value:335, name:'直接访问'},-->
<!--                        {value:310, name:'邮件营销'},-->
<!--                        {value:234, name:'联盟广告'},-->
<!--                        {value:135, name:'视频广告'},-->
<!--                        {value:1548, name:'搜索引擎'}-->
<!--                    ]-->
<!--                }-->
<!--            ]-->
<!--        };-->
<!--        pagetypeChart.setOption(option);-->
<!--    </script>-->
<!--    <script>-->
<!--        var pagefromChart = echarts.init(document.getElementById('pagefrom'));-->
<!--        option = {-->
<!--            tooltip : {-->
<!--                trigger: 'item',-->
<!--                formatter: "{b} <br/> {a} : {c} <br/> 占比 : {d}%"-->
<!--            },-->
<!--            legend: {-->
<!--                orient : 'vertical',-->
<!--                x : 'left',-->
<!--                data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']-->
<!--            },-->
<!--            calculable : true,-->
<!--            series : [-->
<!--                {-->
<!--                    name:'浏览PV',-->
<!--                    type:'pie',-->
<!--                    radius : ['30%', '60%'],-->
<!--                    itemStyle : {-->
<!--                        normal : {-->
<!--                            label : {-->
<!--                                show : false-->
<!--                            },-->
<!--                            labelLine : {-->
<!--                                show : false-->
<!--                            }-->
<!--                        }-->
<!--                    },-->
<!--                    data:[-->
<!--                        {value:335, name:'直接访问'},-->
<!--                        {value:310, name:'邮件营销'},-->
<!--                        {value:234, name:'联盟广告'},-->
<!--                        {value:135, name:'视频广告'},-->
<!--                        {value:1548, name:'搜索引擎'}-->
<!--                    ]-->
<!--                }-->
<!--            ]-->
<!--        };-->
<!--        pagefromChart.setOption(option);-->
<!--    </script>-->
    <script>
        // srcipt标签式引入
        var myChart = echarts.init(document.getElementById('main'));
        option = {
            tooltip : {
                trigger: 'axis'
            },
            legend: {
                data:['浏览PV']
            },
            calculable : true,
            xAxis : [
                {
                    type : 'category',
                    data : ['NO.1','NO.2','NO.3','NO.4','NO.5','NO.6','NO.7','NO.8','NO.9','NO.10']
                }
            ],
            yAxis : [
                {
                    type : 'value'
                }
            ],
            series : [
                {
                    name:'浏览PV',
                    type:'bar',
                    data:[<?=implode(',', $toppv)?>],
                    markPoint : {
                        data : [
                            {type : 'max', name: '最大值'},
                            {type : 'min', name: '最小值'}
                        ]
                    },
                    markLine : {
                        data : [
                            {type : 'average', name: '平均值'}
                        ]
                    }
                }
            ]
        };
        myChart.setOption(option);
    </script>
</div>