<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>

<div class="dux-tools">
    <div class="bread-head">后台用户管理<span class="small">后台添加音频活动</span>

        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/audio/list">
            音频列表</a>
        </div>

    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/campaign/add" enctype="multipart/form-data">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>音频管理</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">添加活动</a></li>
                            
                        </ul>
                    </div>
                </div>
                <div class="tab-body">
                    <div class="tab-panel active" id="tab-1">
                        
                        
                        <div class="form-group">
                            <div class="label">
                                <label>活动名称</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="campaign_title" name="campaign_title" size="60" datatype="*1-100" errormsg="最多100个字符" value="" placeholder="活动名称">*
                                <div class="input-note">请填写活动名称, 最多100个字符</div>
                            </div>
                        </div>
                        
                        
                        <div class="form-group">
                            <div class="label">
                                <label>活动开始时间</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input datebtn" style="width:220px;" id="start_date" name="start_date" onfocus="WdatePicker({minDate:'2015-10-01'})" style="cursor:pointer;" size="60" datatype="*" placeholder="活动开始时间" autocomplete="off">*
                                <div class="input-note">请填写活动名称, 最多100个字符</div>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="label">
                                <label>活动结束时间</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input datebtn" style="width:220px;" id="end_date" name="end_date" onfocus="WdatePicker({minDate:'2015-10-01'})" style="cursor:pointer;" size="60" datatype="*" placeholder="活动结束时间" autocomplete="off">*
                                <div class="input-note">请填写活动名称, 最多100个字符</div>
                            </div>
                        </div>
                        
                        

                        

                        <div class="form-group">
                            <div class="label">
                                <label>活动类型</label>
                            </div>
                            <div class="field">
                                <select  class="input" name="campaign_type" id="campaign_type">
                                    <option value="" selected>请选择活动类型 </option>
                                    <option value="1">返还会员节操币</option>
                                    <option value="2">充值赠送节操币</option>
                                    
                                </select>*
                            </div>
                        </div>
                        
                        <div class="form-group" id="campaignInfo">
                                
                        </div>  
                        
                        <div class="form-group">
                            <div class="label">
                                <label>用户级别要求</label>
                            </div>
                            <div class="field">
                               <select  class="input" name="vip_user" id="vip_user">
                                   <option value="" >请选择 </option>
                                   <option value="1" >必须是会员</option>
                                    <option value="2">不限</option>
                                    
                                </select>*
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="label">
                                <label>是否重复赠送节操币</label>
                            </div>
                            <div class="field">
                                <select class="input" name="is_repeat" id="is_repeat">
                                    <option value="">请选择</option>
                                    <option value="1">不重复赠送</option>
                                    <option value="2">重复赠送</option>
                                </select>
                            </div>
                        </div>

                        
                        
                        <div class="form-group">
                            <div class="label">
                                <label>活动状态</label>
                            </div>
                            <div class="field">
                                <select class="input" name="campaign_status" id="campaign_status">
                                    <option value="">请选择</option>
                                    <option value="1" selected>启用 </option>
                                    <option value="2">停用</option>
                                </select>
                            </div>
                        </div>
                        
                        

                        
                    </div>


                   
                </div>
                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>



<div id="vip_info_box" style="display:none;">
    <?php if($vipTypeList){ foreach($vipTypeList as $v){ ?>
    <div class="form-group">
        <div class="label">
            <label><?=$v?>元会员返还节操币</label>
        </div>

        <div class="field">
            <input class="input" name="user_level_<?=$v?>" id="user_level_<?=$v?>" value="<?=$v?>">
        </div>
    </div>
    <?php }  } ?>
</div>

<div id="fill_coin_box" style="display:none;">
     <?php if($fillList){ foreach($fillList as $v){ ?>
    <div class="form-group">
        <div class="label">
            <label>充值<?=$v?>元赠送节操币</label>
        </div>

        <div class="field">
            <input class="input" name="recharge_coin_<?=$v?>" id="recharge_coin_<?=$v?>">
        </div>
    </div>
    <?php }  } ?>
</div>


<script  type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
        
    });
</script>

<script type="text/javascript">


$(function(){
	$('#campaign_type').change(function(){
            var ctype = $(this).val();
            var ulevel = $('#vip_info_box').html();
            var fillcoin = $('#fill_coin_box').html();
            
            if(ctype == ''){
                $('#campaignInfo').html('');
                
            }else if(ctype == 1){
                $('#campaignInfo').html(ulevel);
                
                $('#vip_user')[0].selectedIndex = 1;
                $('#is_repeat')[0].selectedIndex = 1;
            }else if(ctype == 2){
                $('#campaignInfo').html(fillcoin);
               
                $('#vip_user')[0].selectedIndex = 2;
                $('#is_repeat')[0].selectedIndex = 2;
            }
            
        });
        
});

   
</script>