<script type="text/javascript" src="<?=ASSET_URL?>/static/lib/editor/ueditor.config.js"></script>
<script type="text/javascript" src="<?=ASSET_URL?>/static/lib/editor/ueditor.all.js"></script>
<link rel="stylesheet" type="text/css" href="<?=ASSET_URL?>/static/lib/editor/themes/default/css/ueditor.css" meta="screen">
<?php echo Asset::getResource('promot.css', 'static/common');?>
<style>
    .sugList{
        height: auto; 
        display: block;
        background: #fff none repeat scroll 0 0;
        border:1px solid #ccc;
        box-shadow: 1px 1px 3px #ededed;
        position: absolute;
        width: 170px;
        z-index:99;
        width:200px;
        max-height:200px;
        overflow-x:auto;
        overflow-y:auto;
    }
    .sugList ul{
        list-style: outside none none;
        margin: 0;
        padding: 0;
    }
    .sugList ul li{
        color: #000;
        cursor: default;
        font: 14px/25px arial;
        padding: 0 8px;
        position: relative;
        width: 170px;
    }
    .tags_input{
        margin-right: 5px;
    }
</style>
<div class="dux-tools">
    <div class="bread-head">后台音频管理<span class="small">后台添加音频</span>

        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/audio/list">
            音频列表</a>
        </div>

    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/audio/<?=$acturl?>/m/edit" enctype="multipart/form-data">
     <div class="tab dux-tab">
        <div class="panel dux-box  active">
            <div class="panel-head">
                <div class="tab-head">
                    <strong>音频管理</strong>
                    <ul class="tab-nav">
                        <li class="active"><a href="#tab-1"><?php echo ($acturl=='add')?'添加':'编辑'; ?>音频</a></li>
                        <li><a href="#tab-2" onclick="upload()">付费音频</a></li>
                    </ul>
                </div>
            </div>

            <div class="tab-body">
                <!-- start tab 1 -->
                <div class="tab-panel active" id="tab-1">

                    <div class="form-group">
                        <div class="label">
                            <label>类型</label>
                        </div>
                        <div class="field">
                            <div class="button-group radio">
                                <label class="button <?php if ($avinfo == 1) : ?> active <?php endif; ?>">
                                    <input name="type" value="1" type="radio" datatype="*" <?php if ($avinfo['type'] == 1) : ?> checked <?php endif; ?> />
                                    <span class="icon icon-check text-green"></span> 免费音频
                                </label>

                                <label class="button <?php if ($avinfo == 2) : ?> active <?php endif; ?>">
                                    <input name="type" value="2" type="radio" datatype="*" <?php if ($avinfo['type'] == 2) : ?> checked <?php endif; ?> />
                                    <span class="icon icon-check text-green"></span> 付费音频
                                </label>
                            </div>
                            <div class="input-note">请选择类型</div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="label">
                            <label>类别</label>
                        </div>
                        <div class="field">
                            <select  class="input" name="audio_class" id="audio_class">
                                <option value="">请选择分类 </option>
                                <?php foreach ($lists as $av): ?>
                                <option value="<?=$av['id']?>" <?php if(!empty($avinfo['class_id']) && ($avinfo['class_id'] ==$av['id'])){echo 'selected';} ?> ><?=$av['name'];?></option>
                                <?php endforeach; ?>

                            </select>
                            <div class="input-note">请选择分类</div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="label">
                            <label>标题</label>
                        </div>
                        <div class="field">
                            <input type="text" class="input" style="width:220px;" id="title" name="title" size="60" datatype="*1-14" errormsg="最多14个字符" value="<?=$avinfo['title']?>" placeholder="标题">
                            <div class="input-note">请填写标题, 最多14个字符</div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                            <div class="label">
                                <label>标签</label>
                            </div>
                            <div class="field">
                                <div class="firstBtnBox">
                                <?php if(empty($audioTag)):?>
                                  <a class="add_input_btn firstbtn button bg-blue button-small icon" n="1">+</a>
                                <?php endif; ?>
                                </div>
                                <div class="fieldsList">
                                     
                                      <?php if(!empty($audioTag)){ foreach ($audioTag as $k=>$v){ $n = $k+2;$count=count($audioTag); ?>
                                       <span class="taginput<?=$n?>">
                                        <input n="<?=$n?>" class="tags_input input tagval<?=$n?>" value="<?=$v['name']?>" type="text" name="tags[]" />
                                        <?php if($k == ($count-1)): ?>
                                           <?php if($k < 2): ?>
                                             <a style="margin:0 10px 0 0;" class="button bg-blue button-small icon add_input_btn add<?=$n?>" n="<?=$n?>">+</a>
                                           <?php endif; ?> 
                                        <a style="margin:0 10px 0 0;" class="button bg-blue button-small icon del_input_btn del<?=$n?>" n="<?=$n?>">-</a>
                                       <?php endif; ?> 
                                       </span>
                                      <?php }  }?>
                                    
                                </div>
                                <div class="sugList" style="display:none;">
                                    <ul>
                                        
                                    </ul>
                                </div>
                                <input type="hidden" name="tagid" id="tagid" value="" />
                            </div>
                        </div>

                    <div class="form-group">
                        <div class="label">
                            <label>分享标题</label>
                        </div>
                        <div class="field">
                            <input type="text" class="input" style="width:220px;" id="share_title" name="share_title" size="60" datatype="*1-25"  errormsg="最多25个字符" placeholder="分享标题" value="<?=$avinfo['share_title']?>">
                            <div class="input-note">请填写分享标题, 最多25个字符</div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                            <div class="label">
                                <label>分享摘要</label>
                            </div>
                            <div class="field">
                                <textarea type="text" class="input  Validform_error" style="width: 500px; height: 80px;" id="share_summary" name="share_summary" size="60" datatype="*" placeholder="分享摘要" autocomplete="off" nullmsg="请填写信息！"><?=$avinfo['share_summary']?></textarea>
                                <div class="input-note" style="display: none;">请填写分享摘要</div><div class="input-note js-tip">请填写分享摘要！</div>
                            </div>
                        </div>

                    <div class="form-group">
                        <div class="label">
                            <label>Mp3</label>
                        </div>
                        <div class="field">
                            <input readonly="true" type="text" class="input show_uo_imgs" id="mp3data" name="mp3data" datatype="*" placeholder="请上传音频MP3" value="<?=$avinfo['mp3_url']?>">
                             <a class="button bg-blue button-small " data="images" id="image_upload" preview="image_preview" href="javascript:;" ><span class="icon-upload"> 上传</span></a>
                            <?php if($mp3svn>0): ?> <a class="rollbackMp3" style="margin-left: 20px;color:blue;cursor: pointer;">回溯提交版本</a><?php endif; ?>
                            <!-- <a class="button bg-blue button-small " data="image" id="image_upload"  href="javascript:;" ><span class="mp3-upload"> 上传</span></a>-->
                            <!--<a class="button bg-blue button-small icon-picture-o" id="image_preview" href="javascript:;" > 预览</a> -->
                            <div class="input-note">请上传Mp3</div>
                        </div>
                    </div>

                    <div class="form-group" style="">
                        <div class="label">
                            <label>时长</label>
                        </div>
                        <div class="field">
                            <input readonly="true" type="hidden" class="input" style="width:220px;" id="duration" name="duration" size="60" datatype="*" placeholder="音频时长" value="<?=$avinfo['duration']?>">
                            <input type="hidden" name="mp3key" value="<?=$avinfo['mp3_url']?>" id="mp3keybtnjs" />
                            <input type="hidden" name="amrid" value="" id="amrid" />
                             <div class="durationbtn001 input" style="border:none;box-shadow:none;"></div>
                        </div>
                    </div>


                    <div class="form-group" style="">
                        <div class="label">
                            <label>大小</label>
                        </div>
                        <div class="field">
                            <input readonly="true" type="hidden" class="input" style="width:220px;" id="size" name="size" size="60" datatype="*" placeholder="音频原始大小" value="<?=$avinfo['original_size']?>">
                            <input readonly="true" type="hidden" class="input" style="width:220px;" id="thumb_size" name="thumb_size" size="60" datatype="*" placeholder="音频处理后大小" value="<?=$avinfo['thumb_size']?>">

                            <div class="sizebtn001 input" style="border:none;box-shadow:none;"></div>
                        </div>
                    </div>

                       <!--
                       <div class="form-group">
                        <div class="label">
                            <label>AMR</label>
                        </div>
                        <div class="field">
                            <input type="text" class="input show_uo_amr" id="amr" name="amr" datatype="*" placeholder="请上传AMR">
                            <a class="button bg-blue button-small " data="image" id="amr_upload"  href="javascript:;" ><span class="icon-upload"> 上传</span></a>
                            <div class="input-note">请上传AMR</div>
                        </div>
                    </div>-->



                    <div class="form-group">
                        <div class="label">
                            <label>文稿</label>
                        </div>
                        <div class="field">
                            <?php if($contentSvn): ?><a class="rollbackContent" style="color:blue;cursor: pointer;">回溯提交版本</a><?php endif; ?>
                            <script id="editor" type="text/plain" style="width:554px;min-height:500px;"><?=$avinfo['content']?></script>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="label">
                            <label>字数</label>
                        </div>
                        <div class="field">
                            <input type="text" class="input" style="width:220px;" id="textNum" name="textNum" size="60" datatype="*" placeholder="字数" value="<?=$avinfo['content_count']?>">
                            <div class="input-note">请填写字数</div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="label">
                            <label>签名</label>
                        </div>
                        <div class="field">
                            <input type="text" class="input" style="width:220px;" id="sign" name="sign" size="60" datatype="*" placeholder="签名" value="<?=$avinfo['sign']?>">
                            <div class="input-note">请填写签名</div>
                        </div>
                    </div>
                </div>
                <!-- end tab 1 -->

                <!-- start tab 2 -->
                <div class="tab-panel" id="tab-2">
                    请选择音频类型

                </div>
                <!-- end tab 2 -->
            </div>

            <div class="panel-foot">
                <div class="form-button">
                    <div id="tips"></div>
                    <button class="button bg-main" type="submit">保存</button>
                    <button class="button bg" type="reset">重置</button>
                </div>
            </div>

        </div>
    </div>
    </form>
</div>

<!-- tanchucheng -->
<div id="fade" class="black_overlay">
</div>
<div id="MyDiv" class="white_content">
<div style="text-align: right; cursor: default; height: 40px;">
<span style="font-size: 16px;" class="closeBoxJs">关闭</span>
</div>
    <div class="mp3ListContainer" style="display: none;">
        <span>MP3版本记录</span><br />
        ----------------------------------------<br />
        <ul class="mp3ul">

        </ul>
    </div>

    <div class="contentListContainer" style="display: none;">
         <span>文稿版本记录</span><br />
        ----------------------------------------<br />
        <ul class="contentul">

        </ul>
    </div>

</div>

<div id="chargeAudio" style="display:none;">
    <div class="form-group">
        <div class="label">
            <label>售卖价格</label>
        </div>
        <div class="field">
            <input type="text" class="input" style="width:220px;" datatype="/^[0-9]+(.[0-9]+)?$/" id="price" name="price" size="60"  placeholder="售卖价格" autocomplete="off" value="<?php echo $avinfo['price']; ?>">
            <div class="input-note">请填写售卖价格</div>
        </div>
    </div>

    <div class="form-group">
        <div class="label">
            <label>买赠学分</label>
        </div>
        <div class="field">
            <input type="text" class="input" style="width:220px;" id="points" name="points" size="60"  placeholder="买赠学分" autocomplete="off" datatype="n" value="<?php echo $avinfo['points']; ?>" >
            <div class="input-note">请填写买赠学分</div>
        </div>
    </div>

     <div class="form-group">
        <div class="label">
            <label>音频摘要</label>
        </div>
        <div class="field">
            <!--<input type="text" class="input" style="width:220px;" id="audio_summary" name="audio_summary" size="60" datatype="*" placeholder="音频包摘要"> -->
            <textarea type="text" class="input " style="width: 500px; height: 80px;" id="summary" name="summary" size="60"  placeholder="音频摘要" autocomplete="off" datatype="*"><?php echo $avinfo['summary']; ?>
            </textarea>
            <div class="input-note">请填写音频摘要</div>
        </div>
    </div>

    <!-- 封面图片 -->
    <div class="form-group">
        <div class="label">
            <label>音频封面</label>
        </div>
        <div class="field">
            <input type="text" class="input show_uo_imgs" id="images1" placeholder="请上传封面" readonly datatype="*" value="<?php echo IMG_HOST . '/' . $avinfo['icon']; ?>" >
            <input type="hidden" name="icon" value="<?php echo $avinfo['icon']; ?>">
            <a class="button bg-blue button-small " data="images1" id="image_upload1" preview="image_preview1" href="javascript:;" ><span class="icon-upload"> 上传</span></a>
            <a class="button bg-blue button-small icon-picture-o" id="image_preview1" href="javascript:;" > 预览</a>
            <div class="input-note">请上封面(600 x 600)</div>
        </div>
    </div>

    <!-- 封面图片 -->
    <div class="form-group">
        <div class="label">
            <label>音频包头图</label>
        </div>
        <div class="field">
            <input type="text" class="input show_uo_imgs" id="images2" name="banner"  placeholder="请上传头图" readonly datatype="*" value="<?php echo IMG_HOST . '/' . $avinfo['banner']; ?>" >
            <input type="hidden" name="banner" value="<?php echo $avinfo['banner']; ?>">
            <a class="button bg-blue button-small " data="images2" id="image_upload2" preview="image_preview2" href="javascript:;" ><span class="icon-upload"> 上传</span></a>
            <a class="button bg-blue button-small icon-picture-o" id="image_preview2" href="javascript:;" > 预览</a>
            <div class="input-note">请上传头图(960x540)</div>
        </div>
    </div>
</div>

<script>

    // 用来控制是否已经触发了上传控件
    var bClicked = false;
    function upload() {

        var checkedVal = $(":input[name='type']:checked").val();
        if (bClicked || checkedVal != 2) return;

        bClicked = true;
        $('#image_upload1').duxFileUpload({
            uploadUrl: '/audioclass/upload',
            type: 'jpg,png,gif',
            complete: function (data) {
                $('.show_uo_imgs').eq(1).val(data.savepath);
            }
        });

        $('#image_upload2').duxFileUpload({
            uploadUrl: '/audioclass/upload',
            type: 'jpg,png,gif',
            complete: function (data) {
                $('.show_uo_imgs').eq(2).val(data.savepath);
            }
        });
    }

    $( function () {
        // clone收费音频选项卡
        $(":input[name='type']").on('click', function () {

            var value = parseInt($(this).val());

            if (value === 1) {
                $("#tab-2").html("");
            } else {
                bClicked = false;
                var oElement = $("#chargeAudio").clone();
                $("#tab-2").html($(oElement).html());
            }
        });
        // 自动触发click事件
        $(":input[name='type']:checked").trigger('click');
    });
</script>
<script  type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
        $('#image_upload').duxFileUpload({
            uploadUrl: '/audio/upload',
            type: 'mp3,audio/mpeg,audio,mpeg',
            complete: function (data) {
                $('.show_uo_imgs').val(data.savepath);
                $('#duration').val(data.duration);
                $('#size').val(data.size);
                $('#thumb_size').val(0);
                $('#mp3keybtnjs').val(data.mp3key);
                $('.durationbtn001').html(formatSeconds(data.duration));
                 $('.sizebtn001').html(bytesToSize(data.size));
            }
        });



    });
</script>

<script type="text/javascript">
var aid="<?=$avinfo['id']?>";
var appmsgcount = 1;
var appmsgcountmun = 1;
//var ue = UE.getEditor('editor');

var ue = UE.getEditor('editor',{
    enableAutoSave: false,
    saveInterval: 0
       });

ue.addListener( 'contentChange', function(editor) {
     $('#textNum').val(ue.getContentTxt().length);
 });

$(function(){

$('.durationbtn001').html(formatSeconds($('#duration').val()));
$('.sizebtn001').html(bytesToSize($('#size').val()));

$("a.appmsg_add").on('click',function(){
        if(appmsgcount < 10){
                appmsgcount ++;
                appmsgcountmun ++;

                var appmsgnewhtml = '<div id="appmsgItem'+appmsgcountmun+'" data-id="'+appmsgcountmun+'" class="appmsg_item js_appmsg_item "><img class="js_appmsg_thumb appmsg_thumb" src=""><i class="appmsg_thumb default">缩略图</i><h4 class="appmsg_title"><a href="javascript:void(0);" target="_blank">标题</a></h4><div class="appmsg_edit_mask"><a class="icon18_common edit_gray js_edit" data-id="'+appmsgcountmun+'" href="javascript:void(0);">编辑</a><a class="icon18_common del_gray js_del" data-id="'+appmsgcountmun+'" href="javascript:void(0);">删除</a></div></div>';
                $("#js_appmsg_preview").append(appmsgnewhtml);
        }else{
                alert("最多10条");
        }
});

$("#js_appmsg_preview").on('click','a.js_del',function(){
        var thisdataid = $(this).attr("data-id");
        appmsgcount--;
        $("#js_appmsg_preview #appmsgItem" + thisdataid).remove();
        $(".appmsg_editor").animate({marginTop:0});
});

$("#js_appmsg_preview").on('click','a.js_edit',function(e){
        var dataheight = $(this).attr("data-height");
        if(dataheight){
                $(".appmsg_editor").animate({marginTop:0});
        }else{
                $(".appmsg_editor").animate({marginTop:e.pageY-67});
        }
});



function ShowDiv(show_div,bg_div){
        document.getElementById(show_div).style.display='block';
        document.getElementById(bg_div).style.display='block' ;
        var bgdiv = document.getElementById(bg_div);
        bgdiv.style.width = document.body.scrollWidth;
        // bgdiv.style.height = $(document).height();
        $("#"+bg_div).height($(document).height());
};




//关闭弹出层
function CloseDiv(show_div,bg_div)
{
    document.getElementById(show_div).style.display='none';
    document.getElementById(bg_div).style.display='none';
};

//音频版本记录弹出层
$('.rollbackMp3').on('click',function(){
        $.ajax({
              type: 'POST',
              url: '/audio/mp3list',
              data: {aid:aid},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                  if(data.list){
                      var str = '';
                      $.each(data.list,function(n,v){
                          str+='<li><span>'+v.cdate+'</span><br />'+v.operator_name+'重传语音<br /> <a style="color:blue;cursor: pointer;" class="rollbacknodemp3" rid="'+v.id+'">回滚到此节点</a></li>';
                          str+='----------------------------------------<br />';
                      });
                      $('.mp3ul').html(str);

                      $('.contentListContainer').hide();
                      $('.mp3ListContainer').show();
                      ShowDiv('MyDiv','fade');
                  }else{
                      alert('请求失败');
                  }



              },
              error:function(xhr,type){
                  alert('请求错误！');
              }
           });
  });

//文稿版本记录弹出层
$('.rollbackContent').on('click',function(){
     $.ajax({
              type: 'POST',
              url: '/audio/contentlist',
              data: {aid:aid},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                  if(data.list){
                      var str = '';
                      $.each(data.list,function(n,v){
                          str+='<li><span>'+v.cdate+'</span><br />'+v.operator_name+'更新文稿<br /> <a style="color:blue;cursor: pointer;" class="rollbacknodecontent" rid="'+v.id+'">回滚到此节点</a></li>';
                          str+='----------------------------------------<br />';
                      });
                      $('.contentul').html(str);

                      $('.mp3ListContainer').hide();
                      $('.contentListContainer').show();
                      ShowDiv('MyDiv','fade');
                  }else{
                      alert('请求失败');
                  }



              },
              error:function(xhr,type){
                  alert('请求错误！');
              }
           });

});

//关闭弹出层
$('.closeBoxJs').on('click',function(){
    CloseDiv('MyDiv','fade');
});

//回滚音频到某一节点
$('body').delegate('.rollbacknodemp3','click',function(){
    var rid = $(this).attr('rid');
      $.ajax({
              type: 'POST',
              url: '/audio/rollbackMp3',
              data: {id:rid},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                 if(data.status){
                     $('#mp3data').val(data.res.mp3key);
                     $('#mp3keybtnjs').val(data.res.mp3key);
                     $('#amrid').val(data.res.amr);
                     $('#duration').val(data.res.duration);
                     $('#size').val(data.res.original_size);
                     $('#thumb_size').val(data.res.thumb_size);
                     $('.durationbtn001').html(formatSeconds(parseInt(data.res.duration)));
                     $('.sizebtn001').html(bytesToSize(parseInt(data.res.original_size)));
                     CloseDiv('MyDiv','fade');
                 }else{
                     alert('回滚失败');
                     CloseDiv('MyDiv','fade');
                 }

              },
              error:function(xhr,type){
                  alert('请求错误！');
              }
           });
});

//回滚文稿到选中节点
$('body').delegate('.rollbacknodecontent','click',function(){
    var rid = $(this).attr('rid');
    $.ajax({
              type: 'POST',
              url: '/audio/rollbackContent',
              data: {id:rid},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                        if(data.status){
                            var content = data.res.content;
                            ue.setContent(content);
                            CloseDiv('MyDiv','fade');
                        }else{
                            alert('回滚失败');
                            CloseDiv('MyDiv','fade');
                        }
              },
              error:function(xhr,type){
                  alert('请求错误！');
                  CloseDiv('MyDiv','fade');
              }
           });
});




     //add tag input list
        $("body").delegate('.add_input_btn','click',function(){
            var num = parseInt($(this).attr('n')),n=0;
            n = parseInt(num + 1);
            var addinput = "<a style=\"margin:0 10px 0 0;\" class=\"button bg-blue button-small icon add_input_btn add"+n+"\" n=\""+n+"\">+</a>";
            var delinput = "<a style=\"margin:0 10px 0 0;\" class=\"button bg-blue button-small icon del_input_btn del"+n+"\" n=\""+n+"\">-</a> ";
            
           
            
            var inputHtml="<span class=\"taginput"+n+"\"><input n=\""+n+"\" class=\"tags_input input tagval"+n+"\" type=\"text\" name=\"tags[]\"/>";
                if(n < 4){
                    inputHtml+=addinput;
                }
                inputHtml+=delinput;
                inputHtml+="</span>";
            
            if(num > 1){
                $('.add'+num).remove();
                $('.del'+num).remove();
            }else{
                $('.firstbtn').hide();
            }
            $(inputHtml).appendTo($('.fieldsList'));
        });
        
        //del tag input list
        $("body").delegate('.del_input_btn','click',function(){
            var num = parseInt($(this).attr('n')),n=0;
            n = parseInt(num - 1);
            var addinput = "<a style=\"margin:0 10px 0 0;\" class=\"button bg-blue button-small icon add_input_btn add"+n+"\" n=\""+n+"\">+</a>";
            var delinput = "<a style=\"margin:0 10px 0 0;\" class=\"button bg-blue button-small icon del_input_btn del"+n+"\" n=\""+n+"\">-</a> ";
            
                $('.taginput'+num).remove();
                if(parseInt(num) == 2){
                    if($('.firstbtn').length > 0){
                        $('.firstbtn').show();
                    }else{
                        var firstBtn = "<a class=\"add_input_btn firstbtn button bg-blue button-small icon\" n=\"1\">+</a>";
                        $(firstBtn).appendTo($('.firstBtnBox'));
                    }
                    
                }else{
                   $(addinput).appendTo($('.taginput'+n));
                   $(delinput).appendTo($('.taginput'+n));
                }
                
                $('.sugList').css('display','none');
                $('.sugList').css('margin-left','0');
        });
        
        //add tag input value
        $('body').delegate('.tags_input','keyup',function(){
            var tagVal = $(this).val(),num = parseInt($(this).attr('n'));
            var marginleft=0;
            marginleft = parseInt((num-2)*170);
            
            $.ajax({
                    url: '/audio/searchTag/',
                    type: 'POST',
                    dataType: 'json',
                    data: {kwd: tagVal},
                    success: function(data){
                        $('.sugList').html('');
                        var liStr = '<ul>';
                        if(data.status == 'ok'){
                             $.each(data.res, function (i, item) {
                                liStr+= '<li class=\"sug_li\">'+item.name+'</li>';
                             });
                            
                        }
                            liStr+="<li class=\"sug_addtag\" style=\"padding-top:10px\">";
                            liStr+="<span><input  class=\"newtag\" type=\"text\" name=\"newtag\"/ size=\"8\">";
                            liStr+="<a style=\"margin:0 10px 0 0;\" n=\""+num+"\" class=\"button bg-blue button-small icon newtagbtn \">添加</a></span>";
                            liStr+="</li>";
                            liStr+='</ul';
                            $('.sugList').html(liStr);
                            $('.sugList').css('margin-left',marginleft);
                            $('.sugList').css('display','block');
                            $('.sugList').attr('n',num);
                        
                    }
                });           
            
        });
        
        //sug ul li click
        $('body').delegate('.sug_li','click',function(){
            var txt = $(this).text(),num = $('.sugList').attr('n');
            $('.tagval'+num).val(txt);
            
            $('.sugList').css('display','none');
            $('.sugList').css('margin-left','0');
            
        });
        
        //add new tag
        $('body').delegate('.newtagbtn','click',function(){
            var newtag = $('.newtag').val(),num = $(this).attr('n');
            if(newtag != '' && newtag != null){
                if(confirm('添加新标签？\n添加后不能编辑或删除')){
                        $.ajax({
                        url: '/audio/addTag/',
                        type: 'POST',
                        dataType: 'json',
                        data: {tag: newtag},
                        success: function(data){
                            if(data.status == 'error'){
                                alert(data.code);
                                return false;
                            }else{
                                $('.tagval'+num).val(newtag);
                                $('.newtag').val('');
                                hideSug();
                            }

                        }
                    });
                }
            }else{
                alert('请输入新标签');
                return false;
            }
        });
        
       $('body').on('click','input.tags_input',function(){
            var tagVal = $(this).val(),num = parseInt($(this).attr('n'));
            var marginleft=0;
            marginleft = parseInt((num-2)*170);
            
            $.ajax({
                    url: '/audio/searchTag/',
                    type: 'POST',
                    dataType: 'json',
                    data: {kwd: tagVal},
                    success: function(data){
                        $('.sugList').html('');
                        var liStr = '<ul>';
                        if(data.status == 'ok'){
                             $.each(data.res, function (i, item) {
                                liStr+= '<li class=\"sug_li\">'+item.name+'</li>';
                             });
                            
                        }
                            liStr+="<li class=\"sug_addtag\" style=\"padding-top:10px\">";
                            liStr+="<span><input  class=\"newtag\" type=\"text\" name=\"newtag\"/ size=\"8\">";
                            liStr+="<a style=\"margin:0 10px 0 0;\" n=\""+num+"\" class=\"button bg-blue button-small icon newtagbtn \">添加</a></span>";
                            liStr+="</li>";
                            liStr+='</ul';
                            $('.sugList').html(liStr);
                            $('.sugList').css('margin-left',marginleft);
                            $('.sugList').css('display','block');
                            $('.sugList').attr('n',num);
                        
                    }
                }); 
        });
        
        $(document).bind('click',function(e){ 
            var target = $(e.target); 
            if(target.closest('.sugList .sug_li,input.tags_input').length == 0){ //a表示例外元素
                hideSug();//b表示隐藏的元素
            }; 
        });













});


function bytesToSize(bytes) {
       if (bytes === 0) return '0 B';

        var k = 1024;

        sizes = ['B','KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];

        i = Math.floor(Math.log(bytes) / Math.log(k));

return (bytes / Math.pow(k, i)).toPrecision(3) + ' ' + sizes[i]; 
       //toPrecision(3) 后面保留一位小数，如1.0GB                                                                                                                  //return (bytes / Math.pow(k, i)).toPrecision(3) + ' ' + sizes[i];
}

function formatSeconds(value) {
        var theTime = parseInt(value);// 秒
        var theTime1 = 0;// 分
        var theTime2 = 0;// 小时
        if(theTime > 60) {
           theTime1 = parseInt(theTime/60);
           theTime = parseInt(theTime%60);
           if(theTime1 > 60) {
              theTime2 = parseInt(theTime1/60);
              theTime1 = parseInt(theTime1%60);
            }
        }
        var result = ""+parseInt(theTime)+"秒";
        if(theTime1 > 0) {
            result = ""+parseInt(theTime1)+"分"+result;
        }
        if(theTime2 > 0) {
            result = ""+parseInt(theTime2)+"小时"+result;
        }
        return result;
   }
   
   
   function hideSug(){
    $('.sugList').css('display','none');
    $('.sugList').css('margin-left','0');
    $('.sugList').html('');
 }
</script>