<div class="dux-tools">
    <div class="bread-head">音频分类<span class="small">音频分类列表</span>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/audioclass/add">添加音频分类</a></li>
            </ul>
        </div>
    </div>
</div>


<div class="admin-main">
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <div class="panel dux-box">

        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">ID</th>
                        <th width="*">分类名称</th>
                        <th width="*">分类ICON</th>
                        <th width="*">分类状态</th>
                        <th width="*">分类排序</th>
                        <th width="*">datetime</th>
                        <th width="*">count</th>
                        <th width="*">操作</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                <td><?php echo $val['name']; ?></td>
                                <td>
                                    <img src="<?php echo $val['icon']; ?>" title="<?php echo $val['name']; ?>" alt="<?php echo $val['name']; ?>" width='48' height='48' />
                                </td>
                                <td>
                                    <?php if ($val['status']) : ?> 正常 <?php else : ?> 删除 <?php endif; ?>
                                </td>
                                <td><?php echo $val['order']; ?></td>
                                <td><?php echo $val['datetime']; ?></td>
                                <td><?php echo $val['count']; ?></td>
                                <td>
                                    <a class="button bg-blue button-small icon-pencil" href="/audioclass/edit/id/<?php echo $val['id']; ?>" title="编辑"></a>
                                    <a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/audioclass/delete" data='{"id":<?php echo $val['id']; ?>}' title="删除"></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
Do.ready('base', function () {
$('#table').duxTable();
});
</script>