<script type="text/javascript" src="<?=ASSET_URL?>/static/lib/editor/ueditor.config.js"></script>
<script type="text/javascript" src="<?=ASSET_URL?>/static/lib/editor/ueditor.all.js"></script>
<link rel="stylesheet" type="text/css" href="<?=ASSET_URL?>/static/lib/editor/themes/default/css/ueditor.css" meta="screen">
<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<style>
    .link{cursor: pointer;color: blue;}
    .hidden{display:none;};
</style>
<?php echo Asset::getResource('promot.css', 'static/common');?>
<div class="dux-tools">
    <div class="bread-head">音频活动列表<span class="small"></span>
        
    </div>

</div>

<div class="dux-tools">
    <div class="bread-head">
        <span class="small">
            <a href="/campaign/list" class="bread-head button  <?php echo ($ctype == 2)?('bg-red'):('bg-blue'); ?> " >充值赠送节操币活动列表</a>  
            <a class="button   bread-head  <?php echo ($ctype == 1)?('bg-red'):('bg-blue'); ?>" href="/campaign/refundlist"   >会员返回节操币活动列表</a> 
        </span>
        
    </div>
</div>

<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>活动名称</th>
                        <th>活动开始时间</th>
                        <th>活动结束时间</th>
                        <th>活动类型</th>
                        <th>用户类型</th>
                        
                        <?php if($ctype == 2): ?>
                        <th>充值金额</th>
                        <?php endif; ?>
                        <th>赠送节操币</th>
                        <th>是否重复赠送节操币</th>
                        <th>活动状态</th>
                        <th>操作</th>
                        
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                
                                <td><?php echo $val['rule_name']; ?></td>
                                <td><?php echo $val['start_date']; ?></td>
                                <td><?php echo $val['valid_thru']; ?></td>
                                <td><?php echo $val['type']; ?></td>
                                <td><?php echo $val['identity_category']; ?></td>
                                
                                <?php if($ctype == 2): ?>
                                <td><?php echo $val['top_up_amount']; ?></td>
                                <?php endif; ?>
                                <td><?php echo $val['gift_amount']; ?></td>
                                <td><?php echo ($val['num_of_usage']==1)?('不重复赠送'):('无限制'); ?></td>
                                <td><?php echo ($val['is_activated']==1)?'启用':'停用'; ?></td>
                                <td><a href="/campaign/edit/cid/<?=$val['id']?>/ctype/<?=$ctype?>">修改</a></td>
                                
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </tbody>
            </table>
        </div>
        
        <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
        <?=$pagger?>
        </div>
        <?php endif;?>



    </div>



<script>
//search
$('.searchbtn').click(function(){
    var kwd = $('#kwd').val();
    var url = $(this).attr('url');
    var sd = $('.startdate').val(),ed=$('.enddate').val();
    var device = $('#device').val(),status = $('#status').val();
    if(kwd == '' || kwd == null){
        kwd=0;
    }
    
    
    url = url+kwd;
    if(sd !='' && ed !=''){
        url+='/sd/'+sd+'/ed/'+ed;
    }
    
    if(device !='' && device !=null){
        url+='/type/'+device;
    }
    
    if(status !=''){
        url+='/st/'+status;
    }
    
    
    
    window.location.href = url;
});

$('.upstatus').click(function(){
    var _this = $(this),txt=_this.attr('txt'),st=_this.attr('st'),_class=$('.upstatus'),fid=_this.attr('fid');
    var url='/charge/up/fid/'+fid+'/st/'+st;
    $.ajax({
              type: 'POST',
              url: url,
              data: {},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                  if(data.status == 1){
                     $('.statusname'+fid).text(txt);
                     
                     _this.addClass('hidden');
                     _this.siblings().removeClass('hidden');
                  }else{
                      alert('更新失败');
                  }

              },
              error:function(xhr,type){
                  alert('请求错误！');
              }
           });
    
});

</script>
</div>