<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/admincenter/js/calendar/WdatePicker.js"></script>
<div class="dux-tools">
    <div class="bread-head">音频排期                <span class="small">添加音频排期</span>
    </div>
    <br>
    <div class="tools-function clearfix">
        <div class="button-group float-right">
            <a class="button button-small bg-main icon-list" href="/audiotopic/index">
                音频排期列表</a>
        </div>
    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/audiotopic/add">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>菜单管理</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">添加排期</a></li>
                            <!--li><a href="#tab-2">接口配置</a></li>
                            <li><a href="#tab-3">微信支付配置</a></li>
                            <li><a href="#tab-4">网站微信登录配置</a></li>
                            <li><a href="#tab-5">使用说明</a></li-->
                        </ul>
                    </div>
                </div>
                <div class="tab-body">
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>排期名称</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="title" name="title" size="60" datatype="*" placeholder="排期名称" autocomplete="off">
                                <div class="input-note">请填排期名称</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>排期类型</label>
                            </div>
                            <div class="field">
                                <select class="input paytypebtn" name="type">
                                    <option value="1">免费音频</option>
                                    <option value="2">收费长音频</option>
                                </select>
                                <div class="input-note">请填排期类型</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>排期封面</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input show_uo_imgs" id="images" name="icon" datatype="*" placeholder="请上传排期封面" readonly>
                                <a class="button bg-blue button-small " data="images" id="image_upload" preview="image_preview" href="javascript:;" ><span class="icon-upload"> 上传</span></a>
                                <a class="button bg-blue button-small icon-picture-o" id="image_preview" href="javascript:;" > 预览</a>
                                <div class="input-note">请上传分类ICON</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>上线日期</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input datebtn" style="width:220px;" id="datetime" name="datetime"   onfocus="WdatePicker({minDate:'2015-09-02'})" style="cursor:pointer;" size="60" datatype="*" placeholder="音频上线日期" autocomplete="off">
                                <div class="input-note">请选择音频上线日期</div><div id="paychecknote" style="display: none;color: red;">当天常规计费类型的排期已存在，不能重复</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>排期定价</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="topic_price" name="topic_price" size="60" datatype="*" placeholder="排期定价" autocomplete="off"> 节操币价格
                                <div class="input-note">请输入排期定价</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>音频列表</label>
                            </div>
                            <div class="field">
                                <textarea type="text" class="input audiolist" style="width: 500px; height: 80px;" id="audiolist" name="audiolist" size="60" datatype="*" placeholder="音频列表" autocomplete="off"></textarea>
                                <button class="button viewfile" style="vertical-align: top; width: 100px; height: 80px;" >文件预览</button>
                                <div class="clearfix selectlist checkbox"></div>
                                <div class="clearfix selectnote checkbox"></div>
                                <div class="input-note">请输入音频列表 id,id,id,id</div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>




<script  type="text/javascript">
    Do.ready('base', function () {
        
        $('#form').duxFormPage();
        duxConfig.upDir = '';
        $('#image_upload').duxFileUpload({
            uploadUrl: '/audiotopic/upload',
            type: 'jpeg,jpg,png',
            complete: function (data) {
                $('.show_uo_imgs').val(data.savepath);
            }
        });
        $('.viewfile').click(function(){
            audiolist = $('.audiolist').val();
            if(audiolist){
                $('.selectlist').children('label').remove();
                $.ajax({
                    url: '/audiotopic/audiolist',
                    type: 'POST',
                    dataType: 'json',
                    data: {audiolist: audiolist},
                    success: function(data){
                        if(data.status == 'error'){
                            alert(data.code);
                            return false;
                        }
                        loadlist(data.data, 'selectlist','.selectnote');
                    }
                });
            }
            return false;
        });
    });
    function loadlist(data, dom,note){
        var str = "";
        var atime = 0;
        $.each(data, function (i, item) {
            str += appendAudio(item);
            atime += parseInt(item.duration);
        });
        $('.' + dom).append(str);
         $(note).html( '共'+data.length+'个音频文件，累计时长：'+formatSeconds(atime) );
    }
    function appendAudio(item){
        var str = "";
        str +=  "  <label class=\"button active\" style=\"margin: 0 5px 5px 0;  float: left;  position: relative;  font-weight: normal;\">";
        str +=  "  <input name=\"aid[]\" value=\""+item.id+"\" type=\"checkbox\" checked=\"checked\">";
        str +=  "  "+item.title+" ";
        str +=  "   </label>";
        return str;
    }
    
     function formatSeconds(value) {
        var theTime = parseInt(value);// 秒
        var theTime1 = 0;// 分
        var theTime2 = 0;// 小时
        if(theTime > 60) {
           theTime1 = parseInt(theTime/60);
           theTime = parseInt(theTime%60);
           if(theTime1 > 60) {
              theTime2 = parseInt(theTime1/60);
              theTime1 = parseInt(theTime1%60);
            }
        }
        var result = ""+parseInt(theTime)+"秒";
        if(theTime1 > 0) {
            result = ""+parseInt(theTime1)+"分"+result;
        }
        if(theTime2 > 0) {
            result = ""+parseInt(theTime2)+"小时"+result;
        }
        return result;
   }
   
   
  $('#audiolist').on('click',function(){
      var topicDate = $('#datetime').val();
      var paytype   = $('.paytypebtn').val();
      
      if(paytype !='' && paytype == '1'){
          if(topicDate == '' || topicDate == null){
            alert('请填写排期日期');return false;
          }
          checkPayRecord(topicDate);
      }
      return;
      
  });
  
  function checkPayRecord(topicDate){
      $.ajax({
              type: 'POST',
              url: '/audiotopic/checkPayTypeRecord',
              data:{dtime:topicDate},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                  if(data.status == 'ok'){
                      $('#paychecknote').hide();
                  }else{
                      alert('当天常规计费类型的排期已存在，不能重复！');
                      $('#paychecknote').show();
                  }



              },
              error:function(xhr,type){
                  alert('请求失败！');
              }
           });
  }
   
   
   
 

</script>