<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/admincenter/js/calendar/WdatePicker.js"></script>
<?php echo Asset::getResource('promot.css', 'admincenter/common');?>
<div class="dux-tools">
    <div class="bread-head">音频排期                <span class="small">编辑音频排期</span>
    </div>
    <br>
    <div class="tools-function clearfix">
        <div class="button-group float-right">
            <a class="button button-small bg-main icon-list" href="/audiotopic/index">
                音频排期列表</a>
        </div>
    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/audiotopic/edit/id/<?=$topic['id']?>">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>菜单管理</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">编辑排期</a></li>
                            <!--li><a href="#tab-2">接口配置</a></li>
                            <li><a href="#tab-3">微信支付配置</a></li>
                            <li><a href="#tab-4">网站微信登录配置</a></li>
                            <li><a href="#tab-5">使用说明</a></li-->
                        </ul>
                    </div>
                </div>
                <div class="tab-body">
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>排期名称</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="title" name="title" value="<?=$topic['title']?>" size="60" datatype="*" placeholder="排期名称" autocomplete="off">
                                <div class="input-note">请填排期名称</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>排期类型</label>
                            </div>
                            <div class="field">
                                <select class="input" name="type">
                                    <option value="1" <?php if(1 == $topic['type']):?>selected="selected"<?php endif;?>>常规计费</option>
                                    <option value="2" <?php if(2 == $topic['type']):?>selected="selected"<?php endif;?>>单独计费</option>
                                </select>
                                <div class="input-note">请填排期类型</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>排期封面</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input show_uo_imgs" id="images" name="icon" value="<?=$topic['icon']?>" datatype="*" placeholder="请上传排期封面" readonly>
                                <a class="button bg-blue button-small " data="images" id="image_upload" preview="image_preview" href="javascript:;" ><span class="icon-upload"> 上传</span></a>
                                <a class="button bg-blue button-small icon-picture-o" id="image_preview" href="javascript:;" > 预览</a>
                                <div class="input-note">请上传分类ICON</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>上线日期</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="datetime" name="datetime" value="<?=$topic['datetime']?>" onfocus="WdatePicker({minDate:'%y-%M-{%d+1}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="音频上线日期" autocomplete="off">
                                <div class="input-note">请选择音频上线日期</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>音频列表</label>
                            </div>
                            <div class="field">
                                <textarea type="text" class="input audiolist" style="width: 500px; height: 80px;" id="audiolist" name="audiolist" size="60" datatype="*" placeholder="音频列表" autocomplete="off"><?=$topic['audio']?></textarea>
                                <button class="button viewfile" style="vertical-align: top; width: 100px; height: 80px;" >文件预览</button>
                                <?php if($topicRecordNum > 0): ?>
                                   <a tid="<?=$tid?>" class="rollbackContent" style="margin-left: 20px;color:blue;cursor: pointer;">回溯提交版本</a>
                                <?php endif; ?>
                                <div class="clearfix selectlist checkbox"></div>
                                <div class="clearfix selectnote checkbox"></div>
                                <div class="input-note">请输入音频列表 id,id,id,id</div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <input type="hidden" name="topicid" value="<?=$topic['id']?>">
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<!-- tanchucheng -->
<div id="fade" class="black_overlay">
</div>
<div id="MyDiv" class="white_content">
<div style="text-align: right; cursor: default; height: 40px;">
<span style="font-size: 16px;" class="closeBoxJs">关闭</span>
</div>
    
    
    <div class="contentListContainer" style="display: none;">
         <span>音频排期版本记录</span><br />
        ----------------------------------------<br />
        <ul class="contentul">
            
        </ul>
    </div>
    
</div>


<script  type="text/javascript">
    var tid="<?=$tid;?>";
    Do.ready('base', function () {
        
        $('#form').duxFormPage();
        duxConfig.upDir = '';
        $('#image_upload').duxFileUpload({
            uploadUrl: '/audiotopic/upload/m/edit',
            type: 'jpeg,jpg,png',
            complete: function (data) {
                $('.show_uo_imgs').val(data.savepath);
            }
        });
        $('.viewfile').click(function(){
            audiolist = $('.audiolist').val();
            if(audiolist){
                $('.selectlist').children('label').remove();
                $.ajax({
                    url: '/audiotopic/editaudiolist',
                    type: 'POST',
                    dataType: 'json',
                    data: {audiolist: audiolist,tid:tid},
                    success: function(data){
                        if(data.status == 'error'){
                            alert(data.code);
                            return false;
                        }
                        loadlist(data.data, 'selectlist','.selectnote');
                    }
                });
            }
            return false;
        });
        $('.viewfile').click();
    });
    function loadlist(data, dom,note){
        var str = "";
        var atime = 0;
        $.each(data, function (i, item) {
            str += appendAudio(item);
            atime += parseInt(item.duration);
        });
        $('.' + dom).append(str);
        $(note).html( '共'+data.length+'个音频文件，累计时长：'+formatSeconds(atime) );
    }
    function appendAudio(item){
        var str = "";
        str +=  "  <label class=\"button active\" style=\"margin: 0 5px 5px 0;  float: left;  position: relative;  font-weight: normal;\">";
        str +=  "  <input name=\"aid[]\" value=\""+item.id+"\" type=\"checkbox\" checked=\"checked\">";
        str +=  "  "+item.title+" ";
        str +=  "   </label>";
        return str;
    }
    
    function formatSeconds(value) {
        var theTime = parseInt(value);// 秒
        var theTime1 = 0;// 分
        var theTime2 = 0;// 小时
        if(theTime > 60) {
           theTime1 = parseInt(theTime/60);
           theTime = parseInt(theTime%60);
           if(theTime1 > 60) {
              theTime2 = parseInt(theTime1/60);
              theTime1 = parseInt(theTime1%60);
            }
        }
        var result = ""+parseInt(theTime)+"秒";
        if(theTime1 > 0) {
            result = ""+parseInt(theTime1)+"分"+result;
        }
        if(theTime2 > 0) {
            result = ""+parseInt(theTime2)+"小时"+result;
        }
        return result;
   }
    
    
    function ShowDiv(show_div,bg_div){
        document.getElementById(show_div).style.display='block';
        document.getElementById(bg_div).style.display='block' ;
        var bgdiv = document.getElementById(bg_div);
        bgdiv.style.width = document.body.scrollWidth;
        // bgdiv.style.height = $(document).height();
        $("#"+bg_div).height($(document).height());
};



            
//关闭弹出层
function CloseDiv(show_div,bg_div)
{
    document.getElementById(show_div).style.display='none';
    document.getElementById(bg_div).style.display='none';
};





//文稿版本记录弹出层
$('.rollbackContent').on('click',function(){
    var tid= $(this).attr('tid');//alert(tid);return ;
     $.ajax({
              type: 'POST',
              url: '/audiotopic/topiclist/',
              data: {tid:tid},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                  if(data.status == 'ok'){
                      var str = '';
                      $.each(data.data,function(n,v){
                          str+='<li><span>'+v.datetime+'</span><br />'+v.user+'更新排期<br /> <a style="color:blue;cursor: pointer;" class="rollbacknodecontent" rid="'+v.id+'">回滚到此节点</a></li>';
                          str+='----------------------------------------<br />';
                      });
                      $('.contentul').html(str);
                      $('.contentListContainer').show();
                      ShowDiv('MyDiv','fade');
                  }else{
                      alert('请求失败');
                  }



              },
              error:function(xhr,type){
                  alert('请求失败！');
              }
           }); 

});

//关闭弹出层
$('.closeBoxJs').on('click',function(){
    CloseDiv('MyDiv','fade');
});


//回滚文稿到选中节点
$('body').delegate('.rollbacknodecontent','click',function(){
    var rid = $(this).attr('rid');
    $.ajax({
              type: 'POST',
              url: '/audiotopic/rollbackTopic',
              data: {rid:rid},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){                 
                        if(data.status){
                            var content = data.data.audio;
                            $('#audiolist').val(content);
                            CloseDiv('MyDiv','fade');
                            $('.viewfile').click();
                        }else{
                            alert('回滚失败');
                            CloseDiv('MyDiv','fade');
                        }
              },
              error:function(xhr,type){
                  alert('请求错误！');
                  CloseDiv('MyDiv','fade');
              }
           });
});

    
    

</script>