<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/admincenter/js/calendar/WdatePicker.js"></script>
<div class="dux-tools">
    <div class="bread-head">主题包排期                <span class="small">添加主题包排期</span>
    </div>
    <br>
    <div class="tools-function clearfix">
        <div class="button-group float-right">
            <a class="button button-small bg-main icon-list" href="/audiotopic/listThemePackage">
                主题包排期列表</a>
        </div>
    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/audiotopic/addDailyPackage">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>菜单管理</strong>
                        <ul class="tab-nav">

                            <li class="active"><a href="#tab-1" id="tabtn1" num="1" href="#tab-1" class="tablists ">基本信息</a></li>
                            <li><a href="#tab-3" id="tabtn3" num="3" class="tablists " onclick="upload();">收费音频</a></li>
                            <li><a href="#tab-4" id="tabtn4" num="4" class="tablists lastab">电子书</a></li>
                        </ul>
                    </div>
                </div>
                <div class="tab-body">
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>排期名称</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="title" name="title" size="60" datatype="*" errormsg="最多12个字符" placeholder="排期名称" autocomplete="off">
                                <input type="hidden" class="input" style="width:220px;" id="statusBtn" name="status" value="1" size="60" datatype="*1-12" errormsg="" placeholder="" autocomplete="off">

                                <div class="input-note">请填排期名称</div>
                            </div>
                        </div>
                         <div class="form-group">
                            <div class="label">
                                <label>上线日期</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input datebtn" style="width:220px;" id="datetime" name="datetime"   onfocus="WdatePicker({minDate:'%y-%M-{%d+1}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="音频上线日期" autocomplete="off">
                                <!--<a style="cursor: pointer;" class="checkDailyRecord">检测</a>-->
                                <div class="input-note">请选择音频上线日期</div><div id="paychecknote" style="display: none;color: red;">当天的日常排期已存在，不能重复</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <input name="type" type="hidden" value="2" />
                        </div>




                        <div class="form-group">
                            <div class="label">
                                <label>排期封面</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input show_uo_imgs" id="images" datatype="*" placeholder="请上传排期封面" readonly>
                                <input type="hidden" name="icon" />
                                <a class="button bg-blue button-small " data="images" id="image_upload" preview="image_preview" href="javascript:;" ><span class="icon-upload"> 上传</span></a>
                                <a class="button bg-blue button-small icon-picture-o" id="image_preview" href="javascript:;" > 预览</a>
                                <div class="input-note">请上传排期封面，尺寸为600x600</div>
                            </div>
                        </div>

                    </div>


                    <div class="tab-panel" id="tab-3">

                        <div class="form-group">
                            <div class="label">
                                <label>售卖价格</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="audio_price" name="audio_price" size="60" datatype="*" placeholder="售卖价格" autocomplete="off">
                                <div class="input-note">请填售卖价格</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="label">
                                <label>买赠学分</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="audio_points" name="audio_points" size="60" datatype="*" placeholder="买赠学分" autocomplete="off">
                                <div class="input-note">请填买赠学分</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="label">
                                <label>音频包摘要</label>
                            </div>
                            <div class="field">
                                <!--<input type="text" class="input" style="width:220px;" id="audio_summary" name="audio_summary" size="60" datatype="*" placeholder="音频包摘要">-->
                                <textarea type="text" class="input " style="width: 500px; height: 80px;" id="audio_summary" name="audio_summary" size="60" datatype="*" placeholder="音频包摘要" autocomplete="off"></textarea>
                                <div class="input-note">请填写音频包摘要</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="label">
                                <label>音频包简介</label>
                            </div>
                            <div class="field">
                                <!--<input type="text" class="input" style="width:220px;" id="audio_summary" name="audio_summary" size="60" datatype="*" placeholder="音频包摘要"> -->
                                <textarea type="text" class="input " style="width: 500px; height: 80px;" id="audio_brife" name="audio_brife" size="200"  placeholder="音频包简介" autocomplete="off"></textarea>
                                <div class="input-note">请填写音频包简介(显示在音频包详情页，非必填)</div>
                            </div>
                        </div>

                        <!-- 封面图片 -->
                        <div class="form-group">
                            <div class="label">
                                <label>音频包封面</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input show_uo_imgs" id="images1"  datatype="*" placeholder="请上传封面" readonly>
                                <input type="hidden" name="audio_cover">
                                <a class="button bg-blue button-small " data="images1" id="image_upload1" preview="image_preview1" href="javascript:;" ><span class="icon-upload"> 上传</span></a>
                                <a class="button bg-blue button-small icon-picture-o" id="image_preview1" href="javascript:;" > 预览</a>
                                <div class="input-note">请上传封面，尺寸为600x600</div>
                            </div>
                        </div>

                        <!-- 封面图片 -->
                        <div class="form-group">
                            <div class="label">
                                <label>音频包头图</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input show_uo_imgs" id="images2" datatype="*" placeholder="请上传头图" readonly>
                                <input type="hidden" name="audio_banner">
                                <a class="button bg-blue button-small " data="images2" id="image_upload2" preview="image_preview2" href="javascript:;" ><span class="icon-upload"> 上传</span></a>
                                <a class="button bg-blue button-small icon-picture-o" id="image_preview2" href="javascript:;" > 预览</a>
                                <div class="input-note">请上传头图，尺寸为960x540</div>
                            </div>
                        </div>

                         <div class="form-group">
                            <div class="label">
                                <label>收费音频</label>
                            </div>
                            <div class="field">
                                <textarea type="text" class="input payaudiolist" style="width: 500px; height: 80px;" id="audiolist" name="payaudiolist" size="60" datatype="*" placeholder="音频列表" autocomplete="off"></textarea>
                                <button class="button viewfile_payment" style="vertical-align: top; width: 100px; height: 80px;" >文件预览</button>
                                <div class="clearfix paylist checkbox"></div>
                                <div class="clearfix paynote checkbox"></div>
                                <div class="input-note">请输入音频列表 id,id,id,id</div>
                            </div>
                        </div>

                    </div>

                    <div class="tab-panel" id="tab-4">

                        <div class="form-group">
                            <div class="label">
                                <label>电子书</label>
                            </div>
                            <div class="field">
                                <textarea type="text" class="input ebook ebooktxt" style="width: 500px; height: 80px;" id="ebook" name="ebook" size="60"  placeholder="音频列表" autocomplete="off"></textarea>
                                <button class="button ebookview" style="vertical-align: top; width: 100px; height: 80px;" >文件预览</button>(点击文件预览，设置电子书冰点价格)
                                <div class="ebooklist" id="show_ebook_box" style="float:none;" ></div>
                                <div class="clearfix ebooknote checkbox"></div>
                                <div class="input-note">请输入电子书列表 id,id,id,id</div>
                            </div>
                        </div>

                    </div>



                </div>

                <div class="panel-foot pfcont">

                        <div class="form-button footablist" id="footab-1" >
                            <a class="button bg-main nextab" n="3" style="cursor:pointer;">下一步</a>

                        </div>



                        <div class="form-button footablist" id="footab-3" style="display:none;">
                            <a class="button bg-main nextab" n="1"  style="cursor:pointer;">上一步</a>
                            <a class="button bg-main nextab" n="4"  style="cursor:pointer;">下一步</a>
                        </div>

                       <div class="form-button footablist" id="footab-4" style="display:none;">
                            <div class="newtipslist" id="tips"></div>
                            <a class="button bg-main nextab" n="3"  style="cursor:pointer;">上一步</a>
                            <button class="button bg-main submitBtn saveBtn" type="submit">保存</button>
                            <button class="button bg-main submitBtn otherSubmit" n="4"  style="cursor:pointer;"  >保存并上架</button>
                            <button class="button bg submitBtn" type="reset" >重置</button>
                        </div>

                    </div>



            </div>
        </div>
    </form>
</div>




<script  type="text/javascript">
    Do.ready('base', function () {

        $('#form').duxFormPage();
        duxConfig.upDir = '';
        $('#image_upload').duxFileUpload({
            uploadUrl: '/audiotopic/upload',
            type: 'jpeg,jpg,png',
            complete: function (data) {
                $('.show_uo_imgs').eq(0).val(data.host + '/' + data.path);
                $(':input[name="icon"]').val(data.path);
            }
        });






        //收费音频预览
        $('.viewfile_payment').click(function(){
            audiolist = $('.payaudiolist').val();
            if(audiolist){
                $('.paylist').children('label').remove();
                $.ajax({
                    url: '/audiotopic/audiolist',
                    type: 'POST',
                    dataType: 'json',
                    data: {audiolist: audiolist},
                    success: function(data){
                        if(data.status == 'error'){
                            alert(data.code);
                            $('.payaudiolist').val('');
                            return false;
                        }
                        loadlist(data.data, 'paylist','.paynote','payaudiolist');
                    }
                });
            }
            return false;
        });



        //电子书列表预览
        $('.ebookview').click(function(){
            var ebooklist = $('.ebook').val();
            if ("" != ebooklist){
                if (contains(ebooklist, "，", true)){
                    alert("不能含有中文逗号，请使用英文逗号");return false;
                }
            }
            if(ebooklist){
                $('.ebooklist').html('');//children('label').remove();
                $.ajax({
                    url: '/audiotopic/getEbookList',
                    type: 'POST',
                    dataType: 'json',
                    data: {ebooklist: ebooklist},
                    success: function(data){
                        if(data.status == 'error'){
                            alert(data.code);
                            return false;
                        }

                        var bookids = '';
                        var str = "<ul>";
                        $.each(data.data, function (i, item) {
                            var btype = (item.type=='1'?'全文':'干货');
                                bookids+=item.id+',';
                            //str+= "<li><img height=\"100\" src=\""+item.cover+"\"/><dl><span>"+item.title+"</span><dd>"+btype+"</dd><dd>"+item.author+"</dd><input name=\"bookprice[]\" value=\""+item.price+"\" /></dl></li>";
                            str += '<li>' + '<div class="p-l"><img src="' + item.cover +
                            '" alt="" width="80" /></div>' +
                            '<div class="p-l width">' +
                            '<span><b>' + item.title + '</b></span>' + "\n" +
                            '<span><b>' + btype + '</b></span>' + "\n" +

                            '<span>' + item.author + '</span>' + "\n" +
                            '<span>￥<input name="bookprice[]" value="'+item.price+'" /></span></div></li>' + "\n";

                        });
                        str+="</ul>";
                        $('.ebooklist').append(str);
                        var bids = bookids.substr(0,bookids.length-1);
                        $('.ebooktxt').val(bids);
                        //ebooklist(data.data, 'ebooklist','.ebooknote');
                    }
                });
            }
            return false;
        });



    });


//   function ebooklist(data, dom,note){
//        var str = "<ul>";
//        $.each(data, function (i, item) {
//            var btype = (item.type=='1'?'全文':'干货');
//            str+= "<li><img src=\""+item.cover+"\"/><dl><span>"+item.title+"</span><dd>"+btype+"</dd><dd>"+item.author+"</dd><input name=\"price"+i+"\" value=\""+item.price+"\" /></dl></li>";
//        });
//        str+="</ul>";
//        $('.' + dom).append(str);
//    }


    function loadlist(data, dom,note,audio_input_class){
        var str = "";
        var atime = 0;
        var ids = '';
        $.each(data, function (i, item) {
            ids += item.id+',';
            str += appendAudio(item);
            atime += parseInt(item.duration);
        });
        ids =ids.substring(0,ids.length-1);
        $('.'+audio_input_class).val(ids);
        $('.' + dom).append(str);
         $(note).html( '共'+data.length+'个音频文件，累计时长：'+formatSeconds(atime) );
    }
    function appendAudio(item){
        var str = "";
        str +=  "  <label class=\"button active\" style=\"margin: 0 5px 5px 0;  float: left;  position: relative;  font-weight: normal;\">";
        str +=  "  <input name=\"aid[]\" value=\""+item.id+"\" type=\"checkbox\" checked=\"checked\">";
        str +=  "  "+item.title+" ";
        str +=  "   </label>";
        return str;
    }

     function formatSeconds(value) {
        var theTime = parseInt(value);// 秒
        var theTime1 = 0;// 分
        var theTime2 = 0;// 小时
        if(theTime > 60) {
           theTime1 = parseInt(theTime/60);
           theTime = parseInt(theTime%60);
           if(theTime1 > 60) {
              theTime2 = parseInt(theTime1/60);
              theTime1 = parseInt(theTime1%60);
            }
        }
        var result = ""+parseInt(theTime)+"秒";
        if(theTime1 > 0) {
            result = ""+parseInt(theTime1)+"分"+result;
        }
        if(theTime2 > 0) {
            result = ""+parseInt(theTime2)+"小时"+result;
        }
        return result;
   }


  $('.checkDailyRecord').on('click',function(){
      var topicDate = $('#datetime').val();
          if(topicDate == '' || topicDate == null){
            alert('请填写排期日期');return false;
          }
          checkPayRecord(topicDate);
      return;

  });

  function checkPayRecord(topicDate){
      $.ajax({
              type: 'POST',
              url: '/audiotopic/checkPayTypeRecord',
              data:{dtime:topicDate,topictype:1},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                  if(data.status == 'ok'){
                      $('#paychecknote').hide();
                      alert('没有当天的日常排期记录,可以添加排期');
                  }else{
                      alert('当天的日常排期已存在，不能重复！');
                      $('#paychecknote').show();
                  }



              },
              error:function(xhr,type){
                  alert('请求失败！');
              }
           });
  }


   function contains(str, subStr, isIgnoreCase) {

    if (isIgnoreCase) {
        // 忽略大小写
        str = str.toLowerCase();
        subStr = subStr.toLowerCase();
    }

    var startChar = subStr.substring(0,1);
    var strLen = subStr.length;

    for (var j=0; j<str.length-strLen+1; j++) {
        if (str.charAt(j) == startChar) {
            /* 如果匹配起始字符,开始查找 */
            if (str.substring(j, j+strLen) == subStr) {
                /*如果从j开始的字符与 str 匹配 */
                return true;
            }
        }
    }
    return false;
}


$('body').delegate('.nextab','click',function(){
    var n =  $(this).attr('n');
    $('#tabtn'+n).trigger("click");
});


$('body').delegate('.otherSubmit','click',function(){
    $('#statusBtn').val(2);
    //$('form').submit();
});

$('body').delegate('.saveBtn','click',function(){
    $('#statusBtn').val(1);
    //$('form').submit();
});


    // 用来控制是否已经触发了上传控件
    var bClicked = false;
    function upload() {

        if (bClicked) return;

        bClicked = true;

        $('#image_upload1').duxFileUpload({
            uploadUrl: '/audiotopic/upload',
            type: 'jpeg,jpg,png,gif',
            complete: function (data) {
                $('.show_uo_imgs').eq(1).val(data.host + '/' + data.path);
                $(':input[name="audio_cover"]').val(data.path);
            }
        });

        $('#image_upload2').duxFileUpload({
            uploadUrl: '/audiotopic/upload',
            type: 'jpeg,jpg,png,gif',
            complete: function (data) {
                $('.show_uo_imgs').eq(2).val(data.host + '/' + data.path);
                $(':input[name="audio_banner"]').val(data.path);
            }
        });
    }


</script>