<div class="dux-tools">
    <div class="bread-head">音频排期<span class="small">音频排期列表</span>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/audiotopic/add">添加音频排期</a></li>
            </ul>
        </div>
    </div>
</div>


<div class="admin-main">
    <div id="table">
        <div class="table-responsive">
           
            <?php if($pagger):?>
            <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
            <?=$pagger?>
            </div>
            <?php endif;?>
            
            <?php foreach ($list as $val):?>
            <div class="panel dux-box topic<?=$val['id']?> clearfix" style="margin-bottom:10px;">
                <div class="panel-head clearfix">
                    <div class="float-left button-group" style="line-height: 30px;">
                    名称：<?=$val['title']?> 　 上线：<?=$val['datetime']?> 　By：<?=$val['user']?>
                    </div>
                    <div class="float-right button-group">
                        <?php if($val['datetime'] > date("Y-m-d")):?>
                        <a class="button bg-blue button-small icon-pencil" href="/audiotopic/edit/id/<?=$val['id']?>" title="编辑"></a>
                        <a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" removeclass="topic<?=$val['id']?>" url="/audiotopic/delete" data="<?=$val['id']?>" title="删除"></a>
                        <?php endif;?>
                    </div>
                </div>
                <div class="panel-body"><span class="float-left">封面：</span><img src="<?=$val['icon']?>" height="200"></div>
                <div class="panel-body" style="height: auto; overflow: hidden;">
                    <span class="float-left">音频：</span>
                    <div class="float-left">
                        <textarea class="input-block audiolist" style="width: 600px; height: 80px; display: none;" readonly="readonly"><?=$val['audio']?></textarea>
                        <button class="viewfile" tid="<?=$val['id']?>" data="topic<?=$val['id']?>" style="vertical-align: top; width: 80px; height: 80px; display: none;">文件预览</button>
                        <div class="clearfix selectlist checkbox"></div>
                        <div class="clearfix selectnote checkbox">共0个音频文件，累计时长：0秒</div>
                    </div>
                </div>
            </div>
            <?php endforeach;?>
            
        </div>
        <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
        <?=$pagger?>
        </div>
        <?php endif;?>
    </div>
    <script>
    Do.ready('base', function () {
        $('#table').duxTable();
        
        $('.viewfile').click(function(){
            request = false;
            tablebox = $(this).attr('data');
            str = '.'+tablebox+' .audiolist';
            tid = $(this).attr('tid');
            audiolist = $(str).val();
            
            if(audiolist){
                $('.'+tablebox+' .selectlist').children('label').remove();
                $.ajax({
                    url: '/audiotopic/audiolist/act/list',
                    type: 'POST',
                    dataType: 'json',
                    async:false,
                    data: {audiolist: audiolist,tid:tid},
                    success: function(data){
                        request = true;
                        if(data.status == 'error'){
                            alert(data.code);
                            return false;
                        }
                        loadlist(data.data, '.'+tablebox+' .selectlist', '.'+tablebox+' .selectnote');

                    }
                });
            }
            return false;
        });
        $('.viewfile').each(function(){
            $(this).click();
        });

        function loadlist(data, dom, note){
            var str = "";
            var atime = 0;
            $.each(data, function (i, item) {
                str += appendAudio(item);
                atime += parseInt(item.duration);
            });
            $(dom).append(str);
            $(note).html( '共'+data.length+'个音频文件，累计时长：'+formatSeconds(atime) );
        }
        function appendAudio(item){
            var str = "";
            str +=  "  <label class=\"button active\" style=\"margin: 0 5px 5px 0;  float: left;  position: relative;  font-weight: normal;\">";
            //str +=  "  <input name=\"aid[]\" value=\""+item.id+"\" type=\"checkbox\" checked=\"checked\">";
            str +=  "  <span class=\"icon icon-check text-green\"></span>"+item.title+" ";
            str +=  "   </label>";
            return str;
        }
        
    });
    function formatSeconds(value) {
        var theTime = parseInt(value);// 秒
        var theTime1 = 0;// 分
        var theTime2 = 0;// 小时
        if(theTime > 60) {
           theTime1 = parseInt(theTime/60);
           theTime = parseInt(theTime%60);
           if(theTime1 > 60) {
              theTime2 = parseInt(theTime1/60);
              theTime1 = parseInt(theTime1%60);
            }
        }
        var result = ""+parseInt(theTime)+"秒";
        if(theTime1 > 0) {
            result = ""+parseInt(theTime1)+"分"+result;
        }
        if(theTime2 > 0) {
            result = ""+parseInt(theTime2)+"小时"+result;
        }
        return result;
   }
    </script>
</div>