<style>
    .boxBorder{
        border-radius:5px;
        overflow: auto;
        border:1px solid #eee;
        margin:10px;
    }
    
    .subBar_box{
        height: auto; overflow: hidden;
        margin:5px 0 0 10px;
        
    }
    
</style>
<div class="dux-tools">
    <div class="bread-head">日常包排期列表<span class="small"><a href="/audiotopic/listDailyPackage" class="bread-head button  <?php echo (empty($t))?('bg-red'):('bg-dot'); ?> " >全部排期</a>  <a class="button  <?php echo ($t == 2)?('bg-red'):('bg-dot'); ?>  bread-head" href="/audiotopic/listDailyPackage/t/2">免费音频排期</a> <a class="button  <?php echo ($t == 1)?('bg-red'):('bg-dot'); ?>  bread-head" href="/audiotopic/listDailyPackage/t/1">付费音频排期</a></span>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/audiotopic/addDailyPackage">添加日常包排期</a></li>
                <li><a href="/audiotopic/addPaidTopic">添加付费音频包排期</a></li>
            </ul>
        </div>
    </div>
</div>


<div class="admin-main">
    <div id="table">
        <div class="table-responsive">
           
            <?php if($pagger):?>
            <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
            <?=$pagger?>
            </div>
            <?php endif;?>
            
            <?php if(!empty($list)): 
                    foreach ($list as $lv): 
                      $val=$lv['2'];$payVal=$lv['0'];$bookval=$lv['1'];
                      $tid = $bookval['id'].$val['id'];
                      $title = $val['title']?$val['title']:$payVal['0']['title'];
                      $linetime = $val['datetime']?$val['datetime']:$payVal['0']['datetime'];
                      $tuser = $val['user']?$val['user']:$payVal['0']['user'];
                      $ticon = $val['icon'];
                      $status = $val['status'];
                      $statusTxt = ($status == 1)?'上架':'下架';
                      $st = ($status == 1)?1:2;
                      
            
            ?>
            <?php if((($t == 1) && isset($payVal) && is_array($payVal['0'])) || ($t != 1)): ?>
            
            <div class="panel dux-box topic<?=$val['id']?> clearfix" style="margin-bottom:10px;">               
                <div class="panel-head clearfix">
                    <div class="float-left button-group" style="line-height: 30px;">
                  <?php if(!empty($t)): ?>  名称：<?=$title;?>   &nbsp;&nbsp;   <?php endif; ?>
                  
                    计费类型：<?php if($t == 1): ?> 付费音频<?php endif; ?>日常包　&nbsp;&nbsp;    上线：<?=$linetime?>   　By：<?=$tuser?>
                   <!-- <span style="padding-left:20px;">排期状态：<span class="topic_status<?=$tid?>"><?=$statusTxt;?></span></span>-->
                    </div>
                    <?php if(isset($val) || isset($bookval)): ?>
                    <div class="float-right button-group">
                       
                        <?php if(($val['datetime'] > date("Y-m-d"))  || $showEdit):?>
                        <a style="margin-right:10px;" class="button bg-blue button-small icon-pencil" 
                           href="/audiotopic/ModifyDailyPackage/tid/<?=$val['id']?>-<?=$bookval['id']?>/d/<?=$linetime?>" 
                           title="编辑"></a>
                        <a  class="button bg-green button-small icon updateStatusBtn" href="javascript:;" removeclass="topic<?=$val['id']?>" 
                           url="/audiotopic/updateStatus/tid/<?=$val['id']?>-<?=$bookval['id']?>/type/1/d/<?=$linetime?>/st/" 
                           data="<?=$val['datetime']?>" tid="<?=$tid;?>"  st="<?=$st?>"
                           title="<?php echo $stitle = ($status == 1)?('下架'):('上架'); ?>"><?=$stitle?></a> 
                        <?php endif;?>
                    </div>
                    <?php endif;?>
                </div>
                <?php if(($t != 1) && isset($ticon)): ?>
                <div class="panel-body"><span class="float-left">封面：</span><img src="<?=$ticon?>" height="200"></div>
                <?php endif; ?>
                <?php if(!empty($val)): ?>
                <div class="boxBorder">
                    <div class="subBar_box">
                        <span class="float-left">
                            <b>免费音频:</b>
                            <span style="padding:0 10px 0 10px;">排期状态：<span class="topic_status<?=$val['id'];?>"><?php echo ($val['status']==1)?'上架':'下架'; ?></span></span>
                            
                        <span class="active" >
                                    <a  class="button bg-green button-small icon updateStatusBtn active" style="background:#2c7;" href="javascript:;" removeclass="topic<?=$val['id']?>" 
                                    url="/audiotopic/updateStatus/tid/<?=$val['id']?>/type/s/d/<?=$val['datetime']?>/st/" 
                                    data="<?=$val['datetime']?>" tid="<?=$val['id'];?>"  st="<?php echo ($val['status']== 1)?1:2;?>"
                                    title="<?php echo $st_title = ($val['status'] == 1)?('下架'):('上架'); ?>"><?=$st_title?>
                                     </a> 
                            <a target="_blank" class="button bg-green button-small icon  active" style="background:#2c7;"  href="/audiotopic/view/tid/<?=$val['id'];?>/class/<?=$val['class'];?>" >预览</a>
                        </span>
                        </span>
                    </div>
                    
                    <div class="panel-body" style="height: auto; overflow: hidden;">
                        <textarea class="input-block audiolist" style="width: 600px; height: 80px; display: none;" readonly="readonly"><?=$val['audio']?></textarea>
                        <button class="viewfile" tid="<?=$val['id']?>" data="topic<?=$val['id']?>" style="vertical-align: top; width: 80px; height: 80px; display: none;">文件预览</button>
                        <div class="clearfix selectlist checkbox"></div>
                        <div class="clearfix selectnote checkbox">共0个音频文件，累计时长：0秒</div>
                    </div>
                </div>
                <?php endif;?>
                
                
                 <?php if(isset($lv['0']) && !empty($payVal)): ?>
                <?php foreach($payVal as $pv): ?>
                <div class="boxBorder">
                   <?php if(isset($pv['id'])): ?>
                     <div class="subBar_box" >
                    <span class="float-left">
                        <b>付费音频：</b>
                        <span style="padding-right:10px;">排期id：<?=$pv['id']?></span>
                        <span style="padding:0 10px 0 10px;">
                            排期状态：<span class="topic_status<?=$pv['id'];?>"><?php echo ($pv['status']==1)?'上架':'下架'; ?></span>
                        </span>
                        
                        <?php if(($pv['datetime'] > date("Y-m-d"))  || $showEdit):?>
                            <span>
                                <a style="margin-right:10px;" class="button bg-blue button-small icon-pencil" 
                               href="/audiotopic/modifyPaidTopic/tid/<?=$pv['id']?>/d/<?=$pv['datetime'];?>" 
                               title="编辑">
                                </a>

                            </span>
                            
                        <?php endif;?>
                        <span class="active" >
                                <a  class="button bg-green button-small icon updateStatusBtn active" style="background:#2c7;" href="javascript:;" removeclass="topic<?=$pv['id']?>" 
                                url="/audiotopic/updateStatus/tid/<?=$pv['id']?>/type/s/d/<?=$pv['datetime']?>/st/" 
                                data="<?=$pv['datetime']?>" tid="<?=$pv['id'];?>"  st="<?php echo ($pv['status']== 1)?1:2;?>"
                                title="<?php echo $st_title = ($pv['status'] == 1)?('下架'):('上架'); ?>"><?=$st_title?>
                                 </a> 
                            <a target="_blank" class="button bg-green button-small icon  active" style="background:#2c7;"  href="/audiotopic/view/tid/<?=$pv['id'];?>/class/<?=$pv['class'];?>" >预览</a>
                        </span>
                    </span>
                     </div>
                    <?php endif; ?>
                    <div class="panel-body" style="height: auto; overflow: hidden;">
                        <textarea class="input-block pay_audiolist<?=$pv['id']?>" style="width: 600px; height: 80px; display: none;" readonly="readonly"><?=$pv['audio']?></textarea>
                        <button class="pay_viewfile" tid="<?=$pv['id']?>" data="pay_audiolist<?=$pv['id']?>" style="vertical-align: top; width: 80px; height: 80px; display: none;">文件预览</button>
                        <div class="clearfix pay_selectlist<?=$pv['id']?> checkbox">
                            
                        </div>
                        <?php if(isset($lv['0'])): ?>
                        <div class="clearfix pay_selectnote<?=$pv['id']?> checkbox">共0个音频文件，累计时长：0秒</div>
                        <?php endif; ?>
                    </div>
                </div>
                
                <?php endforeach; ?>
                <?php endif;?>
                
                <?php if(!empty($bookval['booklist'])): ?>
                <div class="boxBorder">
                   
                    <div class="subBar_box" >
                        <span class="float-left">
                            <b>电子书:</b>
                            <span style="padding-right:10px;">
                                排期状态：
                                <span class="topic_status<?=$bookval['id'];?>"><?php echo ($bookval['status']==1)?'上架':'下架'; ?></span>
                            </span>
                            <span class="active" >
                                   <a  class="button bg-green button-small icon updateStatusBtn active" style="background:#2c7;" href="javascript:;" removeclass="topic<?=$bookval['id']?>" 
                                   url="/audiotopic/updateStatus/tid/<?=$bookval['id']?>/type/s/d/<?=$bookval['datetime']?>/st/" 
                                   data="<?=$bookval['datetime']?>" tid="<?=$bookval['id'];?>"  st="<?php echo ($bookval['status']== 1)?1:2;?>"
                                   title="<?php echo $st_title = ($bookval['status'] == 1)?('下架'):('上架'); ?>"><?=$st_title?>
                                    </a> 
                           </span>
                        </span>
                    </div>
                    <div  class="float-left" id="show_ebook_box" style="width:auto;">
                        <ul>
                            <?php foreach ($bookval['booklist'] as $bv): ?>
                            <li><div class="p-l">
                            <img width="80" alt="" src="<?=$bv['cover']?>">
                            </div>
                            <div class="p-l width"><span><b><?=$bv['title']?></b></span>
                            <span><b><?php echo ($bv['type'] == 1)?('全文'):('干货'); ?></b></span>
                            <span><?=$bv['author']?></span>
                            <span>￥<?=$bv['price']?></span>
                            </div>
                            </li>
                            <?php endforeach;  ?>
                        </ul>
                       
                    </div>
                </div>
                <?php endif; ?>
            </div>
            <?php endif; ?>
            <?php endforeach; endif;?>
            
        </div>
        <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
        <?=$pagger?>
        </div>
        <?php endif;?>
    </div>
    <script>
        var t="<?=$t;?>";
    Do.ready('base', function () {
        $('#table').duxTable();
        
        $('.viewfile').click(function(){
            request = false;
            tablebox = $(this).attr('data');
            str = '.'+tablebox+' .audiolist';
            tid = $(this).attr('tid');
            audiolist = $(str).val();
            
            if(audiolist){
                $('.'+tablebox+' .selectlist').children('label').remove();
                $.ajax({
                    url: '/audiotopic/audiolist/act/list/t/'+t,
                    type: 'POST',
                    dataType: 'json',
                    async:false,
                    data: {audiolist: audiolist,tid:tid},
                    success: function(data){
                        request = true;
                        if(data.status == 'error'){
                            alert(data.code);
                            return false;
                        }
                        loadlist(data.data, '.'+tablebox+' .selectlist', '.'+tablebox+' .selectnote');

                    }
                });
            }
            return false;
        });
        
        
        //付费音频列表
        $('.pay_viewfile').click(function(){
            request = false;
            tablebox = $(this).attr('data');
            str = '.'+tablebox;
            tid = $(this).attr('tid');
            var listclass = '.pay_selectlist'+tid;
            var noteclass = '.pay_selectnote'+tid;
            audiolist = $(str).val();
            
            if(audiolist){
                $('.'+tablebox+' .selectlist').children('label').remove();
                $.ajax({
                    url: '/audiotopic/audiolist/act/list/t'+t,
                    type: 'POST',
                    dataType: 'json',
                    async:false,
                    data: {audiolist: audiolist,tid:tid},
                    success: function(data){
                        request = true;
                        if(data.status == 'error'){
                            alert(data.code);
                            return false;
                        }
                        loadlist(data.data, listclass, noteclass);

                    }
                });
            }
            return false;
        });
        
        
        //更新上下架
        $('.updateStatusBtn').click(function(){
           var _this = $(this);
           var url = $(this).attr('url');
           var tid = $(this).attr('tid');
           var title = $(this).attr('title');
           var newTitle = (title =='上架'?'下架':'上架');
           var st = $(this).attr('st');
           url+=st;
           st = (st == 1?2:1);
           
            if(confirm('确定'+title+'？')){
               
                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'json',
                    async:false,
                    data: {},
                    success: function(data){
                        
                        if(data.status == 1){
                            _this.html(newTitle);
                            $('.topic_status'+tid).html(title);
                            _this.attr('st',st);
                            _this.attr('title',newTitle);
                        }else{
                            alert(data.info);
                            return false;
                        }
                        

                    }
                });
            }
            return false;
        });
        
        
        
        
        //end 
        
        $('.pay_viewfile').each(function(){
            $(this).click();
        });
        
        $('.viewfile').each(function(){
            $(this).click();
        });

        function loadlist(data, dom, note){
            var str = "";
            var atime = 0;
            $.each(data, function (i, item) {
                str += appendAudio(item);
                atime += parseInt(item.duration);
            });
            $(dom).append(str);
            $(note).html( '共'+data.length+'个音频文件，累计时长：'+formatSeconds(atime) );
        }
        function appendAudio(item){
            var str = "";
            str +=  "  <label class=\"button active\" style=\"margin: 0 5px 5px 0;  float: left;  position: relative;  font-weight: normal;\">";
            //str +=  "  <input name=\"aid[]\" value=\""+item.id+"\" type=\"checkbox\" checked=\"checked\">";
            str +=  "  <span class=\"icon icon-check text-green\"></span>"+item.title+" ";
            str +=  "   </label>";
            return str;
        }
        
    });
    function formatSeconds(value) {
        var theTime = parseInt(value);// 秒
        var theTime1 = 0;// 分
        var theTime2 = 0;// 小时
        if(theTime > 60) {
           theTime1 = parseInt(theTime/60);
           theTime = parseInt(theTime%60);
           if(theTime1 > 60) {
              theTime2 = parseInt(theTime1/60);
              theTime1 = parseInt(theTime1%60);
            }
        }
        var result = ""+parseInt(theTime)+"秒";
        if(theTime1 > 0) {
            result = ""+parseInt(theTime1)+"分"+result;
        }
        if(theTime2 > 0) {
            result = ""+parseInt(theTime2)+"小时"+result;
        }
        return result;
   }
    </script>
</div>