<style>
    .boxBorder{
        border-radius:5px;
        overflow: auto;
        border:1px solid #eee;
        margin:10px;
    }
    
    .subBar_box{
        height: auto; overflow: hidden;
        margin:5px 0 0 10px;
        
    }
    
</style>
<div class="dux-tools">
    <div class="bread-head">日常包排期预览</div>
        
        
  <div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/audiotopic/addDailyPackage">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="panel-head">
                    <div class="tab-head">
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1" id="tabtn1" num="1" class="tablists "><?php echo ($topicInfo['class']==0)?'付':'免'; ?>费音频排期</a></li>
                        </ul>
                    </div>
                </div>
                <div class="tab-body boxBorder">



                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>排期名称</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['title'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <?php if($topicInfo['class'] == 2): ?>
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>排期封面</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><img src="<?=$topicInfo['icon'];?>"  height="200" /></span>                               
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>排期音频文件</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['audio'];?></span>                               
                            </div>
                        </div>
                        <div class="panel-body" style="height: auto; overflow: hidden;margin-left:150px;">
                            <textarea class="input-block pay_audiolist<?=$topicInfo['id']?>" style="width: 600px; height: 80px; display: none;" readonly="readonly"><?=$topicInfo['audio']?></textarea>
                            <button class="pay_viewfile" audio="<?=$topicInfo['audio']?>" tid="<?=$topicInfo['id']?>" data="<?=$topicInfo['audio']?>" style="vertical-align: top; width: 80px; height: 80px; display: none;">文件预览</button>
                            <div class="clearfix pay_selectlist<?=$topicInfo['id']?> checkbox"></div>
                            <div class="clearfix pay_selectnote<?=$topicInfo['id']?> checkbox">共0个音频文件，累计时长：0秒</div>
                        </div>
                        
                        
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>排期音频时长</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['duration'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>排期类型</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?php echo ($topicInfo['type']==1)?'日常包':'主题包' ;?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>音频类型</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?php echo ($topicInfo['class']==2)?'免费音频':'付费音频'; ?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>排期上线时间</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['datetime'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>排期状态</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?php echo ($topicInfo['status']==1)?'上架':'库存'; ?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    
                    
                    <?php if($topicInfo['class'] == 0){?>
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>音频价格</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['audio_price'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>购买音频赠送学分</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['audio_points'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>付费音频包封面图</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><img src="<?=$topicInfo['audio_icon'];?>"  height="200" /></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>付费音频包头图</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><img src="<?=$topicInfo['audio_banner'];?>"  height="200" /></span>                               
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>付费音频包的摘要</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['audio_summary'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>付费音频包标题</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['audio_title'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>付费音频包简介</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['audio_brife'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                   
                    <?php }elseif($topicInfo['class'] == 2){ ?>
                    
                    
                     <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>客户端推送标题</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['audio_title'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>客户端推送内容</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$topicInfo['audio_brife'];?></span>                               
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                    
                    
                    
                    
                    
                    
                    
                    
                </div>    
            </div>
        </div>
    </form>   
        
        
    </div>
</div>


<div class="admin-main">
    <div id="table">
        <div class="table-responsive">
           
           
            
        </div>
        
    </div>
    <script>
        var t="<?=$t;?>";
    Do.ready('base', function () {
        $('#table').duxTable();
        
        $('body').delegate('.audioplay','click',function(){
           aid = $(this).attr('data');
           var audio = document.getElementById('music'+aid);
           if(audio!==null){

                if(audio.paused){
                    pauseplay();
                    $(this).removeClass('icon-play').addClass('icon-pause');
                    audio.play();//audio.play();// 这个就是播放
                }else{
                    $(this).removeClass('icon-pause').addClass('icon-play');
                    audio.pause();// 这个就是暂停
                }
           }
       });
       function pauseplay(){
           $('.audioplay').each(function(){
                var aid = $(this).attr('data');
                var al = document.getElementById('music'+aid);
                if(al!==null){
                   if(al.paused){

                    }else{
                        $(this).removeClass('icon-pause').addClass('icon-play');
                        al.pause();// 这个就是暂停
                    }
                }
           });
       }
        
        
        
        
        
        
        $('.viewfile').click(function(){
            request = false;
            tablebox = $(this).attr('data');
            str = '.'+tablebox+' .audiolist';
            tid = $(this).attr('tid');
            audiolist = $(str).val();
            
            if(audiolist){
                $('.'+tablebox+' .selectlist').children('label').remove();
                $.ajax({
                    url: '/audiotopic/audiolist/act/list/play/1/t/'+t,
                    type: 'POST',
                    dataType: 'json',
                    async:false,
                    data: {audiolist: audiolist,tid:tid},
                    success: function(data){
                        request = true;
                        if(data.status == 'error'){
                            alert(data.code);
                            return false;
                        }
                        loadlist(data.data, '.'+tablebox+' .selectlist', '.'+tablebox+' .selectnote');

                    }
                });
            }
            return false;
        });
        
        
        //付费音频列表
        $('.pay_viewfile').click(function(){
           var request = false;
            var tablebox = $(this).attr('data');
           var str = '.'+tablebox;
           var tid = $(this).attr('tid');
            var listclass = '.pay_selectlist'+tid;
            var noteclass = '.pay_selectnote'+tid;
            var audiolist = $(this).attr('audio');
            
            if(audiolist){
                $('.'+tablebox+' .selectlist').children('label').remove();
                $.ajax({
                    url: '/audiotopic/audiolist/act/list/play/1/t'+t,
                    type: 'POST',
                    dataType: 'json',
                    async:false,
                    data: {audiolist: audiolist,tid:tid},
                    success: function(data){
                        request = true;
                        if(data.status == 'error'){
                            alert(data.code);
                            return false;
                        }
                        loadlist(data.data, listclass, noteclass);

                    }
                });
            }
            return false;
        });
        
        
        //更新上下架
        $('.updateStatusBtn').click(function(){
           var _this = $(this);
           var url = $(this).attr('url');
           var tid = $(this).attr('tid');
           var title = $(this).attr('title');
           var newTitle = (title =='上架'?'下架':'上架');
           var st = $(this).attr('st');
           url+=st;
           st = (st == 1?2:1);
           
            if(confirm('确定'+title+'？')){
               
                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'json',
                    async:false,
                    data: {},
                    success: function(data){
                        
                        if(data.status == 1){
                            _this.html(newTitle);
                            $('.topic_status'+tid).html(title);
                            _this.attr('st',st);
                            _this.attr('title',newTitle);
                        }else{
                            alert(data.info);
                            return false;
                        }
                        

                    }
                });
            }
            return false;
        });
        
        
        
        
        //end 
        
        $('.pay_viewfile').each(function(){
            $(this).click();
        });
        
        $('.viewfile').each(function(){
            $(this).click();
        });

        function loadlist(data, dom, note){
            var str = "";
            var atime = 0;
            
            $.each(data, function (i, item) {               
                str += appendAudio(item);
                atime += parseInt(item.duration);
                
            });
            $(dom).append(str);
            $(note).html( '共'+data.length+'个音频文件，累计时长：'+formatSeconds(atime) );
        }
        function appendAudio(item){
            var str = "";
            var play = '';
            str +=  "  <label class=\"button active\" style=\"margin: 0 5px 5px 0;  float: left;  position: relative;  font-weight: normal;\">";
            //str +=  "  <input name=\"aid[]\" value=\""+item.id+"\" type=\"checkbox\" checked=\"checked\">";
            str +=  "  <span class=\"icon icon-check text-green\"></span>"+item.title+" ";
            
            play = '<i class="icon-play audioplay" data="'+item.id+'"></i>';
            play+= '<audio src="'+item.mp3_play_url+'" controls="false" id="music'+item.id+'" hidden>';
            str += play;
            str +=  "   </label>";
            return str;
        }
        
    });
    function formatSeconds(value) {
        var theTime = parseInt(value);// 秒
        var theTime1 = 0;// 分
        var theTime2 = 0;// 小时
        if(theTime > 60) {
           theTime1 = parseInt(theTime/60);
           theTime = parseInt(theTime%60);
           if(theTime1 > 60) {
              theTime2 = parseInt(theTime1/60);
              theTime1 = parseInt(theTime1%60);
            }
        }
        var result = ""+parseInt(theTime)+"秒";
        if(theTime1 > 0) {
            result = ""+parseInt(theTime1)+"分"+result;
        }
        if(theTime2 > 0) {
            result = ""+parseInt(theTime2)+"小时"+result;
        }
        return result;
   }
    </script>
</div>