<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<div class="dux-tools">
    <div class="bread-head">渠道数据统计</div>
</div>

<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET">
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        下单开始时间：<input type="text" id="d4321" class="input datebtn" style="width:220px;" id="datetime" name="start_time" value="<?=$start_time?>" onfocus="WdatePicker({startDate:'<?=date('Y-m-d',strtotime('-7 day'))?>',maxDate:'#F{$dp.$D(\'d4322\',{d:+0})}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="" autocomplete="off">
                    </div>&nbsp;
                    <div class="field">
                        下单结束时间：<input type="text" id="d4322" class="input datebtn" style="width:220px;" id="datetime" name="end_time"  value="<?=$end_time?>" onfocus="WdatePicker({maxDate:'<?=date('Y-m-d',strtotime('-1 day'))?>',minDate:'#F{$dp.$D(\'d4321\',{d:+0})}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="" autocomplete="off">
                    </div>&nbsp;
                    <div class="field">
                        渠道号: <input type="text" name="spm" class="input" value="<?=$spm?>" placeholder="">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="admin-main">
    <div class="line-big">
        <div class="xm3">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-red  icon-user"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=($overview['total_uv'])?:0?></strong></h2>
                            浏览UV
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm3">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-blue icon-key"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=($overview['total_pv'])?:0?></strong></h2>
                            浏览PV
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm3">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-green icon-share"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=($overview['total_order'])?:0?></strong></h2>
                            订单数量
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm3">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-yellow icon-link"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=($overview['total_amount'])?:0?></strong></h2>
                            订单金额
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
    </div>

    <div class="panel dux-box">
        <table id="table" class="table table-bordered">
            <tbody>
                <tr>
                    <th width="500">渠道名称</th>
                    <th width="*">渠道号</th>
                    <th width="*">订单数</th>
                    <th width="*">订单金额</th>
                    <th width="*">付款转化率</th>
                </tr>
                <?php if ($spmlist): foreach ($spmlist as $item) : ?>
                    <tr>
                        <td><a href="single?spm=<?=$item['spm']?>"><?=$item['name']?></a></td>
                        <td><?=$item['spm']?></td>
                        <td><?=$item['trans_num']?></td>
                        <td><?=$item['trans_amount']?></td>
                        <td><?=$item['rate'] ?>%</td>
                    </tr>
                <?php endforeach; endif;?>
            </tbody>
        </table>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>

<script type="text/javascript" charset="utf-8">
    Do.ready('base',function() {
        $('.js-time').duxTime();
    });
</script>