<div class="dux-tools">
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main" href="">商品列表</a>
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="post" action="/youzanshop/index" enctype="multipart/form-data">
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="keyword" size="20" value="<?=$keyword;?>" placeholder="关键词">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
                <div class="form-button">
                    <button class="button" type="button" name="excel" id="excel">导出</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
    <table id="table" class="table table-hover ">
        <tbody>
            <tr>
                <th width="100">编号</th>
                <th width="*">商品标题</th>
                <th width="*">商品数量</th>
                <th width="*">商品销量</th>
                <th width="*">商品价格</th>
            </tr>
            <?php if(!empty($data)):?>
            <?php foreach ($data as $key => $value):?>
            <tr>
                <td><?=$value['id'];?></td>
                <td><span><a href="<?=$value['share_url'];?>" target="_blank"/><?=$value['title'];?></span></td>
                <td><span class="tag bg-green"><?=$value['num'];?></span></td>
                <td><span class="tag bg-green"><?=$value['sold_num'];?></span></td>
                <td><span class="tag bg-green"><?=$value['price'];?></span></td>
            </tr>
            <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>
<div class="panel-foot table-foot clearfix">
    <div class="float-right">
        <?php echo $page;?>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    
    //导出
    $(document).ready(function(){
        $('#excel').click(function(){
            $.ajax({
                type:"POST", 
                url:"/youzanshop/index",
                data:{val:1},
                dataType:"json",
                success:function(msg){
                    alert(msg);
                }
            })
        })
    })
</script>

