<div class="dux-tools">
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main" href="">订单数据</a>
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="post" action="/youzanshop/orders" enctype="">
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="keyword" size="20" value="<?=$keyword;?>" placeholder="用户ID">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
    <table id="table" class="table table-hover ">
        <tbody>
            <tr>
                <th width="100">编号</th>
                <th width="*">订单号</th>
                <th width="*">商品名称</th>
                <th width="*">商品价格</th>
                <th width="*">交易类型</th>
                <th width="*">退款状态</th>
                <th width="*">微信粉丝ID</th>
                <th width="*">付款时间</th>
                <th width="*">交易维权状态</th>
                <th width="*">运费</th>
                <th width="*">支付类型</th>
            </tr>
            <?php if(!empty($data)):?>
            <?php foreach ($data as $key => $value):?>
            <tr>
                <td><?=$value['id'];?></td>
                <td><?=$value['outer_tid'];?></td>
                <td><?=$value['title'];?></td>
                <td><span class="tag bg-green"><?=$value['price'];?></span></td>
                <td><span class="tag bg-green"><?=$value['type'];?></span></td>
                <td><span class="tag bg-green"><?=$value['refund_state'];?></span></td>
                <td><span class="tag bg-green"><?=$value['weixin_user_id'];?></span></td>
                <td><span class="tag bg-green"><?=$value['pay_time'];?></span></td>
                <td><span class="tag bg-green"><?=$value['feedback'];?></span></td>
                <td><span class="tag bg-green"><?=$value['post_fee'];?></span></td>
                <td><span class="tag bg-green"><?=$value['pay_type'];?></span></td>
            </tr>
            <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>
<div class="panel-foot table-foot clearfix">
    <div class="float-right">
        <?php echo $page;?>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
</script>

