<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/admincenter/js/calendar/WdatePicker.js"></script>
<div class="dux-tools">
    <div class="tools-function clearfix">
        <div class="float-left">
            <!--<a class="button button-small bg-main" href="">微信粉丝用户</a>-->
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="post" action="/youzan/index" enctype="multipart/form-data">
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="keyword" size="20" value="<?=$keyword;?>" placeholder="关键词">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input datebtn" style="width:220px;" id="time_start" name="start_time" value="<?=$st;?>" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd- HH:mm:ss'})" style="cursor:pointer;" size="60" datatype="*" placeholder="用户关注开始时间" autocomplete="off">
                    </div>—
                    <div class="field">
                        <input type="text" class="input datebtn" style="width:220px;" id="time_end" name="end_time" value="<?=$et;?>" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd- HH:mm:ss'})" style="cursor:pointer;" size="60" datatype="*" placeholder="用户关注结束时间" autocomplete="off">
                    </div>
                </div><br>
                <div class="form-group">
                    <div class="field">
                        <input type="checkbox" name="user_id" value="">用户id
                        <input type="checkbox" name="open_id" value="">open_id
                        <input type="checkbox" name="nick" value="">昵称
                        <input type="checkbox" name="avatar" value="">用户头像
                        <input type="checkbox" name="follow_time" value="">关注时间
                        <input type="checkbox" name="sex" value="">性别
                        <input type="checkbox" name="province" value="">所属省份
                        <input type="checkbox" name="city" value="">所属城市
                        <input type="checkbox" name="tags" value="">粉丝标签
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="button" name="excel" id="excel">导出</button>
                </div>
                <div class="form-button">
                    <button class="button" type="submit" name="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
    <table id="table" class="table table-hover ">
        <tbody>
            <tr>
                <th width="100">编号</th>
                <th width="*">用户ID</th>
                <th width="*">昵称</th>
                <th width="*">头像</th>
                <th width="*">关注时间</th>
                <th width="*">性别</th>
                <th width="*">所在省份</th>
                <th width="*">所在城市</th>
            </tr>
            <?php if(!empty($data)):?>
            <?php foreach ($data as $key => $value):?>
            <tr>
                <td><?=$value['id'];?></td>
                <td><?=$value['user_id'];?></td>
                <td><span class="tag bg-green"><?=$value['nick'];?></span></td>
                <td><img src="<?=$value['avatar'];?>" width="110" height="40"></td>
                <td><span class="tag bg-green"><?=$value['follow_time'];?></span></td>
                <td><span class="tag bg-green"><?php if ($value['sex'] == 'm'){echo '男';}else{echo '女';}?></span></td>
                <td><span class="tag bg-green"><?=$value['province'];?></span></td>
                <td><span class="tag bg-green"><?=$value['city'];?></span></td>
            </tr>
            <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>
<div class="panel-foot table-foot clearfix">
    <div class="float-right">
        <?php echo $page;?>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    
    //导出
    $(document).ready(function(){
        $('#excel').click(function(){
            $.ajax({
                type:"POST", 
                url:"/youzan/index",
                data:{val:1},
                dataType:"json",
                success:function(msg){
                    alert(msg);
                }
            })
        });
    })
</script>

