<div class="dux-tools">
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main" href="">商品图片</a>
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="post" action="" enctype="">
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="keyword" size="20" value="<?=$keyword;?>" placeholder="关键字">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
    <table id="table" class="table table-hover ">
        <tbody>
            <tr>
                <th width="100">ID</th>
                <th width="*">商品ID</th>
                <th width="*">图片链接地址</th>
                <th width="*">缩略图地址</th>
                <th width="*">中号大小图链接地址</th>
                <th width="*">组合图片链接地址</th>
                <th width="*">创建时间</th>
            </tr>
            <?php if(!empty($data)):?>
            <?php foreach ($data as $key => $value):?>
            <tr>
                <td><?=$value['id'];?></td>
                <td><?=$value['num_iid'];?></td>
                <td><?=$value['url'];?></td>
                <td><img src="<?=$value['thumbnail'];?>" width="110" height="40"></td>
                <td><img src="<?=$value['medium'];?>" width="110" height="40"></td>
                <td><img src="<?=$value['combine'];?>" width="110" height="40"></span></td>
                <td><span class="tag bg-green"><?=$value['created'];?></span></td>
            </tr>
            <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>
<div class="panel-foot table-foot clearfix">
    <div class="float-right">
        <?php echo $page;?>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
</script>

