<div class="dux-tools">
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main" href="">有赞数据</a>
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="post" action="/youzanflow/index" enctype="multipart/form-data">
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="keyword" size="20" value="" placeholder="关键词">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                    <input type="file" class="button" name="import" />
                    <button class="button bg-main" type="submit">导入数据</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
    <table id="table" class="table table-hover ">
        <tbody>
            <tr>
                <th width="100">订单编号</th>
                <th width="*">买家会员名</th>
                <th width="*">商品名称</th>
                <th width="*">支付金额</th>
                <th width="*">手机号码</th>
            </tr>
            <?php if(!empty($data)):?>
            <?php foreach ($data as $key => $value):?>
            <tr>
                <td><?=$value['id'];?></td>
                <td><?=$value['vip_name'];?></td>
                <td><?=$value['title'];?></td>
                <td><?=$value['payment_amount'];?></td>
                <td><?=$value['contact_number'];?></td>
            </tr>
            <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>
<div class="panel-foot table-foot clearfix">
    <div class="float-right">
        <?php echo $page;?>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<?php if (!empty($i)):?>
    <?php echo "<script> alert('批量添加了'+$i+'条数据');</script>"; ?>
<?php endif;?>
<?php if ($notice == 1):?>
    <?php echo "<script> alert('请选择上传文件');</script>";?>
<?php endif; ?>
<script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
</script>

