<div class="dux-tools">
    <div class="bread-head">推荐广告位管理<span class="small">推荐广告位列表</span>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/advarea/add">添加广告</a></li>
            </ul>
        </div>
    </div>
</div>


<div class="admin-main">
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <div class="panel dux-box">

        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">ID</th>
                        <th width="*">文本</th>
                        <th width="*">连接</th>
                        <th width="*">图片</th>
                        <th width="*">分类</th>
                        <th width="*">状态</th>
                        <th width="*">排序</th>
                        <th width="*">操作</th>
                    </tr>
                    <?php if ($adv) : ?>
                        <?php foreach($adv as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                <td><?php echo $val['txt']; ?></td>
                                <td><?php echo $val['url']; ?></td>
                                <td><img src="<?php echo $val['img']; ?>" height="80"></td>
                                <td><?php if($val['class'] == 1): ?>电子书<?php else:?>音频排期<?php endif;?></td>
                                <td><?php if($val['status'] == 1): ?><span class="tag bg-green">启用</span><?php else: ?><span class="tag bg-gray">禁用</span><?php endif;?></td>
                                <td><?php echo $val['order']; ?></td>
                                <td>
                                    <a class="button bg-blue button-small icon-pencil" href="/advarea/edit/id/<?php echo $val['id']; ?>" title="编辑"></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
Do.ready('base', function () {
$('#table').duxTable();
});
</script>