<div class="dux-tools">
    <div class="bread-head">app更新包管理<span class="small">添加更新包</span>

        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/appmanage/list">app更新包列表</a>
        </div>

    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/appmanage/add">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <!-- tab head start-->
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>更新包配置</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">基本</a></li>
                        </ul>
                    </div>
                </div>
                <!-- tab head end -->

                <!-- table body start-->
                <div class="tab-body">

                    <!-- tab 1 start -->
                    <div class="tab-panel active" id="tab-1">

                        <!-- 更新包名称 -->
                        <div class="form-group">
                            <div class="label">
                                <label>名称 * </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="title" name="title" size="60" datatype="*" placeholder="名称">
                                <div class="input-note">请填更新包名称</div>
                            </div>
                        </div>


                        <!-- 更新包描述 -->
                        <div class="form-group">
                            <div class="label">
                                <label>更新描述 * </label>
                            </div>
                            <div class="field">
                                <textarea class="input" id="desc" name="desc" rows="3" cols="62" placeholder="更新描述"></textarea>
                                <div class="input-note">请填更新描述</div>
                            </div>
                        </div>

                        <!-- 更新包 -->
                        <div class="form-group">
                            <div class="label">
                                <label>更新包 * </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input show_uo_imgs" id="images1" name="package_key" datatype="*" placeholder="请上传更新包" readonly>
                                <a class="button bg-blue button-small " data="images1" id="image_upload1" preview="image_preview1" href="javascript:;" ><span class="icon-upload"> 上传</span></a>
                                <div class="input-note">请上传更新包</div>
                            </div>
                        </div>

                        <!-- 更新包状态 -->
                        <div class="form-group">
                            <div class="label">
                                <label>更新包状态 * </label>
                            </div>
                            <div class="field">
                                <div class="button-group radio">
                                    <label class="button">
                                        <input name="status" value="1" type="radio" datatype="*" />
                                        <span class="icon icon-check text-green"></span> 可用
                                    </label>

                                    <label class="button">
                                        <input name="status" value="2" type="radio" datatype="*" />
                                        <span class="icon icon-check text-green"></span> 不可用
                                    </label>

                                </div>
                            </div>
                        </div>

                        <!-- 更新包version -->
                        <div class="form-group">
                            <div class="label">
                                <label>版本 * </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="version" name="version" size="60" datatype="*" placeholder="版本">
                                <div class="input-note">请填更新包版本</div>
                            </div>
                        </div>

                        <!-- 类型 -->
                        <div class="form-group">
                            <div class="label">
                                <label>类型 * </label>
                            </div>
                            <div class="field">
                                <div class="button-group radio">
                                    <label class="button ">
                                        <input name="type" value="ANDROID" type="radio" datatype="*" />
                                        <span class="icon icon-check text-green"></span> ANDROID
                                    </label>

                                    <label class="button">
                                        <input name="type" value="IOS" type="radio" datatype="*" />
                                        <span class="icon icon-check text-green"></span> IOS
                                    </label>

                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- tab 1 end -->
                </div>
                <!-- table body end-->

                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


<script  type="text/javascript">

    Do.ready('base', function () {
        //表单综合处理
        duxConfig.upDir = '';
        $('#form').duxFormPage();

        $('#image_upload1').duxFileUpload({
            uploadUrl: '/appmanage/uploadToQN',
            type: 'apk, ipa',
            complete: function (data) {
                $('.show_uo_imgs').eq(0).val(data.savepath);
            }
        });

    });
</script>