<div class="dux-tools">
    <div class="bread-head">app更新包列表<span class="small">app更新包列表</span>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/appmanage/add">添加app更新包</a></li>
            </ul>
        </div>
    </div>
</div>


<div class="admin-main">
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <div class="panel dux-box">

        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">ID</th>
                        <th width="*">名称</th>
                        <th width="*">版本</th>
                        <th width="*">描述</th>
                        <th width="*">七牛key</th>
                        <th width="*">添加时间</th>
                        <th width="*">状态</th>
                        <th width="*">类型</th>
                        <th width="*">操作</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                <td><?php echo $val['title']; ?></td>
                                <td><?php echo $val['version']; ?></td>
                                <td><?php echo $val['desc']; ?></td>
                                <td><?php echo $val['package_key']; ?></td>
                                <td><?php echo $val['create_time']; ?></td>
                                <td><?php echo $val['status'] == 1 ? '<span class="tag bg-green">可用</span>' : '<span class="tag">不可用</span>'; ?></td>
                                <td><?php echo $val['type']; ?></td>
                                <td>
                                    <a class="button bg-blue button-small icon-pencil" href="/appmanage/edit/id/<?php echo $val['id']; ?>" title="编辑"></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
Do.ready('base', function () {
$('#table').duxTable();
});
</script>