<div class="dux-tools">
    <div class="bread-head">订单管理<span class="small">订单详情</span></div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="panel-head"><strong>订单详情</strong>
        </div>
        <div class="table-responsive">
            <table class="table">
                <tbody>
                    <tr>
                        <td width="250" align="right">订单ID：</td>
                        <td><?=$oinfo[order_id]?></td>
                    </tr>
                    <tr>
                        <td align="right">店铺ID</td>
                        <td><?=$oinfo[showcase_id]?></td>
                    </tr>
                    <tr>
                        <td align="right">商品总价：</td>
                        <td><?=$oinfo[total_fee]?></td>
                    </tr>
                    <tr>
                        <td align="right">优惠金额：</td>
                        <td><?=$oinfo[discount_fee]?></td>
                    </tr>
                    <tr>
                        <td align="right">实付金额：</td>
                        <td><?=$oinfo[payment_fee]?></td>
                    </tr>
                    <tr>
                        <td align="right">邮费：</td>
                        <td><?=$oinfo[post_fee]?></td>
                    </tr>
                        <td align="right">买家UID：</td>
                        <td><?=$oinfo[buyer_id]?></td>
                    </tr>
                    <tr>
                        <td align="right">收货地址</td>
                        <td><?=$oinfo[receiver_province]?><?=$oinfo[receiver_city]?><?=$oinfo[receiver_address]?></td>
                    </tr>
                    <tr>
                        <td align="right">邮政编码：</td>
                        <td><?=$oinfo[receiver_zip]?></td>
                    </tr>
                    <tr>
                        <td align="right">收货人姓名：</td>
                        <td><?=$oinfo[receiver_name]?></td>
                    </tr>
                    <tr>
                        <td align="right">收货人手机号：</td>
                        <td><?=$oinfo[receiver_mobile]?></td>
                    </tr>
                    <tr>
                        <td align="right">外部交易编号：</td>
                        <td><?=$oinfo[outer_tid]?></td>
                    </tr>
                    <tr>
                        <td align="right">跟踪页面来源(spm)：</td>
                        <td><?=$oinfo[spm]?></td>
                    </tr>
                    <tr>
                        <td align="right">订单状态：</td>
                        <td><?=$oinfo[state_name]?> - <?=$oinfo[state]?></td>
                    </tr>
                    <tr>
                        <td align="right">支付类型：</td>
                        <td><?=$oinfo[pay_type]?></td>
                    </tr>
                    <tr>
                        <td align="right">付款时间：</td>
                        <td><?=$oinfo[pay_time]?></td>
                    </tr>
                    <tr>
                        <td align="right">退款时间：</td>
                        <td><?=$oinfo[refund_time]?></td>
                    </tr>
                    <tr>
                        <td align="right">发货时间：</td>
                        <td><?=$oinfo[shipping_time]?></td>
                    </tr>
                    <tr>
                        <td align="right">创建时间：</td>
                        <td><?=$oinfo[create_time]?></td>
                    </tr>
                    <tr>
                        <td align="right">更新时间：</td>
                        <td><?=$oinfo[update_time]?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <br>
    <div class="panel dux-box">
        <div class="panel-head"><strong>商品列表</strong></div>
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100" style="text-align: center;">商品ID</th>
                        <th width="*">商品标题</th>
                        <th width="*">商品主图</th>
                        <th width="*">SKU_ID</th>
                        <th width="*">SKU外部编码</th>
                        <th width="*">SKU详情</th>
                        <th width="*">购买数量</th>
                        <th width="*">商品售价</th>
                    </tr>
                    <?php if ($oinfo[order_detail]) : ?>
                        <?php foreach ($oinfo[order_detail] as $val) : ?>
                            <tr>
                                <td align="center"><a href="/store/product/info?id=<?php echo $val['pid']; ?>"><?php echo $val['pid']; ?></a></td>
                                <td><a href="/store/product/info?id=<?php echo $val['pid']; ?>"><?php echo $val['title'] ? : '--'; ?></a></td>
                                <td><img src="<?php echo $val['pic_path']; ?>" width="90px" height="90px" /></td>
                                <td><?php echo $val['sku_id']; ?></td>
                                <td><?php echo $val['outer_sku_id'] ? : '--'; ?></td>
                                <td><?php echo $val['sku_value'] ? :'--'; ?></td>
                                <td><?php echo $val['num']; ?></td>
                                <td><?php echo $val['price']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <br>
    <div class="panel dux-box">
        <div class="panel-head"><strong>交易流水列表</strong></div>
        <?php if($transaction_info): ?>
        <?php foreach($transaction_info as $val) : ?>
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                <tr>
                    <th width="*" style="text-align: center;">订单总额</th>
                    <th width="*">支付渠道</th>
                    <th width="*">订单状态</th>
                    <th width="*">可退金额</th>
                    <th width="*">已退金额</th>
                    <th width="*">退款中金额</th>
                    <th width="*">创建时间</th>
                </tr>
                <tr>
                    <td align="center"><?php echo $val['order_total']; ?></td>
                    <td><?php echo $val['channel']; ?></td>
                    <td><?php echo $order_status[$val['order_status']]; ?></td>
                    <td><?php echo $val['refund_available']; ?></td>
                    <td><?php echo $val['refunded_amount']; ?></td>
                    <td><?php echo $val['refunding_amount']; ?></td>
                    <td><?php echo date('Y-m-d H:i:s',strtotime($val['time_created'])); ?></td>
                </tr>
                <tr>
                    <th width="*" style="text-align: center;">平台流水号</th>
                    <th width="*">渠道流水号</th>
                    <th width="*">原外部交易号</th>
                    <th width="*">渠道</th>
                    <th width="*">交易种类</th>
                    <th width="*">交易金额</th>
                    <th width="*">交易状态</th>
                </tr>
                <?php foreach($val['transactions'] as $v) : ?>
                <tr>
                    <td align="center"><?php echo $v['transaction_no']; ?></td>
                    <td><?php echo $v['channel_transaction_no'] ? :'--'; ?></td>
                    <td><?php echo $v['original_transaction_no'] ? : '--'; ?></td>
                    <td><?php echo $v['channel']; ?></td>
                    <td><?php echo $transaction_category[$v['transaction_category']]; ?></td>
                    <td><?php echo $v['transaction_total']; ?></td>
                    <td><?php echo $v['transaction_status']; ?></td>
                </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>
        <?php endforeach;?>
        <?php else:?>
        <h3><font color="red">交易流水查询失败</font></h3>
        <?php endif;?>
    </div>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>