<div class="dux-tools">
    <div class="bread-head">订单管理<span class="small">订单列表</span></div><br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main" href="/store/order/index?order_status=">全部</a>
            <a class="button button-small bg-green" href="/store/order/index?order_status=WAIT_BUYER_PAY&showcase=<?=$showcase;?>&number=<?=$mobile;?>">待付款</a>
            <a class="button button-small bg-blue" href="/store/order/index?order_status=WAIT_SELLER_SEND_GOODS&showcase=<?=$showcase;?>&number=<?=$mobile;?>">待发货</a>
            <a class="button button-small bg-red" href="/store/order/index?order_status=TRADE_BUYER_SIGNED&showcase=<?=$showcase;?>&number=<?=$mobile;?>">已签收</a>
            <a class="button button-small bg-dot" href="/store/order/index?order_status=TRADE_CLOSED&showcase=<?=$showcase;?>&number=<?=$mobile;?>">退款完成</a>
            <a class="button button-small bg-dot" href="/store/order/index?order_status=TRADE_CLOSED_BY_USER&showcase=<?=$showcase;?>&number=<?=$mobile;?>">已关闭</a>
            <a class="button button-small bg-gray" href="/store/order/index?order_status=WAIT_BUYER_CONFIRM_GOODS&showcase=<?=$showcase;?>&number=<?=$mobile;?>">待确认收货</a>
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/store/order/index" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="number" size="20" value="<?=$mobile?>" placeholder="手机号">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="order_no" size="20" value="<?=$order_no?>" placeholder="订单号">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="outer_tid" size="20" value="<?=$outer_tid?>" placeholder="交易单号">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="spm" size="20" value="<?=$spm?>" placeholder="分销spm编码">
                    </div>&nbsp;
                    <div class="field">
                        <select class="input js-assign" target="#tpl" name="showcase" datatype="*" id="parent">
                            <option value="<?=$showcase?>"><?php echo isset($showcase) ? $name[$showcase] : '请选择店铺';?></option>
                            <?php if ($idlist) : ?>
                                <?php foreach ($idlist as $key => $value) : ?>
                                    <option value="<?php echo $value['id']; ?>"><?php echo $value['name']; ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="*">订单号</th>
                        <th width="*">商品总价</th>
                        <th width="*">实付</th>
                        <th width="*">店铺名</th>
                        <th width="*">收货人姓名</th>
                        <th width="*">收货人地区</th>
                        <th width="*">订单状态</th>
                        <th width="*">付款时间</th>
                        <th width="*">支付方式</th>
                        <th width="*">订单创建时间</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $val) : ?>
                            <tr>
                                <td><a href="/store/order/info?id=<?=$val['order_id']?>&showcase_id=<?=$val['showcase_id']?>"><?php echo $val['order_id']; ?></a></td>
                                <td><?php echo $val['total_fee']; ?></td>
                                <td><?php echo $val['payment_fee']; ?></td>
                                <td><?php echo $name[$val['showcase_id']];?></td>
                                <td><?php echo $val['receiver_name'] ? :'--'; ?></td>
                                <td><?php echo $val['receiver_province'] ? : '--'; ?></td>
                                <?php
                                switch ($val['state']){
                                    case 'WAIT_BUYER_PAY':
                                        $bg = 'blue';
                                        break;
                                    case 'WAIT_SELLER_SEND_GOODS':
                                        $bg = 'green';
                                        break;
                                    case 'WAIT_BUYER_CONFIRM_GOODS':
                                        $bg = 'dot';
                                        break;
                                    case 'TRADE_BUYER_SIGNED':
                                        $bg = 'red';
                                        break;
                                    case 'TRADE_CLOSED':
                                        $bg = 'gray';
                                        break;
                                    case 'TRADE_CLOSED_BY_USER':
                                        $bg = 'gray';
                                        break;
                                }
                                
                                ?>
                                <td><span class="tag bg-<?=$bg?>"><?php echo $val['state_name']; ?></span></td>
                                <td><?php echo $val['pay_time']; ?></td>
                                <td><span class="tag bg-<?=$bg = $val['pay_type'] == 'WECHAT' ? 'blue' : 'green';?>"><?php echo $val['pay_type'] == 'WECHAT' ? '微信支付' : '京东支付'; ?></span></td>
                                <td><?php echo $val['create_time'];?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>