<div class="dux-tools">
    <div class="bread-head">系统<span class="small">redis监控</span></div>
</div>
    <div class="admin-main">
        <div class="panel dux-box">
            <div class="table-responsive">
                <table id="table" class="table table-hover ">
                    <tbody>
                    <tr>
                        <th width="200px">数据库</th>
                        <th width="*">内容</th>
                        <th width="*">备注</th>
                    </tr>
                            <tr>
                                <td>db0</td>
                                <td><?=$db0?></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>db1</td>
                                <td><?=$db1?></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>db2</td>
                                <td><?=$db2?></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>db3</td>
                                <td><?=$db3?></td>
                                <td></td>
                            </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="admin-main">
        <div class="panel dux-box">
            <div class="table-responsive">
                <table id="table" class="table table-hover ">
                    <tbody>
                    <tr>
                        <th width="200px">队列</th>
                        <th width="*">内容</th>
                    </tr>
                    <tr>
                        <td>store:task:main</td>
                        <td><?=$list_store_main?></td>
                    </tr>
                    <tr>
                        <td>store:task:logs</td>
                        <td><?=$list_store_logs?></td>
                    </tr>
                    <tr>
                        <td>store:task:sh5logs</td>
                        <td><?=$list_store_sh5logs?></td>
                    </tr>
                    <tr>
                        <td>store:task:ready:main</td>
                        <td><?=$list_store_ready_main?></td>
                    </tr>
                    <tr>
                        <td>store:task:ready:async</td>
                        <td><?=$list_store_ready_async?></td>
                    </tr>
                    <tr>
                        <td>store:task:ready:notify</td>
                        <td><?=$list_store_ready_notify?></td>
                    </tr>
                    <tr>
                        <td>store:task:ready:logs</td>
                        <td><?=$list_store_ready_logs?></td>
                    </tr>
                    <tr>
                        <td><a href="zset">store:task:delay:async</a></td>
                        <td><?=$list_store_dealy_async?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>