<script type="text/javascript" src="<?=ASSET_URL?>/static/lib/editor/ueditor.config.js"></script>
<script type="text/javascript" src="<?=ASSET_URL?>/static/lib/editor/ueditor.all.js"></script>
<link rel="stylesheet" type="text/css" href="<?=ASSET_URL?>/static/lib/editor/themes/default/css/ueditor.css" meta="screen">
<style>
    .link{cursor: pointer;color: blue;}
    .hidden{display:none;};
</style>
<?php echo Asset::getResource('promot.css', 'static/common');?>
<div class="dux-tools">
    <div class="bread-head">用户反馈列表<span class="small"></span>
        
    </div>

</div>


<div class="dux-tools">
    <div class="form-auto"> 
        
        <select  name="feedback_type" class="feedback_type input" >
            <option value="" <?php  if($type== false){ echo 'selected'; }?>>请选择</option>
            <option txt="正常" value="0" <?php  if(is_numeric($type) && ($type==0)){ echo 'selected'; }?>>正常</option>
            <option txt="已标记" value="1" <?php if($type==1){ echo 'selected'; }?>>标记</option>
            <option txt="已删除" value="2" <?php if($type==2){ echo 'selected'; }?>>删除</option>
            <option txt="处理中" value="3" <?php if($type==3){ echo 'selected'; }?>>处理中</option>
            <option txt="已解决" value="4" <?php if($type==4){ echo 'selected'; }?>>已解决</option>
        </select>
            <a class="searchbtn button button-small bg-blue" url = "/feedback/list/type/">查询</a>
        
    </div>
</div>
<!--
<div class="dux-tools">
    <div> <input name="kwd" type="text" id="kwd" placeholder="输入关键字" value="<?=$kwd?>" />  <a class="searchbtn button button-small bg-blue" url = "/feedback/list/kwd/">搜索</a></div>
</div>-->

<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th width="50%">内容</th>
                        <th>用户id</th>
                        <th>联系方式</th>
                        <th>时间</th>
                        <th>状态</th>
                    </tr>
                    <?php if ($alist) : ?>
                        <?php foreach($alist as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                <td width="50%"><?php echo $val['content']; ?></td>
                                <td><?php echo $val['user_id']; ?></td>
                                <td><?php echo $val['contact']; ?></td>
                                <td><?php echo $val['create_time']; ?></td>
                                <td>
<!--                                    <span class="statusname<?=$val['id'];?>"><?php echo $val['status']==0?'正常':($val['status']==1?'已标记':'已删除'); ?></span>-->
                                    <span>
                                        <select fid="<?=$val['id'];?>" name="status" class="statusbtn">
                                            <option txt="正常" value="0" <?php if($val['status']==0){ echo 'selected'; }?>>正常</option>
                                            <option txt="已标记" value="1" <?php if($val['status']==1){ echo 'selected'; }?>>标记</option>
                                            <option txt="已删除" value="2" <?php if($val['status']==2){ echo 'selected'; }?>>删除</option>
                                            <option txt="处理中" value="3" <?php if($val['status']==3){ echo 'selected'; }?>>处理中</option>
                                            <option txt="已解决" value="4" <?php if($val['status']==4){ echo 'selected'; }?>>已解决</option>
                                        </select>
                                        
<!--                                    <a txt="已标记" st="1"  fid="<?=$val['id'];?>" class="button bg-green button-small icon link upstatus <?php if($val['status']==1){echo 'hidden';} ?>">标记</a>
                                    <a txt="已删除" st="2"  fid="<?=$val['id'];?>" class="button bg-green button-small icon link upstatus <?php if($val['status']==2){echo 'hidden';} ?>">删除</a>
                                    <a txt="正常"  st="0"   fid="<?=$val['id'];?>" class="button bg-green button-small icon link upstatus <?php if($val['status']==0){echo 'hidden';} ?>">正常</a>
                                    <a txt="处理中"  st="3"   fid="<?=$val['id'];?>" class="button bg-green button-small icon link upstatus <?php if($val['status']==3){echo 'hidden';} ?>">处理</a>
                                    <a txt="已解决"  st="4"   fid="<?=$val['id'];?>" class="button bg-green button-small icon link upstatus <?php if($val['status']==4){echo 'hidden';} ?>">解决</a>
                                    -->
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </tbody>
            </table>
        </div>
        
        <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
        <?=$pagger?>
        </div>
        <?php endif;?>



    </div>



<script>
//search
$('.searchbtn').click(function(){
    var type = $('.feedback_type').val();
    var url = $(this).attr('url');
    url = url+type;
    window.location.href = url;
});

$('.statusbtn').change(function(){
    var _this = $(this),fid=_this.attr('fid'),st=_this.val();//txt=_this.attr('txt'),st=_this.attr('st'),_class=$('.upstatus')
    var url='/feedback/up/fid/'+fid+'/st/'+st;
    $.ajax({
              type: 'POST',
              url: url,
              data: {},
              dataType: 'json',
              timeout: 0,
              context:$('body'),
              success: function(data){
                  if(data.status == 1){
//                     $('.statusname'+fid).text(txt);
//                     
//                     _this.addClass('hidden');
//                     _this.siblings().removeClass('hidden');
                        alert('更新成功');
                  }else{
                      alert('更新失败');
                  }

              },
              error:function(xhr,type){
                  alert('请求错误！');
              }
           });
    
});

</script>
</div>