<div class="dux-tools">
    <div class="bread-head">客服后台管理                <span class="small">添加权限</span>
    </div>
    <br>
    <div class="tools-function clearfix">
        <div class="button-group float-right">
            <a class="button button-small bg-main icon-list" href="/kfadmin/getauthlist">
               权限列表 </a>
        </div>
    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/kfadmin/execauth">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>权限管理</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">添加权限</a></li>
                        </ul>
                    </div>
                </div>
                <div class="tab-body">
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>菜单名称</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="title_cn" name="title_cn" size="60" datatype="*" placeholder="菜单名字" autocomplete="off">
                                <div class="input-note">请填菜单名称</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>uri</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="title_en" name="title_en" size="60" datatype="*" placeholder="uri" autocomplete="off">
                                <div class="input-note">请填 uri</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>所属分类</label>
                            </div>
                            <div class="field">
                                <select class="input" name="id" id="id" >
                                    <option value="0" <?php if($id == 0):?>selected="selected"<?php endif;?>>作为顶级分类</option>
                                    <?php foreach ($list as $p_auth) : ?>
                                    <option value="<?=$p_auth['id']?>" <?php if($id == $p_auth['id']):?>selected="selected"<?php endif;?> ><?=$p_auth['title_cn']?></option>
                                    <?php endforeach;?>
                                </select>
                                <div class="input-note">请选择所属分类</div>
                            </div>
                            <input type="hidden" name="type" value="add">
                        </div>
                    </div>
                </div>

                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script  type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
    });
</script>