<div class="dux-tools">
    <div class="bread-head">后台角色管理<span class="small">角色列表</span>
        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/kfadmin/getuserlist">
                用户角色列表</a>
        </div>
    </div>
</div>

<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/kfadmin/adduser">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="panel-head">
                    <div class="tab-head">
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">添加用户</a></li>
                        </ul>
                    </div>
                </div>

                <div class="form-group">
                    <div class="label">
                        <label>账号</label>
                    </div>
                    <div class="field">
                        <input type="text" class="input" style="width:220px;" id="code" name="username" size="60"
                               datatype="*" placeholder="添加密码">
                        <div class="input-note">6-16位字符为字符</div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="label">
                        <label>密码</label>
                    </div>
                    <div class="field">
                        <input type="password" class="input" style="width:220px;" id="password" name="password" size="60"
                               datatype="*" placeholder="填写密码">
                        <div class="input-note">密码</div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="label">
                        <label>权限</label>
                    </div>
                    <div class="field">
                        <select class="input js-assign" target="#tpl" name="group" datatype="*" id="parent">
                            <option value="">请选择权限</option>
                            <?php if ($group_list) : ?>
                                <?php foreach ($group_list as $key => $value) : ?>
                                    <option value="<?php echo $value['id']; ?>"><?php echo $value['group']; ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                        <div class="input-note">请选择一个账号权限</div>
                    </div>
                </div>


                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>

            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
    });
</script>