<div class="dux-tools">
    <div class="bread-head">任务列表</div>
    <br>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/store/jobpool/showlist" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">Topic:
                        <input type="text" class="input" name="topic" size="20" value="<?=$topic?>" placeholder="">
                    </div>&nbsp;
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="150">Jobid</th>
                        <th width="50">Topic</th>
                        <th width="*">Params</th>
                        <th width="30">State</th>
                        <th width="30">Countdown</th>
                        <th width="150">CreateTime</th>
                        <th width="150">UpdateTime</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']?></td>
                                <td><?php echo $val['topic']; ?></td>
                                <td><?php echo $val['params'];?></td>
                                <td><?php echo $val['state'] ? :'--'; ?></td>
                                <td><?php echo $val['delay'] ? : '--'; ?></td>
                                <td><?php echo $val['ctime']; ?></td>
                                <td><?php echo $val['update_time']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>