<div class="dux-tools">
    <div class="bread-head">渠道管理<span class="small">添加渠道</span>
        <div class="float-right">
            <a class="button button-small bg-back icon-backward" href="/store/task/getlist">返回</a>
        </div>
    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/store/task/create" >
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="tab-body">
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>队列标识:</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="topic" name="topic" size="60" datatype="*1-14" errormsg="最多14个字符" value="" placeholder="">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>执行类:</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="topic" name="class" size="60" value="" placeholder="">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>执行方法:</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="topic" name="worker" size="60" datatype="*1-32" errormsg="最多14个字符" value="" placeholder="">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>任务参数:</label>
                            </div>
                            <div class="field">
                                <textarea type="text" class="input" style="width:400px;height: 200px" id="body" name="params" placeholder=""></textarea>
                            </div>
                        </div>
                        <div class="panel-foot">
                            <div class="form-button">
                                <div id="tips"></div>
                                <button class="button bg-main" type="submit">添加</button>
                                <button class="button bg" type="reset">重置</button>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </form>
</div>
<script  type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
    });
</script>