<div class="dux-tools">
    <div class="bread-head">任务列表</div>
    <br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-back icon-list" href="getlist"> 实时队列</a>
            <a class="button button-small bg-main icon-list" href="delaylist"> 延迟队列</a>
        </div>
        <div class="float-right">
            <a class="button button-small bg-main" href="/store/task/create">添加任务</a>
        </div>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                <tr>
                    <th width="*">Time</th>
                    <th width="*">Contents</th>
                    <th width="*">Countdown</th>
                </tr>
                <?php foreach($jobs as $job): ?>
                    <tr>
                        <td><?=$job['time']?></td>
                        <td><?=$job['body']?></td>
                        <td><?=$job['remain']?></td>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>