<div class="dux-tools">
    <div class="bread-head">任务列表</div>
    <br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main icon-list" href="getlist"> 实时队列</a>
            <a class="button button-small bg-back icon-list" href="delaylist"> 延迟队列</a>
        </div>
        <div class="float-right">
            <a class="button button-small bg-main" href="/store/task/create">添加任务</a>
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/store/task/getlist" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <select class="input js-assign" target="#tpl" name="topic" datatype="*" id="parent">
                            <option value="">请选择Topic</option>
                            <option value="main" <?=($search['topic'] == 'main') ? 'selected': ''?>>Main</option>
                            <option value="order" <?=($search['topic'] == 'order') ? 'selected': ''?>>Order</option>
                            <option value="notify" <?=($search['topic'] == 'notify') ? 'selected': ''?>>Notify</option>
                            <option value="others" <?=($search['topic'] == 'others') ? 'selected': ''?>>Others</option>
                        </select>
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="worker" size="20" value="<?=$search['worker']?>" placeholder="Worker">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="params" size="20" value="<?=$search['params']?>" placeholder="Params">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="memo" size="20" value="<?=$search['memo']?>" placeholder="Memo">
                    </div>&nbsp;
                    <div class="field">
                        <select class="input js-assign" target="#tpl" name="state" datatype="*" id="parent">
                            <option value="">all</option>
                            <option value="0" <?=($search['state'] == '0') ? 'selected': ''?>>ready</option>
                            <option value="1" <?=($search['state'] == '1') ? 'selected': ''?>>delay</option>
                            <option value="2" <?=($search['state'] == '2') ? 'selected': ''?>>reserved</option>
                            <option value="3" <?=($search['state'] == '3') ? 'selected': ''?>>deleted</option>
                        </select>
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <style>
                table{width:30em;table-layout:fixed;}
                td{width:100%;overflow:hidden;}
            </style>
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="80px">JobID</th>
                        <th width="60px">Topic</th>
                        <th width="90px">Worker</th>
                        <th width="*">Params</th>
                        <th width="70px">State</th>
                        <th width="*">Memo</th>
                        <th width="50px">Times</th>
                        <th width="70px">Timeuse</th>
                        <th width="160px">CreateTime</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $val) : ?>
                            <tr>
                                <td><?=$val['jobid']; ?></td>
                                <td><?=$val['topic']; ?></td>
                                <td><?=$val['worker']; ?></td>
                                <td><?=json_encode($val['params']);?></td>
                                <td><span class="tag <?=$val['state_bg']?>"> <?=$val['state'] ? :'--'; ?></span></td>
                                <td><?=$val['memo'] ? : '--'; ?></td>
                                <td align="center"><?=$val['times']; ?></td>
                                <td><?=$val['timeuse'] ? :'--'; ?></td>
                                <td><?=$val['ctime']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>