<div class="dux-tools">
    <div class="bread-head">队列管理<span class="small">队列列表</span></div>
    <div class="tools-function clearfix">
        <div class="float-right">
            <a class="button button-small bg-main" href="/store/task/create">添加任务</a>
        </div>
    </div>
    <br>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="*">编号</th>
                        <th width="*">队列名称</th>
                        <th width="*">任务ID</th>
                        <th width="*">Worker</th>
                        <th width="*">任务内容／任务参数</th>
                        <th width="*">状态</th>
                        <th width="*">备注</th>
                        <th width="*">耗时</th>
                        <th width="*">创建时间</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']?></td>
                                <td><?php echo $val['topic']; ?></td>
                                <td><?php echo $val['jobid']; ?></td>
                                <td><?php echo $val['worker']; ?></td>
                                <td><?php echo json_encode($val['params']);?></td>
                                <td><?php echo $val['state'] ? :'--'; ?></td>
                                <td><?php echo $val['memo'] ? : '--'; ?></td>
                                <td><?php echo $val['timeuse'] ? :'--'; ?></td>
                                <td><?php echo $val['ctime']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>