<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="renderer" content="webkit">
<title>罗辑思维CMS管理系统</title>
<?php echo Asset::getResource('pintuer.css', 'admincenter/common');?>
<?php echo Asset::getResource('admin.css', 'admincenter/lib');?>
<?php echo Asset::getResource('jquery.js', 'admincenter');?>
<?php echo Asset::getResource('pintuer.js', 'admincenter/common');?>
<?php echo Asset::getResource('respond.js', 'admincenter/common');?>
<script>
var duxConfig = {
	//基础配置
	baseDir : '<?=ASSET_URL?>/admincenter/js/',
	baseUrl : '<?=ASSET_URL?>/admincenter/',
	uploadUrl : "",
        upDir : '',
	//自定义配置
	libDir : '<?=ASSET_URL?>/admincenter/lib/js/',
	sessId  : '',
	editorUploadUrl : "",
	};
</script>
<?php echo Asset::getResource('do.js', 'admincenter');?>
<?php echo Asset::getResource('config.js', 'admincenter');?>
<?php echo Asset::getResource('definition.js', 'admincenter/lib');?>
<style>
	body {overflow-x:hidden; background-color: #eff3f6;}
</style>
</head>
<body>
    <?=$page?>
<script>
    Do.ready('base', function () {
        $('#table').duxTable();
        $('#form').duxForm();
    });
</script>
</body>
</html>