<div class="dux-tools">
    <div class="bread-head">商品管理<span class="small">商品列表</span></div><br>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/store/product/index" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <select class="input js-assign" target="#tpl" name="showcase_id" datatype="*" id="parent">
                            <option value="">请选择店铺</option>
                            <?php foreach ($showcase_list as $showcase) : ?>
                                <option value="<?=$showcase['showcase_id']?>" <?=($showcase_id == $showcase['showcase_id']) ? 'selected': ''?>><?php echo $showcase['name']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>&nbsp;
                    <div class="field">
                        <select class="input js-assign" target="#tpl" name="type" datatype="*" id="parent">
                            <option value="">全部</option>
                            <option value="0" <?=($type == '0') ? 'selected': ''?>>实物商品</option>
                            <option value="1" <?=($type == '1') ? 'selected': ''?>>虚拟商品</option>
                        </select>
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="pname" size="20" value="<?=$pname?>" placeholder="商品名">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="*">ID</th>
                        <th width="*">店铺名称</th>
                        <th width="*">商品名称</th>
                        <th width="*">价格</th>
                        <th width="*">销售量</th>
                        <th width="*">类型</th>
                        <th width="100">状态</th>
                        <th width="*">访问(uv/pv)</th>
                        <th width="*">修改时间</th>
                        <th width="*">发布时间</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['product_id']; ?></td>
                                <td><?php echo $val['showcase_name']; ?></td>
                                <td><a href="/store/product/info?id=<?php echo $val['product_id']; ?>"><?php echo $val['title']; ?><a><?=$val['presell'] ? '<span class="tag bg-red">预售<span>':''; ?></td>
                                <td><?php echo $val['price']; ?></td>
                                <td><?php echo $val['sold_num']; ?></td>
                                <td><?php echo $val['type_name'] ? :'--'; ?></td>
                                <td><span class="tag bg-<?=$val['onsell'] == 1 ? 'green':'red'; ?>"><?=$val['onsell_name'] ? :'--'; ?></span></td>
                                <td><?=$val['uv'].' / '.$val['pv']; ?></td>
                                <td><?php echo $val['update_time']; ?></td>
                                <td><?php echo $val['create_time']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
    </script>
</div>