<div class="dux-tools">
    <div class="bread-head">渠道管理<span class="small">添加渠道</span>
        <div class="float-right">
            <a class="button button-small bg-back icon-backward" href="/store/channel/showlist">返回</a>
        </div>
    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/store/channel/add" >
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="tab-body">
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>名称:</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="name" name="name" size="60" value="" placeholder="">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>来源:</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="desc" name="desc" size="60" value="" placeholder="">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>渠道号:</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="spm" name="spm" size="60" placeholder="渠道号不足8位将自动补足">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>通知邮箱:</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="email" name="email" size="60" placeholder="不填写则不发送邮件通知">
                            </div>
                        </div>
                        <div class="panel-foot">
                            <div class="form-button">
                                <div id="tips"></div>
                                <button class="button bg-main" type="submit">添加</button>
                                <button class="button bg" type="reset">重置</button>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </form>
</div>
<script  type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
    });
</script>