<div class="dux-tools">
    <div class="bread-head">渠道管理
        <div class="float-right">
            <a class="button button-small bg-back icon-backward" href="/store/channel/showlist">返回</a>
        </div>
    </div>
</div>
<div class="admin-main">
    <div class="tab dux-tab">
    <div class="panel dux-box  active">
        <form method="post" class="form-x dux-form form-auto" id="form" action="/store/channel/update" >
            <div class="tab dux-tab">
                <div class="panel dux-box  active">
                    <div class="panel-head">
                        <h4>修改渠道信息</h4>
                    </div>
                    <div class="tab-body">
                        <div class="tab-panel active" id="tab-1">
                            <input type="text" class="hidden" name="id" value="<?=$channel['id']?>">
                            <div class="form-group">
                                <div class="label">
                                    <label>渠道号:</label>
                                </div>
                                <div class="field">
                                    <input type="text" class="input" disabled style="width:220px;" id="name" name="name" size="60" value="<?=$channel['spm']?>" placeholder="">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="label">
                                    <label>名称:</label>
                                </div>
                                <div class="field">
                                    <input type="text" class="input" style="width:220px;" id="name" name="name" size="60" datatype="*1-14" errormsg="最多14个字符" value="<?=$channel['name']?>" placeholder="">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="label">
                                    <label>来源:</label>
                                </div>
                                <div class="field">
                                    <input type="text" class="input" style="width:220px;" id="desc" name="desc" size="60" value="<?=$channel['desc']?>" placeholder="">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="label">
                                    <label>邮箱:</label>
                                </div>
                                <div class="field">
                                    <input type="text" class="input" style="width:220px;" id="email" name="email" size="60" value="<?=$channel['email']?>" placeholder="">
                                </div>
                            </div>
                            <div class="channel panel-foot">
                                <div class="form-button">
                                    <div id="tips"></div>
                                    <button class="button bg-main" type="submit">保存</button>
                                    <?php if($channel['state'] == 0):?>
                                        <a href="javascript:;" url="/store/channel/disable" data="<?=$channel['id'];?>" success="location.reload();" title="停用" class="button bg-red float-right js-action">停用</a>
                                    <?php else: ?>
                                        <a href="javascript:;" url="/store/channel/enable" data="<?=$channel['id'];?>" success="location.reload();" title="恢复" class="button bg-green float-right js-action">恢复</a>
                                    <?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    </div>
</div>
<div class="admin-main">
    <div class="tab dux-tab">
        <div class="panel dux-box  active">
            <div class="panel-head">
                <h4>删除渠道</h4>
            </div>
            <div class="channel panel-body">
                <h3>此操作将删除该渠道,请谨慎操作!</h3>
                <div style="margin-top: 20px;">
                    <a href="javascript:;" url="/store/channel/delete" data="<?=$channel['id'];?>" success="location.replace('/store/channel/showlist');" title="删除" class="button bg-red js-action">删除渠道</a>
                </div>
        </div>
    </div>
</div>


<script  type="text/javascript">
    Do.ready('base', function () {
        //表单综合处理
        $('#form').duxFormPage();
        $('.channel').duxTable();
    });
</script>