<div class="dux-tools">
    <div class="bread-head">渠道管理<span class="small">渠道列表</span>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET" action="/store/channel/showlist" >
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" name="name" size="20" value="<?=$search['name']?>" placeholder="渠道名称">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" name="desc" size="20" value="<?=$search['desc']?>" placeholder="来源">
                    </div>&nbsp;
                    <div class="field">
                        <input type="text" class="input" name="spm" size="20" value="<?=$search['spm']?>" placeholder="渠道号">
                    </div>&nbsp;
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
    <div class="button-group float-right">
        <a href="/store/channel/add" class="button button-small bg-blue icon-plus dropdown-toggle"> 添加渠道 </a>
    </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="80">渠道ID</th>
                        <th width="100">渠道号</th>
                        <th width="*">名称</th>
                        <th width="*">来源</th>
                        <th width="*">添加时间</th>
                        <th width="*">操作</th>
                    </tr>
                    <?php if ($list) : ?>
                        <?php foreach ($list as $val) : ?>
                            <tr>
                                <td><?php echo $val['id']; ?></td>
                                <td><?php echo $val['spm']; ?></td>
                                <td><?php echo $val['name']; ?></td>
                                <td><?php echo $val['desc']; ?></td>
                                <td><?php echo $val['ctime']; ?></td>
                                <td><a href="/store/channel/edit?id=<?=$val['id']; ?>">编辑</a> | <a href="/store/statcenter/channel?spm=<?=$val['spm']; ?>">查看销量</a></td>
                                </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <script>
        Do.ready('base', function () {
        $('#table').duxTable();
        });
    </script>
</div>