<div class="dux-tools">
    <div class="bread-head">标签管理<span class="small">添加标签</span>

        <div class="float-right">
            <a class="button button-small bg-main icon-list" href="/tag/list">标签列表</a>
        </div>

    </div>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/tag/add">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <!-- tab head start-->
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>标签配置</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">添加标签</a></li>
                        </ul>
                    </div>
                </div>
                <!-- tab head end -->

                <!-- table body start-->
                 <div class="tab-body">

                    <!-- tab 1 start -->
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>Nav顶级分类ID</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="tag_top_id" name="tag_top_id" size="60" datatype="n" placeholder="Nav顶级分类ID">
                                <div class="input-note">请填写Nav顶级分类ID</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="label">
                                <label>标签名称</label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" id="tag_name" name="tag_name" size="60" datatype="*" placeholder="标签名称">
                                <div class="input-note">请填写标签名称</div>
                            </div>
                        </div>

                    </div>
                    <!-- tab 1 end -->

                 </div>
                <!-- table body end-->

                <div class="panel-foot">
                    <div class="form-button">
                        <div id="tips"></div>
                        <button class="button bg-main" type="submit">保存</button>
                        <button class="button bg" type="reset">重置</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>