<div class="dux-tools">
    <div class="bread-head">标签列表管理<span class="small">标签列表</span>
        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/tag/add">添加标签</a></li>
            </ul>
        </div>
    </div>
</div>


<div class="admin-main">
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
    <div class="panel dux-box">

        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">ID</th>
                        <th width="*">Nav 顶级分类ID</th>
                        <th width="*">标签名</th>
                        <th width="*">操作</th>
                    </tr>
                    <?php if ($tags) : ?>
                        <?php foreach($tags as $val) : ?>
                            <tr>
                                <td><?php echo $val['tag_id']; ?></td>
                                <td><?php echo $val['tag_top_id']; ?></td>
                                <td><?php echo $val['tag_name']; ?></td>
                                <td><a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/Tag/delete" data='{"id":<?php echo $val['tag_id']; ?>}' title="删除"></a></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
<script>
Do.ready('base', function () {
$('#table').duxTable();
});
</script>