<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/admincenter/js/calendar/WdatePicker.js"></script>
<div class="dux-tools">
    <div class="bread-head">中奖用户<span class="small">日榜中奖用户</span></div><br>
</div>
<div class="tools-function clearfix">
    <div class="float-left">&nbsp;
        <a class="button button-small bg-main icon-list" href="/Operate/winning/">总榜中奖用户</a>
    </div>
</div> 
<div class="admin-main">
<div class="panel dux-box">
   <div class="table-tools clearfix ">
       <div class="float-left">
<!--           <form method="get" action="/operate/oneday">
                <div class="form-inline">
                    <div class="form-group">
                        <div class="field">
                            <input type="text" class="input" id="keyword" name="kw" size="20" value="<?=$number?>" placeholder="搜索用户姓名/手机号">
                        </div>&nbsp;
                        <div class="field">
                            开始时间：<input type="text" id="d4321" class="input datebtn" style="width:220px;" id="datetime" name="time_start" value="<?=$time_start;?>" onfocus="WdatePicker({startDate:'Y-M-D 00:00:00',dateFmt:'yyyy-MM-dd HH:mm:ss'})" style="cursor:pointer;" size="60" >
                        </div>&nbsp;
                        <div class="field">
                            结束时间：<input type="text" id="d4322" class="input datebtn" style="width:220px;" id="datetime" name="time_end"  value="<?=$time_end;?>" onfocus="WdatePicker({startDate:'Y-M-D 00:00:00',dateFmt:'yyyy-MM-dd HH:mm:ss'})" style="cursor:pointer;" size="60" >
                        </div>
                    </div>&nbsp;&nbsp;
                    <div class="form-button">
                        <button class="button" type="submit">查询</button>
                    </div>
                </div>
            </form>-->
       </div>
    </div>
    <div class="table-responsive">
        <table id="table" class="table table-hover ">
            <tbody>
                <tr>
                    <th width="*">ID</th>
                    <th width="*">作品ID</th>
                    <th width="*">OPENID</th>
                    <th width="*">日榜排名</th>
                    <th width="*">真实姓名</th>
                    <th width="*">手机号</th>
                    <th width="*">微信昵称</th>
                    <th width="*">浏览数</th>
                    <th width="*">中奖日期</th>
                </tr>
        <?php if ($list) : ?>
            <?php foreach ($list as $key => $val) : ?>
                <tr>
                    <td><?=$val['id']?></td>
                    <td><?=$val['pid']?></td>
                    <td><?=$val['openid']?></td>
                    <td><?=$val['rank']?></td>
                    <td><?=$val['name']?></td>
                    <td><?=$val['phone']?></td>
                    <td><?=$val['nickname']?></td>
                    <td><?=$val['uv']?></td>
                    <td><?=$val['ctime']?></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>	
            </tbody>
        </table>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
</div>