<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/admincenter/js/calendar/WdatePicker.js"></script>
<div class="dux-tools">
    <div class="bread-head">用户作品<span class="small">用户作品</span></div><br>
</div>
<div class="admin-main">
<div class="panel dux-box">
   <div class="table-tools clearfix ">
       <div class="float-left">
           <form method="get" action="/operate/winning">
                <div class="form-inline">
                    <div class="form-group">
                        <div class="field">
                            <input type="text" class="input" id="keyword" name="kw" size="20" value="<?=$number?>" placeholder="搜索海报文字">
                        </div>&nbsp;
                        <div class="field">
                            开始时间：<input type="text" id="d4321" class="input datebtn" style="width:220px;" id="datetime" name="time_start" value="<?=$time_start;?>" onfocus="WdatePicker({startDate:'Y-M-D 00:00:00',dateFmt:'yyyy-MM-dd HH:mm:ss'})" style="cursor:pointer;" size="60" >
                        </div>&nbsp;
                        <div class="field">
                            结束时间：<input type="text" id="d4322" class="input datebtn" style="width:220px;" id="datetime" name="time_end"  value="<?=$time_end;?>" onfocus="WdatePicker({startDate:'Y-M-D 00:00:00',dateFmt:'yyyy-MM-dd HH:mm:ss'})" style="cursor:pointer;" size="60" >
                        </div>
                    </div>&nbsp;&nbsp;
                    <div class="form-button">
                        <button class="button" type="submit">查询</button>
                    </div>
                </div>
            </form>
       </div>
    </div>
    <div class="table-responsive">
        <table id="table" class="table table-hover ">
            <tbody>
                <tr>
                    <th width="*">ID</th>
                    <th width="*">OPENID</th>
                    <th width="*">原图地址</th>
                    <th width="*">海报文字</th>
                    <th width="*">海报地址</th>
                    <th width="*">浏览数</th>
                    <th width="*">海报主题</th>
                    <th width="*">操作</th>
                </tr>
        <?php if ($list) : ?>
            <?php foreach ($list as $key => $val) : ?>
                <tr>
                    <td><?=$val['id']?></td>
                    <td><?=$val['openid']?></td>
                    <td><?=$val['origin_img_url']?></td>
                    <td><?=$val['poster_text']?></td>
                    <td><img src="<?=$val['poster_img_url']?>" width="100" height="80" ></td>
                    <td><?=$val['page_view']?></td>
                    <td><?=$val['theme']?></td>
                    <td>
                        <?php if($val['delete'] == 1):?>
                            <a href="javascript:;" url="/operate/block" data='{"id":<?php echo $val['id']; ?>}' title="禁封" class="button bg-red button-small icon-lock js-action" success="location.reload()"></a>
                        <?php else:?>
                            <a href="javascript:;" url="/operate/unblock" data='{"id":<?php echo $val['id']; ?>}' title="解封" class="button bg-green button-small icon-unlock js-action" success="location.reload()"></a>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>	
            </tbody>
        </table>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
    <script type="text/javascript">
        Do.ready('base', function () {
        $('#table').duxTable();
        });
    
        $(function(){
            var x = 20;
            var y = 20;
            var sTop = 0;
            function showImg(sTop){
                $("a.tooltip").hover(function(){
                    if($("#newTip").length > 0 ){
                        $("#newTip").remove();
                    }
                    var $div = $("<div id='newTip'><img width='350' src='"+this.href+"'/></div>");
                    $("body").append($div);
                    $div.css({"position":"absolute","background":"silver"}).show("fast");
                },function(){
                    $("#newTip").remove();
                }).mousemove(function(e){
                    var smallImgH = $(this).offset().top;
                    var bigImgH = $("#newTip").height();
                    var windowH = $(window).height();
                    if(smallImgH - sTop -30 < windowH - bigImgH){
                        $("#newTip").css({"left":(e.pageX+x)+'px',"top":(e.pageY)+'px'}).show("fast");
                    }else if(smallImgH - sTop < bigImgH){
                        $("#newTip").css({"left":(e.pageX+x)+'px',"top":(e.pageY- bigImgH/2 - y)+'px'}).show("fast");
                    }else{
                        $("#newTip").css({"left":(e.pageX+x)+'px',"top":(e.pageY - bigImgH - y)+'px'}).show("fast");
                    }
                });
            }
        })
    </script>
</div>