<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<!-- ECharts单文件引入 -->
<script src="<?=ASSET_URL?>/static/lib/js/chart/echarts-all.js"></script>
<div class="dux-tools">
    <div class="bread-head">渠道数据统计 - <?=$channel_name?></div>
</div>

<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET">
<!--            <input type="hidden" name="spm" value="--><?//=$spm?><!--">-->
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        开始时间：<input type="text" id="d4321" class="input datebtn" style="width:220px;" id="datetime" name="start_time" value="<?=$start_time?>" onfocus="WdatePicker({startDate:'<?=date('Y-m-d',strtotime('-7 day'))?>',maxDate:'#F{$dp.$D(\'d4322\',{d:+0})}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="" autocomplete="off">
                    </div>&nbsp;
                    <div class="field">
                        结束时间：<input type="text" id="d4322" class="input datebtn" style="width:220px;" id="datetime" name="end_time"  value="<?=$end_time?>" onfocus="WdatePicker({maxDate:'<?=date('Y-m-d',strtotime('-1 day'));?>',minDate:'#F{$dp.$D(\'d4321\',{d:+0})}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="" autocomplete="off">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>


<div class="admin-main">
    <div class="line-big">
        <div class="xm3">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-red  icon-user"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=($overview['total_uv'])?:0?></strong></h2>
                            浏览UV
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm3">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-blue icon-key"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=($overview['total_pv'])?:0?></strong></h2>
                            浏览PV
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm3">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-green icon-share"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=($overview['total_order'])?:0?></strong></h2>
                            订单数量
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="xm3">
            <div class="panel dux-box dux-dashboard">
                <div class="clearfix">
                    <div class="media media-x ">
                        <div class="float-left">
                            <div class="txt dashboard-head radius-small bg-yellow icon-link"></div>
                        </div>
                        <div class="media-body text-center">
                            <h2><strong><?=($overview['total_amount'])?:0?></strong></h2>
                            订单金额
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
    </div>
    <div class="panel dux-box">
        <div class="panel-head">按天流量查看</div>
        <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
        <div id="main" style="height:400px"></div>
    </div>
    <br>
    <div class="panel dux-box">
        <div class="panel-head">详细数据</div>
        <table id="table" class="table table-bordered">
            <tbody>
            <tr>
                <th width="100">日期</th>
                <th width="*">浏览UV/PV</th>
                <th width="*">订单数</th>
                <th width="*">订单金额</th>
                <th width="*">转换率</th>
            </tr>
            <?php foreach ($spmlist as $key => $item) : ?>
                <tr>
                    <td><a><?=date('Y-m-d', strtotime($item['date']))?></a></td>
                    <td><?=$item['uv']?> / <?=$item['pv']?></td>
                    <td><?=$item['trans_num']?></td>
                    <td><?=$item['trans_amount']?></td>
                    <td><?=$item['rate']?>%</td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:20px;border-radius: 4px;">
            <?=$pagger?>
        </div>
    <?php endif;?>
</div>
    <script type="text/javascript" charset="utf-8">
        Do.ready('base',function() {
            $('.js-time').duxTime();
        });
    </script>
    <script>
        // srcipt标签式引入
        var myChart = echarts.init(document.getElementById('main'), 'macarons');
        var option = {
            tooltip : {
                trigger: 'axis'
            },
            legend: {
                data:['订单数','订单金额']
            },
            calculable : true,
            xAxis : [
                {
                    type : 'category',
                    boundaryGap : false,
                    data : [<?=implode(',', $dates)?>]
                }
            ],
            yAxis : [
                {
                    type : 'value',
                    axisLabel : {
                        formatter: '{value}'
                    }
                }
            ],
            series : [
                {
                    name:'订单数',
                    type:'line',
                    data:[<?=($trans_num)?implode(',', $trans_num):''?>]
                },
                {
                    name:'订单金额',
                    type:'line',
                    data:[<?=($trans_amount)?implode(',', $trans_amount):''?>]
                }
            ]
        };
        myChart.setOption(option);
    </script>
