<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<!-- ECharts单文件引入 -->
<script src="<?=ASSET_URL?>/static/lib/js/chart/echarts-all.js"></script>
<div class="dux-tools">
    <div class="bread-head">页面流量<span class="small">网站访问数据统计</span></div>
    <br>
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-back icon-list" href="pagedata"> 页面转化数据</a>
            <a class="button button-small bg-main icon-list" href="pvperday"> 按每天流量分析</a>
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="GET">
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        开始时间：<input type="text" id="d4321" class="input datebtn" style="width:220px;" id="datetime" name="start_time" value="<?=$start_time?>" onfocus="WdatePicker({startDate:'<?=date('Y-m-d',strtotime('-7 day'))?>',maxDate:'#F{$dp.$D(\'d4322\',{d:+0})}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="" autocomplete="off">
                    </div>&nbsp;
                    <div class="field">
                        结束时间：<input type="text" id="d4322" class="input datebtn" style="width:220px;" id="datetime" name="end_time"  value="<?=$end_time?>" onfocus="WdatePicker({maxDate:'<?=date('Y-m-d',strtotime('-1 day'));?>',minDate:'#F{$dp.$D(\'d4321\',{d:+0})}'})" style="cursor:pointer;" size="60" datatype="*" placeholder="" autocomplete="off">
                    </div>&nbsp;
                    <div class="field">
                        <select class="input js-assign" target="#tpl" name="showcase_id" datatype="*" id="parent">
                            <option value="">请选择店铺</option>
                            <?php foreach ($showcase_list as $showcase) : ?>
                                <option value="<?=$showcase['showcase_id']?>" <?=($showcase_id == $showcase['showcase_id']) ? 'selected': ''?>><?php echo $showcase['name']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>


<div class="admin-main">
    <div class="panel dux-box">
        <div class="panel-head">按天流量查看</div>
        <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
        <div id="main" style="height:400px"></div>
    </div>
    <br>
    <div class="panel dux-box">
        <div class="panel-head">详细数据</div>
        <table id="table" class="table table-bordered">
            <tbody>
            <tr>
                <th width="100">日期</th>
                <th width="*">浏览UV/PV</th>
                <th width="*">内部访问UV/PV</th>
                <th width="*">外部分享UV/PV</th>
                <th width="*">导出UV/PV</th>
                <th width="*">到店UV/PV</th>
            </tr>
            <?php foreach ($view_list as $key => $item) : ?>
                <tr>
                    <td><a><?=date('Y-m-d', strtotime($item['date']))?></a></td>
                    <td><?=$item['total_uv']?> / <?=$item['total_pv']?></td>
                    <td><?=$item['total_uv'] - $item['share_uv']?> / <?=$item['total_pv'] - $item['share_pv']?></td>
                    <td><?=$item['share_uv']?> / <?=$item['share_pv']?></td>
                    <td>0 / 0</td>
                    <td><?=$item['goods_uv']?> / <?=$item['goods_pv']?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
    <script type="text/javascript" charset="utf-8">
        Do.ready('base',function() {
            $('.js-time').duxTime();
        });
    </script>
    <script>
        // srcipt标签式引入
        var myChart = echarts.init(document.getElementById('main'), 'macarons');
        var option = {
            tooltip : {
                trigger: 'axis'
            },
            legend: {
                data:['浏览PV','浏览UV','到店PV','到店UV']
            },
            calculable : true,
            xAxis : [
                {
                    type : 'category',
                    boundaryGap : false,
                    data : [<?=implode(',', $dates)?>]
                }
            ],
            yAxis : [
                {
                    type : 'value',
                    axisLabel : {
                        formatter: '{value}'
                    }
                }
            ],
            series : [
                {
                    name:'浏览PV',
                    type:'line',
                    data:[<?=($total_pv)?implode(',', $total_pv):''?>]
                },
                {
                    name:'浏览UV',
                    type:'line',
                    data:[<?=($total_uv)?implode(',', $total_uv):''?>]
                },
                {
                    name:'到店PV',
                    type:'line',
                    data:[<?=($goods_pv)?implode(',', $goods_pv):''?>]
                },
                {
                    name:'到店UV',
                    type:'line',
                    data:[<?=($goods_uv)?implode(',', $goods_uv):''?>]
                }
            ]
        };
        myChart.setOption(option);
    </script>
