<div class="dux-tools">
  <div class="tools-function clearfix">
    <div class="float-left"> 
	<a class="button button-small bg-main icon-list" href="/index.php?m=admin&c=wechat&a=keyword&wechatid=1"> 微信账号 又一课 关键词管理</a> 
	</div>
	<div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a> 
            <ul class="drop-menu pull-right">
               <li><a href="/index.php?m=admin&c=wechat&a=addkeyword&wechatid=1">添加关键词</a></li>
            </ul>
	</div>
  </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">关键词编号</th>
                        <th width="*">关键词名称</th>
                        <th width="*">关键词</th>
                        <th width="*">关键词类型</th>
                        <th width="*">是否验证绑定</th>
                        <th width="*">关键词状态</th>
                        <th width="100">操作</th>
                    </tr>
                    <?php if (!empty($data)):?>
                    <?php foreach ($data as $key=>$val):?>
                    <tr>
                        <td><?=$val['keyword_id'];?></td>
                        <td><?=$val['keyword_name'];?></td>
                        <td><?=$val['keyword_keys'];?></td>
                        <td><span class="tag bg-green"><?php if ($val['keyword_tepy'] == 1):?>文本<?php elseif($val['keyword_tepy'] == 2):?>图文<?php elseif ($val['keyword_tepy'] == 3):?>语音<?php elseif($val['keyword_tepy'] == 4):?>图片<?php elseif($val['keyword_tepy'] == 5):?>应用<?php elseif($val['keyword_tepy'] == 6):?>接口<?php endif;?></span></td>
                        <td><span class="tag bg-red"><?php if ($val['keyword_isuser'] ==0):?>否<?php else:?>是<?php endif;?></span></td>
                        <td><span class="tag bg-red"><?php if ($val['keyword_state']== 0):?>关闭<?php else:?>开启<?php endif;?></span></td>
                        <td>
                            <a class="button bg-blue button-small icon-pencil" href="/wechat/upReply/kid/<?=$val['keyword_id'];?>/wechatid/<?php echo $id;?>" title="修改"></a>
                            <a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" url="/wechat/delete/keywordid/<?php echo $val['keyword_id'];?>/wechatid/<?php echo $id;?>" data="" title="删除"></a>
                        </td>
                    </tr>
                    <?php endforeach;?>
                    <?php endif;?>
                </tbody>
            </table>
        </div>
        <div class="panel-foot table-foot clearfix">
        <div class="float-right">
            <?php echo $page;?>
        </div>
        </div>
    </div>
</div>