<div class="dux-tools">
</div>
<div class="admin-main">
    <div class="tab dux-tab">
        <div class="panel dux-box  active">
            <div class="panel-head">
                <div class="tab-head">
                    <strong>微信接口配置</strong>
                    <ul class="tab-nav">
                        <li class="active"><a href="#tab-1">基本配置</a></li>
                        <li><a href="#tab-2">接口配置</a></li>
                        <li><a href="#tab-3">微信支付配置</a></li>
                        <li><a href="#tab-4">网站微信登录配置</a></li>
                    </ul>
                </div>
            </div>
            <div class="tab-body">
                <div class="tab-panel active" id="tab-1">
                    <div class="form-group">
                        <div class="label">
                            <label>帐号类型</label>
                        </div>
                        <div class="field">
                            <div class="button-group button-group-small radio">
                               <?php if ($data['tepy'] == 1):?>
                                <label class="button">订阅号</label>
                                <?php else:?>
                                <label class="button">服务号</label>
                                <?php endif;?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>是否认证</label>
                        </div>
                        <div class="field">
                            <div class="button-group button-group-small radio">
                                <?php if($data['isreg'] == 1):?>
                                <label class="button">是</label>
                                <?php else:?>
                                <label class="button">否</label>
                                <?php endif;?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>帐号名称</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:340px;" id="title" size="60" datatype="*"><?=$data['name'];?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>微信号</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:340px;" id="title" size="60" datatype="*"><?=$data['code'];?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>微信原始ID</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:340px;" id="title" size="60" datatype="*"><?=$data['oldcode'];?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>二维码</label>
                        </div>
                        <div class="field">
                            <input type="text" class="input show_uo_imgs" id="image" name="wechat_img" value="<?=$data['img'];?>" datatype="*">
                            <a class="button bg-blue button-small icon-picture-o" id="image_preview" href="javascript:;" > 预览</a>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>微信头像</label>
                        </div>
                        <div class="field">
                            <input type="text" class="input show_uo_imgss" id="images" name="wechat_avaimg" value="<?=$data['avaimg'];?>" datatype="*">
                            <a class="button bg-blue button-small icon-picture-o" id="image_previews" href="javascript:;" > 预览</a>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>微信关注图文链接</label>
                        </div>
                        <div class="field">
                            <input type="text" class="input" style="width:440px;" id="title" name="wechat_gurl" size="60" datatype="*" value="<?=$data['gurl'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label for="sitename">账号绑定</label>
                        </div>
                        <div class="field">
                            <div class="button-group button-group-small radio">
                                <?php if($data['isuser'] == 0):?>
                                <label class="button active">关闭</label>
                                <?php else:?>
                                <label class="button active">开启</label>
                                <?php endif;?>
                                <!--<label class="button"><input name="wechat_isuser" value="0" type="radio"><span class="icon icon-times"></span> 关闭</label>-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-panel" id="tab-2">
                    <div class="form-group">
                        <div class="label">
                            <label for="sitename">接口状态</label>
                        </div>
                        <div class="field">
                            <div class="button-group button-group-small radio">
                                <?php if ($data['isopen'] == 0):?>
                                <label class="button active">关闭</label>
                                <?php else:?>
                                <label class="button active">正常</label>
                                <?php endif;?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>微信接口Token</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:300px;" id="title" name="wechat_token" size="60" datatype="*" value=""><?=$data['token'];?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>微信接口AppID</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:300px;" id="title" name="wechat_appid" size="60" datatype="*" value=""><?=$data['appid'];?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>微信接口AppSecret</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:320px;" id="title" name="wechat_appsecret" size="60" datatype="*" value=""><?=$data['appsecret'];?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>EncodingAESKey</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:440px;" id="title" name="wechat_aeskey" size="60" datatype="*" value=""><?=$data['aeskey'];?></span>
                        </div>
                    </div>
                </div>
                <div class="tab-panel" id="tab-3">
                    <div class="form-group">
                        <div class="label">
                            <label>partnerid</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:240px;" id="title" name="wechat_partnerid" size="60" value=""><?=$data['partnerid'];?></span>
                            <div class="input-note">财付通商户身份标识</div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>partnerkey</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:240px;" id="title" name="wechat_partnerkey" size="60"  value=""><?=$data['partnerkey'];?></span>
                            <div class="input-note">财付通商户权限密钥Key</div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>paysignkey</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:320px;" id="title" name="wechat_paysignkey" size="60"  value=""><?=$data['paysignkey'];?></span>
                            <div class="input-note">商户签名密钥Key</div>
                        </div>
                    </div>
                </div>
                <div class="tab-panel" id="tab-4">
                    <div class="form-group">
                        <div class="label">
                            <label>loginappid</label>
                        </div>
                        <div class="field">
                            <span class="input" style="width:240px;" id="title" name="wechat_loginappid" size="60" value=""><?=$data['loginappid'];?></span>
                            <div class="input-note">微信公众平台获取的网站授权登录AppID</div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="label">
                            <label>loginappsecret</label>
                        </div>
                        <div class="field">
                            <span class="input" class="input" style="width:240px;" id="title" name="wechat_loginappsecret" size="60"  value=""><?=$data['loginappsecret'];?></span>
                            <div class="input-note">微信公众平台获取的网站授权登录AppSecret</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>