<div class="dux-tools">
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main icon-list" href="">微信列表</a>
        </div>
<!--            <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a> 
            <ul class="drop-menu pull-right">
                <li><a href="">添加文章</a></li>
            </ul>
        </div>-->
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="post" action="">
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="keyword" size="20" value="" placeholder="关键词">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
    <table id="table" class="table table-hover ">
        <tbody>
            <tr>
                <th width="100">微信编号</th>
                <th width="*">微信名称</th>
                <th width="*">账号类型</th>
                <th width="*">是否认证</th>
                <th width="*">自动回复</th>
                <th width="*">自定义菜单</th>
                <th width="*">微信素材</th>
                <th width="100">接口状态</th>
                <th width="*">操作</th>
            </tr>
            <?php if(!empty($data)):?>
            <?php foreach ($data as $key => $value):?>
            <tr>
                <td><?=$value['id']?></td>
                <td><?=$value['name']?></td>
                <td><span class="tag bg-green"><?php if ($value['tepy'] == 1):?>服务号<?php else:?>订阅号<?php endif;?></span></td>
                <td><span class="tag bg-green"><?php if ($value['isreg'] == 1):?>已认证<?php else:?>未认证<?php endif;?></span></td>
                <td><a class="button bg-blue button-small icon-list" id="wechat_buts" href="replay/id/<?=$value['id']?>">管理回复</a></td>
                <td><a class="button bg-blue button-small icon-list" id="wechat_buts" href="menu/id/<?=$value['id'];?>"> 管理菜单</a></td>
                <td><a class="button bg-blue button-small icon-list" id="wechat_buts" href="/wechat/material/id/<?=$value['id'];?>"> 素材管理</a></td>
                <td><span class="tag bg-green"><?php if ($value['isopen'] == 1):?>开启<?php else:?>关闭<?php endif;?></span></td>
                <td>
                    <a class="button bg-red button-small " id="wechat_buts" href="getDetails/id/<?php echo $value['id'];?>">查看详情</a>
                    <a class="button bg-blue button-small icon-pencil" href="/wechat/updetails/id/<?php echo $value['id'];?>" title="修改"></a>
                    <a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" data="3" title="删除"></a>
                </td>
            </tr>
            <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>
<div class="panel-foot table-foot clearfix">
    <div class="float-right">
        <?php echo $page;?>
    </div>
</div>