<div class="dux-tools">
  <div class="tools-function clearfix">
    <div class="float-left"> 
	<a class="button button-small bg-main icon-list" href="/wechat/index"> 微信账号 又一课 菜单管理</a> 
    </div>
  </div>
</div>
<div class="admin-main">
<form method="post" class="form-x dux-form form-auto" id="form" action="/wechat/delete">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">日志编号</th>
                        <th width="*">日志内容</th>
                    </tr>
                    <?php if (!empty($data)):?>
                    <?php foreach ($data as $key=>$val):?>
                    <tr>
                        <td><?php echo $val['id']; ?></td>
                        <td><?php echo $val['info']; ?></td>
                    </tr>
                    <?php endforeach;?>
                    <?php endif;?>
                </tbody>
            </table>
        </div>
        <div class="panel-foot table-foot clearfix">
            <div class="float-right">
                <?php echo $listpage;?>
            <ul class='pagination pagination-small'>    </ul>            
            </div>
        </div>
    </div>
</form>
</div>
