<div class="dux-tools">
    <div class="tools-function clearfix">
        <div class="float-left">
            <a class="button button-small bg-main" href="">短信群发</a>
        </div>
    </div>
</div>
<div class="table-tools clearfix ">
    <div class="float-left">
        <form method="post" action="/wechat/message" enctype="multipart/form-data">
            <div class="form-inline">
                <div class="form-group">
                    <div class="field">
                        <input type="text" class="input" id="keyword" name="keyword" size="20" value="" placeholder="关键词">
                    </div>
                </div>
                <div class="form-button">
                    <button class="button" type="submit">搜索</button>
                    <input type="file" class="button" name="import" />
                    <button class="button bg-main" type="submit">倒入数据</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
    <form method="post" action="/wechat/message">
        <div class="field">
            <textarea type="text" class="input audiolist" style="width: 1200px; height: 300px;" id="audiolist" name="message" size="60" datatype="*" placeholder="" autocomplete="off"><?php echo $data;?></textarea></br>
            <button class="button bg-main" type="submit">短信群发</button>
        </div>
    </form>
</div>
<div class="panel-foot table-foot clearfix">
    <div class="float-right">
        <?php echo $page;?>
    </div>
</div>
<script>
    Do.ready('base', function () {
    $('#table').duxTable();
    });
</script>