
<div class="dux-tools">
  <div class="tools-function clearfix">
    <div class="float-left"><a class="button button-small bg-main icon-list" href=""> 编辑至 从此不再是一个人 自定义菜单</a></div>
  </div>
</div>
<div class="admin-main">
<form method="post" class="form-x dux-form form-auto" id="form" action="/wechat/upMenu">
    <div class="panel dux-box  active">
        <div class="panel-body">
		    <div class="form-group">
                <div class="label">
                    <label>菜单分类</label>
                </div>
                <div class="field">
                    <select class="input" id="menu_cid" name="menucid">
                        <option value="0" >作为一级菜单</option>
                        <option value="1" >测试菜单1</option>
                        <option value="2" >测试菜单2</option>                    
                    </select>
                    <div class="input-note">请填写菜单所属分类</div>
                </div>
            </div>
            <div class="form-group">
                <div class="label">
                    <label>菜单名称</label>
                </div>
                <div class="field">
                    <input type="text" class="input" id="menu_name" name="menucname" datatype="*" value="<?php echo $data['name'];?>">
                    <div class="input-note">请填写菜单名称</div>
                </div>
            </div>
            <div class="form-group">
                <div class="label">
                    <label for="sitename">触发事件</label>
                </div>
                <div class="field">
                    <input type="text" class="input" id="menu_tepy" name="menuctepy" datatype="*" value="<?php echo $data['tepy'];?>">
                    <select class="input js-assign" target="#menu_tepy">
                        <option value="click" selected="selected">触发关键词</option>
                        <option value="view" >打开网页</option>
                    </select>
                    <div class="input-note">请选择菜单点击后的触发事件</div>
                </div>
            </div>
            <div class="form-group">
                <div class="label">
                    <label>触发内容</label>
                </div>
                <div class="field">
                    <input type="text" style="width:340px;" class="input" id="menu_info" name="menucinfo" datatype="*" value="<?php echo $data['info'];?>">
                    <div class="input-note">请填写菜单点击后的触发的事件内容,如果为click触发事件，填写对应的关键词编号，否则填写完整的跳转url</div>
                </div>
            </div>
        </div>
        <div class="panel-foot">
            <div class="form-button">
                <div id="tips"></div>
                <input type="hidden" name="wechatid" id="menu_wid" type="hidden" value="<?php echo $data['wid'];?>">
                <input type="hidden" name="menuid" id="menu_id" type="hidden" value="<?php echo $data['id'];?>">
                <button class="button bg-main" type="submit">保存</button>
                <button class="button bg" type="reset">重置</button>
            </div>
        </div>
    </div>
</form>
</div>
