<div class="dux-tools">
  <div class="tools-function clearfix">
    <div class="float-left"> 
	<a class="button button-small bg-main icon-list" href="/wechat/index"> 微信 又一课 素材管理</a> 
	</div>
	<div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a> 
            <ul class="drop-menu pull-right">
               <li><a href="/index.php?m=admin&c=wechat&a=addwechatpulic&wechatid=1">添加素材</a></li>
            </ul>
	</div>
  </div>
</div>
<div class="admin-main">
    <div class="panel dux-box">
        <div class="table-tools clearfix ">
            <div class="float-left">
                <form method="post" action="">
                    <div class="form-inline">
                        <div class="form-group">
                            <div class="field">
                                    <input type="text" class="input" id="keyword" name="keyword" size="20" value="" placeholder="关键词">
                            </div>
                        </div>
                        <div class="form-button">
                                <button class="button" type="submit">搜索</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">素材编号</th>
                        <th width="*">所属微信</th>
                        <th width="*">素材标题</th>
                        <th width="*">素材类型</th>
                        <th width="*">media_id</th>
                        <th width="200">更新时间</th>
                    </tr>
                    <?php if(!empty($data)):?>
                    <?php foreach ($data as $key=>$val):?>
                    <tr>
                        <td><?=$val['id'];?></td>
                        <td><?=$val['wid'];?></td>
                        <td><?=$val['contents'];?></td>
                        <td><?=$val['tepy'];?></td>
                        <td><?=$val['mediaid'];?></td>
                        <td><?=$val['date'];?></td>
                    </tr>
                    <?php endforeach;?>
                    <?php endif;?>
                </tbody>
            </table>
        </div>
        <div class="panel-foot table-foot clearfix">
            <div class="float-right">
                <?php echo $listpage;?>
            </div>
        </div>
    </div>
</div>