<div class="dux-tools">
  <div class="tools-function clearfix">
    <div class="float-left"> 
	<a class="button button-small bg-main icon-list" href="/wechat/index"> 微信账号 又一课 菜单管理</a> 
	</div>
	<div class="button-group float-right">
		<a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a> 
		<ul class="drop-menu pull-right">
		   <li><a href="/index.php?m=admin&c=wechat&a=addmenu&wechatid=1">添加菜单</a></li>
		</ul>
	</div>
  </div>
</div>
<div class="admin-main">
<form method="post" class="form-x dux-form form-auto" id="form" action="/wechat/delete">
    <div class="panel dux-box">
        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                    <tr>
                        <th width="100">菜单编号</th>
                        <th width="*">菜单名称</th>
                        <th width="*">事件类型</th>
                        <th width="*">菜单触发内容</th>
                        <th width="100">操作</th>
                    </tr>
                    <?php if(!empty($data)):?>
                    <?php foreach ($data as $key=>$val):?>
                    <tr>
                        <td><?php echo $val['menu_id']?></td>
                        <td><?php echo $val['menu_name']?></td>
                        <td><?php echo $val['menu_tepy']?></td>
                        <td><?php echo $val['menu_info']?></td>
                        <td>
                            <a class="button bg-blue button-small icon-pencil" href="/wechat/upMenu/id/<?php echo $val['menu_id'];?>/wechatid/<?php echo $id;?>" title="修改"></a>
                            <a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" data="3" title="删除"></a>
                        </td>
                    </tr>
                    <?php foreach ($val['cidlist'] as $listkey=>$listval):?>
                    <tr>
                        <td><?php echo $listval['menu_id']?></td>
                        <td>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $listval['menu_name']?></td>
                        <td><?php echo $listval['menu_tepy']?></td>
                        <td><?php echo $listval['menu_info']?></td>
                        <td>
                            <a class="button bg-blue button-small icon-pencil" href="/wechat/upMenu/id/<?php echo $val['menu_id'];?>/wechatid/<?php echo $id;?>" title="修改"></a>
                            <a class="button bg-red button-small icon-trash-o js-del" href="javascript:;" data="3" title="删除"></a>
                        </td>
                    </tr>
                    <?php endforeach;?>
                    <?php endforeach;?>
                    <?php endif;?>
                </tbody>
            </table>
        </div>
    </div>
</form>
</div>
