<style>
    .boxBorder{
        border-radius:5px;
        overflow: auto;
        border:1px solid #eee;
        margin:10px;
    }
    
    .subBar_box{
        height: auto; overflow: hidden;
        margin:5px 0 0 10px;
        
    }
    
    
</style>
<div class="dux-tools">
    <div class="bread-head">账号信息</div>
        
        
  <div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" id="form" action="/audiotopic/addDailyPackage">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <div class="panel-head">
                    <div class="tab-head">
                        <ul class="tab-nav">
                           
                            <li class="active"><a href="/charge/uchargelist/uid/<?=$uid?>/type/ANDROID" class="button-small tablists hand" style="cursor:pointer;">android充值记录</a></li>
                            <li class="active"><a href="/charge/uchargelist/uid/<?=$uid?>/type/IOS" class="button-small tablists hand" style="cursor:pointer;">ios充值记录</a></li>
                            <li class="active"><a href="/charge/buylist/uid/<?=$uid?>" class=" button-small tablists hand " style="cursor:pointer;">用户消费记录</a></li>
                        </ul>
                    </div>
                </div>
                <div class="tab-body boxBorder">



                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>充值总额</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$fillCoin;?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>消费总额</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$ubuy;?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>android账号 节操币余额</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$androidCoin;?></span>                               
                            </div>
                        </div>
                    </div>
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>ios账号 节操币余额</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$iosCoin;?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>昵称</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$uinfo['nickname'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>头像</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><img src="<?=$uinfo['avatar'];?>" height="100" /></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>手机号</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?=$uinfo['phone'];?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    <div class="tab-panel active boxBorder" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>性别</label>
                            </div>
                            <div class="field">
                                <span class="input" style="border:0;"><?php echo ($uinfo['sex']==1)?('男'):(($uinfo['sex']==2)?('女'):('保密'));?></span>                               
                            </div>
                        </div>
                    </div>
                    
                    
                    
                    
                    
                    
                    
                    
                    
                </div>    
            </div>
        </div>
    </form>   
        
        
    </div>
</div>


<div class="admin-main">
    <div id="table">
        <div class="table-responsive">
           
           
            
        </div>
        
    </div>
   
</div>