<script language="JavaScript" type="text/javascript" src="<?=ASSET_URL?>/static/js/calendar/WdatePicker.js"></script>
<div class="dux-tools">
    <div class="bread-head">电商数据报表<span class="small">数据报表</span></div><br>
</div>
<div class="admin-main">
    <form method="post" class="form-x dux-form form-auto" action="/welcome/index">
        <div class="tab dux-tab">
            <div class="panel dux-box  active">
                <!-- tab head start-->
                <div class="panel-head">
                    <div class="tab-head">
                        <strong>电商数据报表</strong>
                        <ul class="tab-nav">
                            <li class="active"><a href="#tab-1">日报表</a></li>
                            <li><a href="#tab-2">周报表</a></li>
                            <li><a href="#tab-3">月报表</a></li>
                        </ul>
                    </div>
                </div>
                <!-- tab head end -->

                <!-- table body start-->
                <div class="tab-body">
                    <!-- tab 1 start -->
                    <div class="tab-panel active" id="tab-1">
                        <div class="form-group">
                            <div class="label">
                                <label>选择日期: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input datebtn" style="width:220px;" name="time1" id="time1" onFocus="WdatePicker()" style="cursor:pointer;" size="60" datatype="*" value="<?=$time;?>" >
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>日下单总数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="<?=$data[0]['order_num']?>" id="t1-1" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>日下单总金额: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="<?=$data[0]['order_sum']?>" id="t1-2" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>日支付订单总数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="<?=$data[0]['paied_num']?>" id="t1-3" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>日支付总额: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="<?=$data[0]['paied_sum']?>" id="t1-4" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>微信支付笔数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="<?=$data[0]['paied_num_wx']?>" id="t1-5" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>京东支付笔数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="<?=$data[0]['paied_num_jd']?>" id="t1-6" readOnly="true">
                            </div>
                        </div>
                    </div>
                    <!-- tab 1 end -->
                    
                    <!-- start tab2 -->
                    <div class="tab-panel" id="tab-2">
                        <div class="form-group">
                            <div class="label">
                                <label>选择日期: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input datebtn" style="width:220px;" name="time2" id="time2" onfocus="WdatePicker({maxDate:''})" style="cursor:pointer;" size="60" datatype="*" value="<?=$time?>" >
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>周下单总笔数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t2-1" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>周订单总金额: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t2-2" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>周付款笔数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t2-3" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>周付款总金额: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t2-4" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>微信支付笔数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t2-5" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>京东支付笔数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t2-6" readOnly="true">
                            </div>
                        </div>
                    </div>
                    <!-- end tab2 -->

                    <!-- start tab3 -->
                    <div class="tab-panel" id="tab-3">
                        <div class="form-group">
                            <div class="label">
                                <label>选择月份: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input datebtn" style="width:220px;" name="time3" id="time3" onfocus="WdatePicker({maxDate:''})" style="cursor:pointer;" size="60" datatype="*" value="<?=$time?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>月下单总笔数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t3-1" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>月订单总金额: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t3-2" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>月付款笔数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t3-3" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>月付款总金额: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t3-4" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>微信支付笔数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t3-5" readOnly="true">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="label">
                                <label>京东支付笔数: </label>
                            </div>
                            <div class="field">
                                <input type="text" class="input" style="width:220px;" size="60" value="" id="t3-6" readOnly="true">
                            </div>
                        </div>
                    </div>
                    <!-- end tab3 -->
                </div>
                <!--table end-->
                <div class="panel-foot">
                    <div class="form-button">
                        <input type="button" value="提交" class="button bg-main" id="submit"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
<script type="text/javascript" charset="utf-8">
    Do.ready('base',function() {
        $('.js-time').duxTime();
    });
</script>
<script>
    //ajax提交
    $(document).ready(function(){
        $('#submit').click(function(){
            var timeOne = $('#time1').val();
            var timeTwo = $('#time2').val();
            var timeThree = $('#time3').val();
            $.ajax({
                url:'/welcome/index',
                type:'POST',
                data:{time1:timeOne,time2:timeTwo,time3:timeThree},
                dataType:'json',
                success:function(data){
                    $("#t1-1").val(data.ta1[0].order_num);
                    $("#t1-2").val(data.ta1[0].order_sum);
                    $("#t1-3").val(data.ta1[0].paied_num);
                    $("#t1-4").val(data.ta1[0].paied_sum);
                    $("#t1-5").val(data.ta1[0].paied_num_wx);
                    $("#t1-6").val(data.ta1[0].paied_num_jd);
                    $("#t2-1").val(data.ta2.order_num);
                    $("#t2-2").val(data.ta2.order_sum);
                    $("#t2-3").val(data.ta2.paied_num);
                    $("#t2-4").val(data.ta2.paied_sum);
                    $("#t2-5").val(data.ta2.paied_num_wx);
                    $("#t2-6").val(data.ta2.paied_num_jd);
                    $("#t3-1").val(data.ta3.order_num);
                    $("#t3-2").val(data.ta3.order_sum);
                    $("#t3-3").val(data.ta3.paied_num);
                    $("#t3-4").val(data.ta3.paied_sum);
                    $("#t3-5").val(data.ta3.paied_num_wx);
                    $("#t3-6").val(data.ta3.paied_num_jd);
                }
            })
        })
    })
</script>
</div>