<div class="admin-main">
    <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
        <input type="text" class="input pull-left" style="width:220px;" id="search_title" value="<?=$search_title?>" name="search_title" size="60" placeholder="输入来源搜索">
        <button class="button bg-main search" type="button">搜索</button>
    </div>
    <div class="panel dux-box">

        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                <tr>
                    <th width="100">ID</th>
                    <th width="*">来源(哪本书)</th>
                    <th width="*">金句内容</th>
                    <th width="*">状态</th>
                    <th width="*">收藏总数</th>

                    <th width="*">操作</th>
                </tr>
                <?php if ($list) : ?>
                    <?php foreach($list as $val) : ?>
                        <tr>
                            <td><?php echo $val['id']; ?></td>
                            <td class="verse_title_<?=$val['id']?>"><?php echo $val['source']; ?></td>
                            <td><?php echo $val['content']; ?></td>


                            <td>
                                <?php if ($val['state'] == 1) : ?>
                                    <span class="tag bg-green">显示</span>
                                <?php elseif($val['state'] == 0) : ?>
                                    <span class="tag">不显示</span>
                                <?php endif; ?>
                            </td>
                            <td><?php echo $val['count']; ?></td>
                            <td>
                                <a class="button bg-green button-small icon-plus" value="<?php echo $val['id']; ?>" title="编辑"></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>

                </tbody>
            </table>
        </div>
    </div>
    <?php if($pagger):?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?=$pagger?>
            <a class="button bg-main selectVerseBtn pull-right " style="cursor:pointer;">好了</a>
        </div>
    <?php endif;?>
</div>