<div class="dux-tools">
    <div class="bread-head">金句管理<span class="small">金句列表</span>

        <div class="button-group float-right">
            <a class="button button-small bg-dot icon-plus dropdown-toggle"> 添加 <span class="downward"></span></a>
            <ul class="drop-menu pull-right">
                <li><a href="/verse/add">添加金句</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="admin-main">
    <?php if ($pagger): ?>
        <div class="panel dux-box panel-foot clearfix" style="margin-bottom:10px;border-radius: 4px;">
            <?= $pagger ?>
        </div>
    <?php endif; ?>
    <div class="panel dux-box">

        <div class="table-responsive">
            <table id="table" class="table table-hover ">
                <tbody>
                <tr>
                    <th width="100">ID</th>
                    <th width="*">金句来源(于哪本书)</th>
                    <th width="*">内容</th>
                    <th width="*">关联的电子书</th>
                    <th width="*">状态</th>
                    <th width="*">收藏统计</th>
                    <th width="*">操作</th>
                </tr>
                <?php if ($list) : ?>
                    <?php foreach ($list as $val) : ?>
                        <tr>
                            <td><?php echo $val['id']; ?></td>
                            <td><?php echo $val['source']; ?></td>
                            <td><?php echo $val['content']; ?></td>
                            <td>
                                <?php if (isset($val['relationBooks']) && !empty($val['relationBooks'])) : ?>
                                    <?php foreach ($val['relationBooks'] as $value) : ?>
                                        <a href="/book/list/id/<?php echo $value['id']; ?>"><?php echo $value['operating_title']; ?></a>
                                        <br>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if ($val['state'] == 1) : ?>
                                    <span class="tag bg-green">显示</span>
                                <?php elseif ($val['status'] == 0) : ?>
                                    <span class="tag">不显示</span>
                                <?php endif; ?>
                            </td>
                            <td><?php echo $val['count']; ?></td>
                            <td>
                                <a class="button bg-blue button-small icon-pencil"
                                   href="/verse/edit/id/<?php echo $val['id']; ?>" title="编辑"></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>

                </tbody>
            </table>
        </div>
    </div>
    <?php if ($pagger): ?>
        <div class="panel dux-box panel-foot clearfix" style="margin-top:10px;border-radius: 4px;">
            <?= $pagger ?>
        </div>
    <?php endif; ?>
</div>